package dev.silenium.libs.av.core

import dev.silenium.libs.av.foreign.NativeEnum
import org.ffmpeg.bindings.FFMPEG

enum class SampleFormat(override val value: Int) : NativeEnum {
    AV_SAMPLE_FMT_NONE(FFMPEG.AV_SAMPLE_FMT_NONE()),
    AV_SAMPLE_FMT_U8(FFMPEG.AV_SAMPLE_FMT_U8()),
    AV_SAMPLE_FMT_S16(FFMPEG.AV_SAMPLE_FMT_S16()),
    AV_SAMPLE_FMT_S32(FFMPEG.AV_SAMPLE_FMT_S32()),
    AV_SAMPLE_FMT_FLT(FFMPEG.AV_SAMPLE_FMT_FLT()),
    AV_SAMPLE_FMT_DBL(FFMPEG.AV_SAMPLE_FMT_DBL()),
    AV_SAMPLE_FMT_U8P(FFMPEG.AV_SAMPLE_FMT_U8P()),
    AV_SAMPLE_FMT_S16P(FFMPEG.AV_SAMPLE_FMT_S16P()),
    AV_SAMPLE_FMT_S32P(FFMPEG.AV_SAMPLE_FMT_S32P()),
    AV_SAMPLE_FMT_FLTP(FFMPEG.AV_SAMPLE_FMT_FLTP()),
    AV_SAMPLE_FMT_DBLP(FFMPEG.AV_SAMPLE_FMT_DBLP()),
    AV_SAMPLE_FMT_S64(FFMPEG.AV_SAMPLE_FMT_S64()),
    AV_SAMPLE_FMT_S64P(FFMPEG.AV_SAMPLE_FMT_S64P()),
    AV_SAMPLE_FMT_NB(FFMPEG.AV_SAMPLE_FMT_NB()),
}
