// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVAmbientViewingEnvironment {
 *     AVRational ambient_illuminance;
 *     AVRational ambient_light_x;
 *     AVRational ambient_light_y;
 * }
 * }
 */
public class AVAmbientViewingEnvironment {

    AVAmbientViewingEnvironment() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        AVRational.layout().withName("ambient_illuminance"),
        AVRational.layout().withName("ambient_light_x"),
        AVRational.layout().withName("ambient_light_y")
    ).withName("AVAmbientViewingEnvironment");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ambient_illuminance$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ambient_illuminance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational ambient_illuminance
     * }
     */
    public static final GroupLayout ambient_illuminance$layout() {
        return ambient_illuminance$LAYOUT;
    }

    private static final long ambient_illuminance$OFFSET = $LAYOUT.byteOffset(groupElement("ambient_illuminance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational ambient_illuminance
     * }
     */
    public static final long ambient_illuminance$offset() {
        return ambient_illuminance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational ambient_illuminance
     * }
     */
    public static MemorySegment ambient_illuminance(MemorySegment struct) {
        return struct.asSlice(ambient_illuminance$OFFSET, ambient_illuminance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational ambient_illuminance
     * }
     */
    public static void ambient_illuminance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ambient_illuminance$OFFSET, ambient_illuminance$LAYOUT.byteSize());
    }

    private static final GroupLayout ambient_light_x$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ambient_light_x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational ambient_light_x
     * }
     */
    public static final GroupLayout ambient_light_x$layout() {
        return ambient_light_x$LAYOUT;
    }

    private static final long ambient_light_x$OFFSET = $LAYOUT.byteOffset(groupElement("ambient_light_x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational ambient_light_x
     * }
     */
    public static final long ambient_light_x$offset() {
        return ambient_light_x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational ambient_light_x
     * }
     */
    public static MemorySegment ambient_light_x(MemorySegment struct) {
        return struct.asSlice(ambient_light_x$OFFSET, ambient_light_x$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational ambient_light_x
     * }
     */
    public static void ambient_light_x(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ambient_light_x$OFFSET, ambient_light_x$LAYOUT.byteSize());
    }

    private static final GroupLayout ambient_light_y$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ambient_light_y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational ambient_light_y
     * }
     */
    public static final GroupLayout ambient_light_y$layout() {
        return ambient_light_y$LAYOUT;
    }

    private static final long ambient_light_y$OFFSET = $LAYOUT.byteOffset(groupElement("ambient_light_y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational ambient_light_y
     * }
     */
    public static final long ambient_light_y$offset() {
        return ambient_light_y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational ambient_light_y
     * }
     */
    public static MemorySegment ambient_light_y(MemorySegment struct) {
        return struct.asSlice(ambient_light_y$OFFSET, ambient_light_y$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational ambient_light_y
     * }
     */
    public static void ambient_light_y(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ambient_light_y$OFFSET, ambient_light_y$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

