// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVBlowfish {
 *     uint32_t p[18];
 *     uint32_t s[4][256];
 * }
 * }
 */
public class AVBlowfish {

    AVBlowfish() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(18, FFMPEG.C_INT).withName("p"),
        MemoryLayout.sequenceLayout(4, MemoryLayout.sequenceLayout(256, FFMPEG.C_INT)).withName("s")
    ).withName("AVBlowfish");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout p$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("p"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t p[18]
     * }
     */
    public static final SequenceLayout p$layout() {
        return p$LAYOUT;
    }

    private static final long p$OFFSET = $LAYOUT.byteOffset(groupElement("p"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t p[18]
     * }
     */
    public static final long p$offset() {
        return p$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t p[18]
     * }
     */
    public static MemorySegment p(MemorySegment struct) {
        return struct.asSlice(p$OFFSET, p$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t p[18]
     * }
     */
    public static void p(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, p$OFFSET, p$LAYOUT.byteSize());
    }

    private static long[] p$DIMS = { 18 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint32_t p[18]
     * }
     */
    public static long[] p$dimensions() {
        return p$DIMS;
    }
    private static final VarHandle p$ELEM_HANDLE = p$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint32_t p[18]
     * }
     */
    public static int p(MemorySegment struct, long index0) {
        return (int)p$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint32_t p[18]
     * }
     */
    public static void p(MemorySegment struct, long index0, int fieldValue) {
        p$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout s$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("s"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t s[4][256]
     * }
     */
    public static final SequenceLayout s$layout() {
        return s$LAYOUT;
    }

    private static final long s$OFFSET = $LAYOUT.byteOffset(groupElement("s"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t s[4][256]
     * }
     */
    public static final long s$offset() {
        return s$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t s[4][256]
     * }
     */
    public static MemorySegment s(MemorySegment struct) {
        return struct.asSlice(s$OFFSET, s$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t s[4][256]
     * }
     */
    public static void s(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, s$OFFSET, s$LAYOUT.byteSize());
    }

    private static long[] s$DIMS = { 4, 256 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint32_t s[4][256]
     * }
     */
    public static long[] s$dimensions() {
        return s$DIMS;
    }
    private static final VarHandle s$ELEM_HANDLE = s$LAYOUT.varHandle(sequenceElement(), sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint32_t s[4][256]
     * }
     */
    public static int s(MemorySegment struct, long index0, long index1) {
        return (int)s$ELEM_HANDLE.get(struct, 0L, index0, index1);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint32_t s[4][256]
     * }
     */
    public static void s(MemorySegment struct, long index0, long index1, int fieldValue) {
        s$ELEM_HANDLE.set(struct, 0L, index0, index1, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

