// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVBSFContext {
 *     const AVClass *av_class;
 *     const struct AVBitStreamFilter *filter;
 *     void *priv_data;
 *     AVCodecParameters *par_in;
 *     AVCodecParameters *par_out;
 *     AVRational time_base_in;
 *     AVRational time_base_out;
 * }
 * }
 */
public class AVBSFContext {

    AVBSFContext() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("av_class"),
        FFMPEG.C_POINTER.withName("filter"),
        FFMPEG.C_POINTER.withName("priv_data"),
        FFMPEG.C_POINTER.withName("par_in"),
        FFMPEG.C_POINTER.withName("par_out"),
        AVRational.layout().withName("time_base_in"),
        AVRational.layout().withName("time_base_out")
    ).withName("AVBSFContext");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout av_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("av_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final AddressLayout av_class$layout() {
        return av_class$LAYOUT;
    }

    private static final long av_class$OFFSET = $LAYOUT.byteOffset(groupElement("av_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final long av_class$offset() {
        return av_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static MemorySegment av_class(MemorySegment struct) {
        return struct.get(av_class$LAYOUT, av_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static void av_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(av_class$LAYOUT, av_class$OFFSET, fieldValue);
    }

    private static final AddressLayout filter$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("filter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const struct AVBitStreamFilter *filter
     * }
     */
    public static final AddressLayout filter$layout() {
        return filter$LAYOUT;
    }

    private static final long filter$OFFSET = $LAYOUT.byteOffset(groupElement("filter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const struct AVBitStreamFilter *filter
     * }
     */
    public static final long filter$offset() {
        return filter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const struct AVBitStreamFilter *filter
     * }
     */
    public static MemorySegment filter(MemorySegment struct) {
        return struct.get(filter$LAYOUT, filter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const struct AVBitStreamFilter *filter
     * }
     */
    public static void filter(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(filter$LAYOUT, filter$OFFSET, fieldValue);
    }

    private static final AddressLayout priv_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("priv_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *priv_data
     * }
     */
    public static final AddressLayout priv_data$layout() {
        return priv_data$LAYOUT;
    }

    private static final long priv_data$OFFSET = $LAYOUT.byteOffset(groupElement("priv_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *priv_data
     * }
     */
    public static final long priv_data$offset() {
        return priv_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *priv_data
     * }
     */
    public static MemorySegment priv_data(MemorySegment struct) {
        return struct.get(priv_data$LAYOUT, priv_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *priv_data
     * }
     */
    public static void priv_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(priv_data$LAYOUT, priv_data$OFFSET, fieldValue);
    }

    private static final AddressLayout par_in$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("par_in"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVCodecParameters *par_in
     * }
     */
    public static final AddressLayout par_in$layout() {
        return par_in$LAYOUT;
    }

    private static final long par_in$OFFSET = $LAYOUT.byteOffset(groupElement("par_in"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVCodecParameters *par_in
     * }
     */
    public static final long par_in$offset() {
        return par_in$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVCodecParameters *par_in
     * }
     */
    public static MemorySegment par_in(MemorySegment struct) {
        return struct.get(par_in$LAYOUT, par_in$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVCodecParameters *par_in
     * }
     */
    public static void par_in(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(par_in$LAYOUT, par_in$OFFSET, fieldValue);
    }

    private static final AddressLayout par_out$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("par_out"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVCodecParameters *par_out
     * }
     */
    public static final AddressLayout par_out$layout() {
        return par_out$LAYOUT;
    }

    private static final long par_out$OFFSET = $LAYOUT.byteOffset(groupElement("par_out"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVCodecParameters *par_out
     * }
     */
    public static final long par_out$offset() {
        return par_out$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVCodecParameters *par_out
     * }
     */
    public static MemorySegment par_out(MemorySegment struct) {
        return struct.get(par_out$LAYOUT, par_out$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVCodecParameters *par_out
     * }
     */
    public static void par_out(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(par_out$LAYOUT, par_out$OFFSET, fieldValue);
    }

    private static final GroupLayout time_base_in$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("time_base_in"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational time_base_in
     * }
     */
    public static final GroupLayout time_base_in$layout() {
        return time_base_in$LAYOUT;
    }

    private static final long time_base_in$OFFSET = $LAYOUT.byteOffset(groupElement("time_base_in"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational time_base_in
     * }
     */
    public static final long time_base_in$offset() {
        return time_base_in$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational time_base_in
     * }
     */
    public static MemorySegment time_base_in(MemorySegment struct) {
        return struct.asSlice(time_base_in$OFFSET, time_base_in$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational time_base_in
     * }
     */
    public static void time_base_in(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, time_base_in$OFFSET, time_base_in$LAYOUT.byteSize());
    }

    private static final GroupLayout time_base_out$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("time_base_out"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational time_base_out
     * }
     */
    public static final GroupLayout time_base_out$layout() {
        return time_base_out$LAYOUT;
    }

    private static final long time_base_out$OFFSET = $LAYOUT.byteOffset(groupElement("time_base_out"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational time_base_out
     * }
     */
    public static final long time_base_out$offset() {
        return time_base_out$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational time_base_out
     * }
     */
    public static MemorySegment time_base_out(MemorySegment struct) {
        return struct.asSlice(time_base_out$OFFSET, time_base_out$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational time_base_out
     * }
     */
    public static void time_base_out(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, time_base_out$OFFSET, time_base_out$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

