// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVColorPrimariesDesc {
 *     AVWhitepointCoefficients wp;
 *     AVPrimaryCoefficients prim;
 * }
 * }
 */
public class AVColorPrimariesDesc {

    AVColorPrimariesDesc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        AVCIExy.layout().withName("wp"),
        AVPrimaryCoefficients.layout().withName("prim")
    ).withName("AVColorPrimariesDesc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout wp$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("wp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVWhitepointCoefficients wp
     * }
     */
    public static final GroupLayout wp$layout() {
        return wp$LAYOUT;
    }

    private static final long wp$OFFSET = $LAYOUT.byteOffset(groupElement("wp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVWhitepointCoefficients wp
     * }
     */
    public static final long wp$offset() {
        return wp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVWhitepointCoefficients wp
     * }
     */
    public static MemorySegment wp(MemorySegment struct) {
        return struct.asSlice(wp$OFFSET, wp$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVWhitepointCoefficients wp
     * }
     */
    public static void wp(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, wp$OFFSET, wp$LAYOUT.byteSize());
    }

    private static final GroupLayout prim$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("prim"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVPrimaryCoefficients prim
     * }
     */
    public static final GroupLayout prim$layout() {
        return prim$LAYOUT;
    }

    private static final long prim$OFFSET = $LAYOUT.byteOffset(groupElement("prim"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVPrimaryCoefficients prim
     * }
     */
    public static final long prim$offset() {
        return prim$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVPrimaryCoefficients prim
     * }
     */
    public static MemorySegment prim(MemorySegment struct) {
        return struct.asSlice(prim$OFFSET, prim$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVPrimaryCoefficients prim
     * }
     */
    public static void prim(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, prim$OFFSET, prim$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

