// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVComplexDouble {
 *     double re;
 *     double im;
 * }
 * }
 */
public class AVComplexDouble {

    AVComplexDouble() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_DOUBLE.withName("re"),
        FFMPEG.C_DOUBLE.withName("im")
    ).withName("AVComplexDouble");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble re$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("re"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double re
     * }
     */
    public static final OfDouble re$layout() {
        return re$LAYOUT;
    }

    private static final long re$OFFSET = $LAYOUT.byteOffset(groupElement("re"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double re
     * }
     */
    public static final long re$offset() {
        return re$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double re
     * }
     */
    public static double re(MemorySegment struct) {
        return struct.get(re$LAYOUT, re$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double re
     * }
     */
    public static void re(MemorySegment struct, double fieldValue) {
        struct.set(re$LAYOUT, re$OFFSET, fieldValue);
    }

    private static final OfDouble im$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("im"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double im
     * }
     */
    public static final OfDouble im$layout() {
        return im$LAYOUT;
    }

    private static final long im$OFFSET = $LAYOUT.byteOffset(groupElement("im"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double im
     * }
     */
    public static final long im$offset() {
        return im$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double im
     * }
     */
    public static double im(MemorySegment struct) {
        return struct.get(im$LAYOUT, im$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double im
     * }
     */
    public static void im(MemorySegment struct, double fieldValue) {
        struct.set(im$LAYOUT, im$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

