// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDCT {
 *     const AVClass *av_class;
 *     void (*idct)(int16_t *);
 *     uint8_t idct_permutation[64];
 *     void (*fdct)(int16_t *);
 *     int dct_algo;
 *     int idct_algo;
 *     void (*get_pixels)(int16_t *, const uint8_t *, ptrdiff_t);
 *     int bits_per_sample;
 *     void (*get_pixels_unaligned)(int16_t *, const uint8_t *, ptrdiff_t);
 * }
 * }
 */
public class AVDCT {

    AVDCT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("av_class"),
        FFMPEG.C_POINTER.withName("idct"),
        MemoryLayout.sequenceLayout(64, FFMPEG.C_CHAR).withName("idct_permutation"),
        FFMPEG.C_POINTER.withName("fdct"),
        FFMPEG.C_INT.withName("dct_algo"),
        FFMPEG.C_INT.withName("idct_algo"),
        FFMPEG.C_POINTER.withName("get_pixels"),
        FFMPEG.C_INT.withName("bits_per_sample"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("get_pixels_unaligned")
    ).withName("AVDCT");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout av_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("av_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final AddressLayout av_class$layout() {
        return av_class$LAYOUT;
    }

    private static final long av_class$OFFSET = $LAYOUT.byteOffset(groupElement("av_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final long av_class$offset() {
        return av_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static MemorySegment av_class(MemorySegment struct) {
        return struct.get(av_class$LAYOUT, av_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static void av_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(av_class$LAYOUT, av_class$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*idct)(int16_t *)
     * }
     */
    public final static class idct {

        private idct() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            FFMPEG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = FFMPEG.upcallHandle(idct.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(idct.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout idct$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("idct"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*idct)(int16_t *)
     * }
     */
    public static final AddressLayout idct$layout() {
        return idct$LAYOUT;
    }

    private static final long idct$OFFSET = $LAYOUT.byteOffset(groupElement("idct"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*idct)(int16_t *)
     * }
     */
    public static final long idct$offset() {
        return idct$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*idct)(int16_t *)
     * }
     */
    public static MemorySegment idct(MemorySegment struct) {
        return struct.get(idct$LAYOUT, idct$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*idct)(int16_t *)
     * }
     */
    public static void idct(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(idct$LAYOUT, idct$OFFSET, fieldValue);
    }

    private static final SequenceLayout idct_permutation$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("idct_permutation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t idct_permutation[64]
     * }
     */
    public static final SequenceLayout idct_permutation$layout() {
        return idct_permutation$LAYOUT;
    }

    private static final long idct_permutation$OFFSET = $LAYOUT.byteOffset(groupElement("idct_permutation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t idct_permutation[64]
     * }
     */
    public static final long idct_permutation$offset() {
        return idct_permutation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t idct_permutation[64]
     * }
     */
    public static MemorySegment idct_permutation(MemorySegment struct) {
        return struct.asSlice(idct_permutation$OFFSET, idct_permutation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t idct_permutation[64]
     * }
     */
    public static void idct_permutation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, idct_permutation$OFFSET, idct_permutation$LAYOUT.byteSize());
    }

    private static long[] idct_permutation$DIMS = { 64 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t idct_permutation[64]
     * }
     */
    public static long[] idct_permutation$dimensions() {
        return idct_permutation$DIMS;
    }
    private static final VarHandle idct_permutation$ELEM_HANDLE = idct_permutation$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t idct_permutation[64]
     * }
     */
    public static byte idct_permutation(MemorySegment struct, long index0) {
        return (byte)idct_permutation$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t idct_permutation[64]
     * }
     */
    public static void idct_permutation(MemorySegment struct, long index0, byte fieldValue) {
        idct_permutation$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*fdct)(int16_t *)
     * }
     */
    public final static class fdct {

        private fdct() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            FFMPEG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = FFMPEG.upcallHandle(fdct.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(fdct.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout fdct$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fdct"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*fdct)(int16_t *)
     * }
     */
    public static final AddressLayout fdct$layout() {
        return fdct$LAYOUT;
    }

    private static final long fdct$OFFSET = $LAYOUT.byteOffset(groupElement("fdct"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*fdct)(int16_t *)
     * }
     */
    public static final long fdct$offset() {
        return fdct$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*fdct)(int16_t *)
     * }
     */
    public static MemorySegment fdct(MemorySegment struct) {
        return struct.get(fdct$LAYOUT, fdct$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*fdct)(int16_t *)
     * }
     */
    public static void fdct(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fdct$LAYOUT, fdct$OFFSET, fieldValue);
    }

    private static final OfInt dct_algo$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dct_algo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dct_algo
     * }
     */
    public static final OfInt dct_algo$layout() {
        return dct_algo$LAYOUT;
    }

    private static final long dct_algo$OFFSET = $LAYOUT.byteOffset(groupElement("dct_algo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dct_algo
     * }
     */
    public static final long dct_algo$offset() {
        return dct_algo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dct_algo
     * }
     */
    public static int dct_algo(MemorySegment struct) {
        return struct.get(dct_algo$LAYOUT, dct_algo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dct_algo
     * }
     */
    public static void dct_algo(MemorySegment struct, int fieldValue) {
        struct.set(dct_algo$LAYOUT, dct_algo$OFFSET, fieldValue);
    }

    private static final OfInt idct_algo$LAYOUT = (OfInt)$LAYOUT.select(groupElement("idct_algo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int idct_algo
     * }
     */
    public static final OfInt idct_algo$layout() {
        return idct_algo$LAYOUT;
    }

    private static final long idct_algo$OFFSET = $LAYOUT.byteOffset(groupElement("idct_algo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int idct_algo
     * }
     */
    public static final long idct_algo$offset() {
        return idct_algo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int idct_algo
     * }
     */
    public static int idct_algo(MemorySegment struct) {
        return struct.get(idct_algo$LAYOUT, idct_algo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int idct_algo
     * }
     */
    public static void idct_algo(MemorySegment struct, int fieldValue) {
        struct.set(idct_algo$LAYOUT, idct_algo$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*get_pixels)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public final static class get_pixels {

        private get_pixels() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, long _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            FFMPEG.C_POINTER,
            FFMPEG.C_POINTER,
            FFMPEG.C_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = FFMPEG.upcallHandle(get_pixels.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_pixels.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, long _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_pixels$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_pixels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*get_pixels)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public static final AddressLayout get_pixels$layout() {
        return get_pixels$LAYOUT;
    }

    private static final long get_pixels$OFFSET = $LAYOUT.byteOffset(groupElement("get_pixels"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*get_pixels)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public static final long get_pixels$offset() {
        return get_pixels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*get_pixels)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public static MemorySegment get_pixels(MemorySegment struct) {
        return struct.get(get_pixels$LAYOUT, get_pixels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*get_pixels)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public static void get_pixels(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_pixels$LAYOUT, get_pixels$OFFSET, fieldValue);
    }

    private static final OfInt bits_per_sample$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bits_per_sample"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int bits_per_sample
     * }
     */
    public static final OfInt bits_per_sample$layout() {
        return bits_per_sample$LAYOUT;
    }

    private static final long bits_per_sample$OFFSET = $LAYOUT.byteOffset(groupElement("bits_per_sample"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int bits_per_sample
     * }
     */
    public static final long bits_per_sample$offset() {
        return bits_per_sample$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int bits_per_sample
     * }
     */
    public static int bits_per_sample(MemorySegment struct) {
        return struct.get(bits_per_sample$LAYOUT, bits_per_sample$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int bits_per_sample
     * }
     */
    public static void bits_per_sample(MemorySegment struct, int fieldValue) {
        struct.set(bits_per_sample$LAYOUT, bits_per_sample$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*get_pixels_unaligned)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public final static class get_pixels_unaligned {

        private get_pixels_unaligned() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, MemorySegment _x1, long _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            FFMPEG.C_POINTER,
            FFMPEG.C_POINTER,
            FFMPEG.C_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = FFMPEG.upcallHandle(get_pixels_unaligned.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(get_pixels_unaligned.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, long _x2) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout get_pixels_unaligned$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_pixels_unaligned"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*get_pixels_unaligned)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public static final AddressLayout get_pixels_unaligned$layout() {
        return get_pixels_unaligned$LAYOUT;
    }

    private static final long get_pixels_unaligned$OFFSET = $LAYOUT.byteOffset(groupElement("get_pixels_unaligned"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*get_pixels_unaligned)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public static final long get_pixels_unaligned$offset() {
        return get_pixels_unaligned$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*get_pixels_unaligned)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public static MemorySegment get_pixels_unaligned(MemorySegment struct) {
        return struct.get(get_pixels_unaligned$LAYOUT, get_pixels_unaligned$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*get_pixels_unaligned)(int16_t *, const uint8_t *, ptrdiff_t)
     * }
     */
    public static void get_pixels_unaligned(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_pixels_unaligned$LAYOUT, get_pixels_unaligned$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

