// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDOVIDmLevel10 {
 *     uint8_t target_display_index;
 *     uint16_t target_max_pq;
 *     uint16_t target_min_pq;
 *     uint8_t target_primary_index;
 *     AVColorPrimariesDesc target_display_primaries;
 * }
 * }
 */
public class AVDOVIDmLevel10 {

    AVDOVIDmLevel10() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_CHAR.withName("target_display_index"),
        MemoryLayout.paddingLayout(1),
        FFMPEG.C_SHORT.withName("target_max_pq"),
        FFMPEG.C_SHORT.withName("target_min_pq"),
        FFMPEG.C_CHAR.withName("target_primary_index"),
        MemoryLayout.paddingLayout(1),
        AVColorPrimariesDesc.layout().withName("target_display_primaries")
    ).withName("AVDOVIDmLevel10");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte target_display_index$LAYOUT = (OfByte)$LAYOUT.select(groupElement("target_display_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t target_display_index
     * }
     */
    public static final OfByte target_display_index$layout() {
        return target_display_index$LAYOUT;
    }

    private static final long target_display_index$OFFSET = $LAYOUT.byteOffset(groupElement("target_display_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t target_display_index
     * }
     */
    public static final long target_display_index$offset() {
        return target_display_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t target_display_index
     * }
     */
    public static byte target_display_index(MemorySegment struct) {
        return struct.get(target_display_index$LAYOUT, target_display_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t target_display_index
     * }
     */
    public static void target_display_index(MemorySegment struct, byte fieldValue) {
        struct.set(target_display_index$LAYOUT, target_display_index$OFFSET, fieldValue);
    }

    private static final OfShort target_max_pq$LAYOUT = (OfShort)$LAYOUT.select(groupElement("target_max_pq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t target_max_pq
     * }
     */
    public static final OfShort target_max_pq$layout() {
        return target_max_pq$LAYOUT;
    }

    private static final long target_max_pq$OFFSET = $LAYOUT.byteOffset(groupElement("target_max_pq"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t target_max_pq
     * }
     */
    public static final long target_max_pq$offset() {
        return target_max_pq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t target_max_pq
     * }
     */
    public static short target_max_pq(MemorySegment struct) {
        return struct.get(target_max_pq$LAYOUT, target_max_pq$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t target_max_pq
     * }
     */
    public static void target_max_pq(MemorySegment struct, short fieldValue) {
        struct.set(target_max_pq$LAYOUT, target_max_pq$OFFSET, fieldValue);
    }

    private static final OfShort target_min_pq$LAYOUT = (OfShort)$LAYOUT.select(groupElement("target_min_pq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t target_min_pq
     * }
     */
    public static final OfShort target_min_pq$layout() {
        return target_min_pq$LAYOUT;
    }

    private static final long target_min_pq$OFFSET = $LAYOUT.byteOffset(groupElement("target_min_pq"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t target_min_pq
     * }
     */
    public static final long target_min_pq$offset() {
        return target_min_pq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t target_min_pq
     * }
     */
    public static short target_min_pq(MemorySegment struct) {
        return struct.get(target_min_pq$LAYOUT, target_min_pq$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t target_min_pq
     * }
     */
    public static void target_min_pq(MemorySegment struct, short fieldValue) {
        struct.set(target_min_pq$LAYOUT, target_min_pq$OFFSET, fieldValue);
    }

    private static final OfByte target_primary_index$LAYOUT = (OfByte)$LAYOUT.select(groupElement("target_primary_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t target_primary_index
     * }
     */
    public static final OfByte target_primary_index$layout() {
        return target_primary_index$LAYOUT;
    }

    private static final long target_primary_index$OFFSET = $LAYOUT.byteOffset(groupElement("target_primary_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t target_primary_index
     * }
     */
    public static final long target_primary_index$offset() {
        return target_primary_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t target_primary_index
     * }
     */
    public static byte target_primary_index(MemorySegment struct) {
        return struct.get(target_primary_index$LAYOUT, target_primary_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t target_primary_index
     * }
     */
    public static void target_primary_index(MemorySegment struct, byte fieldValue) {
        struct.set(target_primary_index$LAYOUT, target_primary_index$OFFSET, fieldValue);
    }

    private static final GroupLayout target_display_primaries$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("target_display_primaries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVColorPrimariesDesc target_display_primaries
     * }
     */
    public static final GroupLayout target_display_primaries$layout() {
        return target_display_primaries$LAYOUT;
    }

    private static final long target_display_primaries$OFFSET = $LAYOUT.byteOffset(groupElement("target_display_primaries"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVColorPrimariesDesc target_display_primaries
     * }
     */
    public static final long target_display_primaries$offset() {
        return target_display_primaries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVColorPrimariesDesc target_display_primaries
     * }
     */
    public static MemorySegment target_display_primaries(MemorySegment struct) {
        return struct.asSlice(target_display_primaries$OFFSET, target_display_primaries$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVColorPrimariesDesc target_display_primaries
     * }
     */
    public static void target_display_primaries(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, target_display_primaries$OFFSET, target_display_primaries$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

