// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDOVIDmLevel4 {
 *     uint16_t anchor_pq;
 *     uint16_t anchor_power;
 * }
 * }
 */
public class AVDOVIDmLevel4 {

    AVDOVIDmLevel4() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_SHORT.withName("anchor_pq"),
        FFMPEG.C_SHORT.withName("anchor_power")
    ).withName("AVDOVIDmLevel4");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort anchor_pq$LAYOUT = (OfShort)$LAYOUT.select(groupElement("anchor_pq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t anchor_pq
     * }
     */
    public static final OfShort anchor_pq$layout() {
        return anchor_pq$LAYOUT;
    }

    private static final long anchor_pq$OFFSET = $LAYOUT.byteOffset(groupElement("anchor_pq"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t anchor_pq
     * }
     */
    public static final long anchor_pq$offset() {
        return anchor_pq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t anchor_pq
     * }
     */
    public static short anchor_pq(MemorySegment struct) {
        return struct.get(anchor_pq$LAYOUT, anchor_pq$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t anchor_pq
     * }
     */
    public static void anchor_pq(MemorySegment struct, short fieldValue) {
        struct.set(anchor_pq$LAYOUT, anchor_pq$OFFSET, fieldValue);
    }

    private static final OfShort anchor_power$LAYOUT = (OfShort)$LAYOUT.select(groupElement("anchor_power"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t anchor_power
     * }
     */
    public static final OfShort anchor_power$layout() {
        return anchor_power$LAYOUT;
    }

    private static final long anchor_power$OFFSET = $LAYOUT.byteOffset(groupElement("anchor_power"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t anchor_power
     * }
     */
    public static final long anchor_power$offset() {
        return anchor_power$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t anchor_power
     * }
     */
    public static short anchor_power(MemorySegment struct) {
        return struct.get(anchor_power$LAYOUT, anchor_power$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t anchor_power
     * }
     */
    public static void anchor_power(MemorySegment struct, short fieldValue) {
        struct.set(anchor_power$LAYOUT, anchor_power$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

