// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDOVIColorMetadata {
 *     uint8_t dm_metadata_id;
 *     uint8_t scene_refresh_flag;
 *     AVRational ycc_to_rgb_matrix[9];
 *     AVRational ycc_to_rgb_offset[3];
 *     AVRational rgb_to_lms_matrix[9];
 *     uint16_t signal_eotf;
 *     uint16_t signal_eotf_param0;
 *     uint16_t signal_eotf_param1;
 *     uint32_t signal_eotf_param2;
 *     uint8_t signal_bit_depth;
 *     uint8_t signal_color_space;
 *     uint8_t signal_chroma_format;
 *     uint8_t signal_full_range_flag;
 *     uint16_t source_min_pq;
 *     uint16_t source_max_pq;
 *     uint16_t source_diagonal;
 * }
 * }
 */
public class AVDOVIColorMetadata {

    AVDOVIColorMetadata() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_CHAR.withName("dm_metadata_id"),
        FFMPEG.C_CHAR.withName("scene_refresh_flag"),
        MemoryLayout.paddingLayout(2),
        MemoryLayout.sequenceLayout(9, AVRational.layout()).withName("ycc_to_rgb_matrix"),
        MemoryLayout.sequenceLayout(3, AVRational.layout()).withName("ycc_to_rgb_offset"),
        MemoryLayout.sequenceLayout(9, AVRational.layout()).withName("rgb_to_lms_matrix"),
        FFMPEG.C_SHORT.withName("signal_eotf"),
        FFMPEG.C_SHORT.withName("signal_eotf_param0"),
        FFMPEG.C_SHORT.withName("signal_eotf_param1"),
        MemoryLayout.paddingLayout(2),
        FFMPEG.C_INT.withName("signal_eotf_param2"),
        FFMPEG.C_CHAR.withName("signal_bit_depth"),
        FFMPEG.C_CHAR.withName("signal_color_space"),
        FFMPEG.C_CHAR.withName("signal_chroma_format"),
        FFMPEG.C_CHAR.withName("signal_full_range_flag"),
        FFMPEG.C_SHORT.withName("source_min_pq"),
        FFMPEG.C_SHORT.withName("source_max_pq"),
        FFMPEG.C_SHORT.withName("source_diagonal"),
        MemoryLayout.paddingLayout(2)
    ).withName("AVDOVIColorMetadata");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte dm_metadata_id$LAYOUT = (OfByte)$LAYOUT.select(groupElement("dm_metadata_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t dm_metadata_id
     * }
     */
    public static final OfByte dm_metadata_id$layout() {
        return dm_metadata_id$LAYOUT;
    }

    private static final long dm_metadata_id$OFFSET = $LAYOUT.byteOffset(groupElement("dm_metadata_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t dm_metadata_id
     * }
     */
    public static final long dm_metadata_id$offset() {
        return dm_metadata_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t dm_metadata_id
     * }
     */
    public static byte dm_metadata_id(MemorySegment struct) {
        return struct.get(dm_metadata_id$LAYOUT, dm_metadata_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t dm_metadata_id
     * }
     */
    public static void dm_metadata_id(MemorySegment struct, byte fieldValue) {
        struct.set(dm_metadata_id$LAYOUT, dm_metadata_id$OFFSET, fieldValue);
    }

    private static final OfByte scene_refresh_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("scene_refresh_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t scene_refresh_flag
     * }
     */
    public static final OfByte scene_refresh_flag$layout() {
        return scene_refresh_flag$LAYOUT;
    }

    private static final long scene_refresh_flag$OFFSET = $LAYOUT.byteOffset(groupElement("scene_refresh_flag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t scene_refresh_flag
     * }
     */
    public static final long scene_refresh_flag$offset() {
        return scene_refresh_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t scene_refresh_flag
     * }
     */
    public static byte scene_refresh_flag(MemorySegment struct) {
        return struct.get(scene_refresh_flag$LAYOUT, scene_refresh_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t scene_refresh_flag
     * }
     */
    public static void scene_refresh_flag(MemorySegment struct, byte fieldValue) {
        struct.set(scene_refresh_flag$LAYOUT, scene_refresh_flag$OFFSET, fieldValue);
    }

    private static final SequenceLayout ycc_to_rgb_matrix$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ycc_to_rgb_matrix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_matrix[9]
     * }
     */
    public static final SequenceLayout ycc_to_rgb_matrix$layout() {
        return ycc_to_rgb_matrix$LAYOUT;
    }

    private static final long ycc_to_rgb_matrix$OFFSET = $LAYOUT.byteOffset(groupElement("ycc_to_rgb_matrix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_matrix[9]
     * }
     */
    public static final long ycc_to_rgb_matrix$offset() {
        return ycc_to_rgb_matrix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_matrix[9]
     * }
     */
    public static MemorySegment ycc_to_rgb_matrix(MemorySegment struct) {
        return struct.asSlice(ycc_to_rgb_matrix$OFFSET, ycc_to_rgb_matrix$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_matrix[9]
     * }
     */
    public static void ycc_to_rgb_matrix(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ycc_to_rgb_matrix$OFFSET, ycc_to_rgb_matrix$LAYOUT.byteSize());
    }

    private static long[] ycc_to_rgb_matrix$DIMS = { 9 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_matrix[9]
     * }
     */
    public static long[] ycc_to_rgb_matrix$dimensions() {
        return ycc_to_rgb_matrix$DIMS;
    }
    private static final MethodHandle ycc_to_rgb_matrix$ELEM_HANDLE = ycc_to_rgb_matrix$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_matrix[9]
     * }
     */
    public static MemorySegment ycc_to_rgb_matrix(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)ycc_to_rgb_matrix$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_matrix[9]
     * }
     */
    public static void ycc_to_rgb_matrix(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, ycc_to_rgb_matrix(struct, index0), 0L, AVRational.layout().byteSize());
    }

    private static final SequenceLayout ycc_to_rgb_offset$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ycc_to_rgb_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_offset[3]
     * }
     */
    public static final SequenceLayout ycc_to_rgb_offset$layout() {
        return ycc_to_rgb_offset$LAYOUT;
    }

    private static final long ycc_to_rgb_offset$OFFSET = $LAYOUT.byteOffset(groupElement("ycc_to_rgb_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_offset[3]
     * }
     */
    public static final long ycc_to_rgb_offset$offset() {
        return ycc_to_rgb_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_offset[3]
     * }
     */
    public static MemorySegment ycc_to_rgb_offset(MemorySegment struct) {
        return struct.asSlice(ycc_to_rgb_offset$OFFSET, ycc_to_rgb_offset$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_offset[3]
     * }
     */
    public static void ycc_to_rgb_offset(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ycc_to_rgb_offset$OFFSET, ycc_to_rgb_offset$LAYOUT.byteSize());
    }

    private static long[] ycc_to_rgb_offset$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_offset[3]
     * }
     */
    public static long[] ycc_to_rgb_offset$dimensions() {
        return ycc_to_rgb_offset$DIMS;
    }
    private static final MethodHandle ycc_to_rgb_offset$ELEM_HANDLE = ycc_to_rgb_offset$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_offset[3]
     * }
     */
    public static MemorySegment ycc_to_rgb_offset(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)ycc_to_rgb_offset$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVRational ycc_to_rgb_offset[3]
     * }
     */
    public static void ycc_to_rgb_offset(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, ycc_to_rgb_offset(struct, index0), 0L, AVRational.layout().byteSize());
    }

    private static final SequenceLayout rgb_to_lms_matrix$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("rgb_to_lms_matrix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational rgb_to_lms_matrix[9]
     * }
     */
    public static final SequenceLayout rgb_to_lms_matrix$layout() {
        return rgb_to_lms_matrix$LAYOUT;
    }

    private static final long rgb_to_lms_matrix$OFFSET = $LAYOUT.byteOffset(groupElement("rgb_to_lms_matrix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational rgb_to_lms_matrix[9]
     * }
     */
    public static final long rgb_to_lms_matrix$offset() {
        return rgb_to_lms_matrix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational rgb_to_lms_matrix[9]
     * }
     */
    public static MemorySegment rgb_to_lms_matrix(MemorySegment struct) {
        return struct.asSlice(rgb_to_lms_matrix$OFFSET, rgb_to_lms_matrix$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational rgb_to_lms_matrix[9]
     * }
     */
    public static void rgb_to_lms_matrix(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, rgb_to_lms_matrix$OFFSET, rgb_to_lms_matrix$LAYOUT.byteSize());
    }

    private static long[] rgb_to_lms_matrix$DIMS = { 9 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVRational rgb_to_lms_matrix[9]
     * }
     */
    public static long[] rgb_to_lms_matrix$dimensions() {
        return rgb_to_lms_matrix$DIMS;
    }
    private static final MethodHandle rgb_to_lms_matrix$ELEM_HANDLE = rgb_to_lms_matrix$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVRational rgb_to_lms_matrix[9]
     * }
     */
    public static MemorySegment rgb_to_lms_matrix(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)rgb_to_lms_matrix$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVRational rgb_to_lms_matrix[9]
     * }
     */
    public static void rgb_to_lms_matrix(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, rgb_to_lms_matrix(struct, index0), 0L, AVRational.layout().byteSize());
    }

    private static final OfShort signal_eotf$LAYOUT = (OfShort)$LAYOUT.select(groupElement("signal_eotf"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf
     * }
     */
    public static final OfShort signal_eotf$layout() {
        return signal_eotf$LAYOUT;
    }

    private static final long signal_eotf$OFFSET = $LAYOUT.byteOffset(groupElement("signal_eotf"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf
     * }
     */
    public static final long signal_eotf$offset() {
        return signal_eotf$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf
     * }
     */
    public static short signal_eotf(MemorySegment struct) {
        return struct.get(signal_eotf$LAYOUT, signal_eotf$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf
     * }
     */
    public static void signal_eotf(MemorySegment struct, short fieldValue) {
        struct.set(signal_eotf$LAYOUT, signal_eotf$OFFSET, fieldValue);
    }

    private static final OfShort signal_eotf_param0$LAYOUT = (OfShort)$LAYOUT.select(groupElement("signal_eotf_param0"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf_param0
     * }
     */
    public static final OfShort signal_eotf_param0$layout() {
        return signal_eotf_param0$LAYOUT;
    }

    private static final long signal_eotf_param0$OFFSET = $LAYOUT.byteOffset(groupElement("signal_eotf_param0"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf_param0
     * }
     */
    public static final long signal_eotf_param0$offset() {
        return signal_eotf_param0$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf_param0
     * }
     */
    public static short signal_eotf_param0(MemorySegment struct) {
        return struct.get(signal_eotf_param0$LAYOUT, signal_eotf_param0$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf_param0
     * }
     */
    public static void signal_eotf_param0(MemorySegment struct, short fieldValue) {
        struct.set(signal_eotf_param0$LAYOUT, signal_eotf_param0$OFFSET, fieldValue);
    }

    private static final OfShort signal_eotf_param1$LAYOUT = (OfShort)$LAYOUT.select(groupElement("signal_eotf_param1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf_param1
     * }
     */
    public static final OfShort signal_eotf_param1$layout() {
        return signal_eotf_param1$LAYOUT;
    }

    private static final long signal_eotf_param1$OFFSET = $LAYOUT.byteOffset(groupElement("signal_eotf_param1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf_param1
     * }
     */
    public static final long signal_eotf_param1$offset() {
        return signal_eotf_param1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf_param1
     * }
     */
    public static short signal_eotf_param1(MemorySegment struct) {
        return struct.get(signal_eotf_param1$LAYOUT, signal_eotf_param1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t signal_eotf_param1
     * }
     */
    public static void signal_eotf_param1(MemorySegment struct, short fieldValue) {
        struct.set(signal_eotf_param1$LAYOUT, signal_eotf_param1$OFFSET, fieldValue);
    }

    private static final OfInt signal_eotf_param2$LAYOUT = (OfInt)$LAYOUT.select(groupElement("signal_eotf_param2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t signal_eotf_param2
     * }
     */
    public static final OfInt signal_eotf_param2$layout() {
        return signal_eotf_param2$LAYOUT;
    }

    private static final long signal_eotf_param2$OFFSET = $LAYOUT.byteOffset(groupElement("signal_eotf_param2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t signal_eotf_param2
     * }
     */
    public static final long signal_eotf_param2$offset() {
        return signal_eotf_param2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t signal_eotf_param2
     * }
     */
    public static int signal_eotf_param2(MemorySegment struct) {
        return struct.get(signal_eotf_param2$LAYOUT, signal_eotf_param2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t signal_eotf_param2
     * }
     */
    public static void signal_eotf_param2(MemorySegment struct, int fieldValue) {
        struct.set(signal_eotf_param2$LAYOUT, signal_eotf_param2$OFFSET, fieldValue);
    }

    private static final OfByte signal_bit_depth$LAYOUT = (OfByte)$LAYOUT.select(groupElement("signal_bit_depth"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t signal_bit_depth
     * }
     */
    public static final OfByte signal_bit_depth$layout() {
        return signal_bit_depth$LAYOUT;
    }

    private static final long signal_bit_depth$OFFSET = $LAYOUT.byteOffset(groupElement("signal_bit_depth"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t signal_bit_depth
     * }
     */
    public static final long signal_bit_depth$offset() {
        return signal_bit_depth$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t signal_bit_depth
     * }
     */
    public static byte signal_bit_depth(MemorySegment struct) {
        return struct.get(signal_bit_depth$LAYOUT, signal_bit_depth$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t signal_bit_depth
     * }
     */
    public static void signal_bit_depth(MemorySegment struct, byte fieldValue) {
        struct.set(signal_bit_depth$LAYOUT, signal_bit_depth$OFFSET, fieldValue);
    }

    private static final OfByte signal_color_space$LAYOUT = (OfByte)$LAYOUT.select(groupElement("signal_color_space"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t signal_color_space
     * }
     */
    public static final OfByte signal_color_space$layout() {
        return signal_color_space$LAYOUT;
    }

    private static final long signal_color_space$OFFSET = $LAYOUT.byteOffset(groupElement("signal_color_space"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t signal_color_space
     * }
     */
    public static final long signal_color_space$offset() {
        return signal_color_space$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t signal_color_space
     * }
     */
    public static byte signal_color_space(MemorySegment struct) {
        return struct.get(signal_color_space$LAYOUT, signal_color_space$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t signal_color_space
     * }
     */
    public static void signal_color_space(MemorySegment struct, byte fieldValue) {
        struct.set(signal_color_space$LAYOUT, signal_color_space$OFFSET, fieldValue);
    }

    private static final OfByte signal_chroma_format$LAYOUT = (OfByte)$LAYOUT.select(groupElement("signal_chroma_format"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t signal_chroma_format
     * }
     */
    public static final OfByte signal_chroma_format$layout() {
        return signal_chroma_format$LAYOUT;
    }

    private static final long signal_chroma_format$OFFSET = $LAYOUT.byteOffset(groupElement("signal_chroma_format"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t signal_chroma_format
     * }
     */
    public static final long signal_chroma_format$offset() {
        return signal_chroma_format$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t signal_chroma_format
     * }
     */
    public static byte signal_chroma_format(MemorySegment struct) {
        return struct.get(signal_chroma_format$LAYOUT, signal_chroma_format$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t signal_chroma_format
     * }
     */
    public static void signal_chroma_format(MemorySegment struct, byte fieldValue) {
        struct.set(signal_chroma_format$LAYOUT, signal_chroma_format$OFFSET, fieldValue);
    }

    private static final OfByte signal_full_range_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("signal_full_range_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t signal_full_range_flag
     * }
     */
    public static final OfByte signal_full_range_flag$layout() {
        return signal_full_range_flag$LAYOUT;
    }

    private static final long signal_full_range_flag$OFFSET = $LAYOUT.byteOffset(groupElement("signal_full_range_flag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t signal_full_range_flag
     * }
     */
    public static final long signal_full_range_flag$offset() {
        return signal_full_range_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t signal_full_range_flag
     * }
     */
    public static byte signal_full_range_flag(MemorySegment struct) {
        return struct.get(signal_full_range_flag$LAYOUT, signal_full_range_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t signal_full_range_flag
     * }
     */
    public static void signal_full_range_flag(MemorySegment struct, byte fieldValue) {
        struct.set(signal_full_range_flag$LAYOUT, signal_full_range_flag$OFFSET, fieldValue);
    }

    private static final OfShort source_min_pq$LAYOUT = (OfShort)$LAYOUT.select(groupElement("source_min_pq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t source_min_pq
     * }
     */
    public static final OfShort source_min_pq$layout() {
        return source_min_pq$LAYOUT;
    }

    private static final long source_min_pq$OFFSET = $LAYOUT.byteOffset(groupElement("source_min_pq"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t source_min_pq
     * }
     */
    public static final long source_min_pq$offset() {
        return source_min_pq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t source_min_pq
     * }
     */
    public static short source_min_pq(MemorySegment struct) {
        return struct.get(source_min_pq$LAYOUT, source_min_pq$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t source_min_pq
     * }
     */
    public static void source_min_pq(MemorySegment struct, short fieldValue) {
        struct.set(source_min_pq$LAYOUT, source_min_pq$OFFSET, fieldValue);
    }

    private static final OfShort source_max_pq$LAYOUT = (OfShort)$LAYOUT.select(groupElement("source_max_pq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t source_max_pq
     * }
     */
    public static final OfShort source_max_pq$layout() {
        return source_max_pq$LAYOUT;
    }

    private static final long source_max_pq$OFFSET = $LAYOUT.byteOffset(groupElement("source_max_pq"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t source_max_pq
     * }
     */
    public static final long source_max_pq$offset() {
        return source_max_pq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t source_max_pq
     * }
     */
    public static short source_max_pq(MemorySegment struct) {
        return struct.get(source_max_pq$LAYOUT, source_max_pq$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t source_max_pq
     * }
     */
    public static void source_max_pq(MemorySegment struct, short fieldValue) {
        struct.set(source_max_pq$LAYOUT, source_max_pq$OFFSET, fieldValue);
    }

    private static final OfShort source_diagonal$LAYOUT = (OfShort)$LAYOUT.select(groupElement("source_diagonal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t source_diagonal
     * }
     */
    public static final OfShort source_diagonal$layout() {
        return source_diagonal$LAYOUT;
    }

    private static final long source_diagonal$OFFSET = $LAYOUT.byteOffset(groupElement("source_diagonal"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t source_diagonal
     * }
     */
    public static final long source_diagonal$offset() {
        return source_diagonal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t source_diagonal
     * }
     */
    public static short source_diagonal(MemorySegment struct) {
        return struct.get(source_diagonal$LAYOUT, source_diagonal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t source_diagonal
     * }
     */
    public static void source_diagonal(MemorySegment struct, short fieldValue) {
        struct.set(source_diagonal$LAYOUT, source_diagonal$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

