// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDOVIDmLevel255 {
 *     uint8_t dm_run_mode;
 *     uint8_t dm_run_version;
 *     uint8_t dm_debug[4];
 * }
 * }
 */
public class AVDOVIDmLevel255 {

    AVDOVIDmLevel255() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_CHAR.withName("dm_run_mode"),
        FFMPEG.C_CHAR.withName("dm_run_version"),
        MemoryLayout.sequenceLayout(4, FFMPEG.C_CHAR).withName("dm_debug")
    ).withName("AVDOVIDmLevel255");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte dm_run_mode$LAYOUT = (OfByte)$LAYOUT.select(groupElement("dm_run_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t dm_run_mode
     * }
     */
    public static final OfByte dm_run_mode$layout() {
        return dm_run_mode$LAYOUT;
    }

    private static final long dm_run_mode$OFFSET = $LAYOUT.byteOffset(groupElement("dm_run_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t dm_run_mode
     * }
     */
    public static final long dm_run_mode$offset() {
        return dm_run_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t dm_run_mode
     * }
     */
    public static byte dm_run_mode(MemorySegment struct) {
        return struct.get(dm_run_mode$LAYOUT, dm_run_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t dm_run_mode
     * }
     */
    public static void dm_run_mode(MemorySegment struct, byte fieldValue) {
        struct.set(dm_run_mode$LAYOUT, dm_run_mode$OFFSET, fieldValue);
    }

    private static final OfByte dm_run_version$LAYOUT = (OfByte)$LAYOUT.select(groupElement("dm_run_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t dm_run_version
     * }
     */
    public static final OfByte dm_run_version$layout() {
        return dm_run_version$LAYOUT;
    }

    private static final long dm_run_version$OFFSET = $LAYOUT.byteOffset(groupElement("dm_run_version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t dm_run_version
     * }
     */
    public static final long dm_run_version$offset() {
        return dm_run_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t dm_run_version
     * }
     */
    public static byte dm_run_version(MemorySegment struct) {
        return struct.get(dm_run_version$LAYOUT, dm_run_version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t dm_run_version
     * }
     */
    public static void dm_run_version(MemorySegment struct, byte fieldValue) {
        struct.set(dm_run_version$LAYOUT, dm_run_version$OFFSET, fieldValue);
    }

    private static final SequenceLayout dm_debug$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("dm_debug"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t dm_debug[4]
     * }
     */
    public static final SequenceLayout dm_debug$layout() {
        return dm_debug$LAYOUT;
    }

    private static final long dm_debug$OFFSET = $LAYOUT.byteOffset(groupElement("dm_debug"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t dm_debug[4]
     * }
     */
    public static final long dm_debug$offset() {
        return dm_debug$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t dm_debug[4]
     * }
     */
    public static MemorySegment dm_debug(MemorySegment struct) {
        return struct.asSlice(dm_debug$OFFSET, dm_debug$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t dm_debug[4]
     * }
     */
    public static void dm_debug(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, dm_debug$OFFSET, dm_debug$LAYOUT.byteSize());
    }

    private static long[] dm_debug$DIMS = { 4 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t dm_debug[4]
     * }
     */
    public static long[] dm_debug$dimensions() {
        return dm_debug$DIMS;
    }
    private static final VarHandle dm_debug$ELEM_HANDLE = dm_debug$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t dm_debug[4]
     * }
     */
    public static byte dm_debug(MemorySegment struct, long index0) {
        return (byte)dm_debug$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t dm_debug[4]
     * }
     */
    public static void dm_debug(MemorySegment struct, long index0, byte fieldValue) {
        dm_debug$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

