// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDOVIDmLevel254 {
 *     uint8_t dm_mode;
 *     uint8_t dm_version_index;
 * }
 * }
 */
public class AVDOVIDmLevel254 {

    AVDOVIDmLevel254() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_CHAR.withName("dm_mode"),
        FFMPEG.C_CHAR.withName("dm_version_index")
    ).withName("AVDOVIDmLevel254");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte dm_mode$LAYOUT = (OfByte)$LAYOUT.select(groupElement("dm_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t dm_mode
     * }
     */
    public static final OfByte dm_mode$layout() {
        return dm_mode$LAYOUT;
    }

    private static final long dm_mode$OFFSET = $LAYOUT.byteOffset(groupElement("dm_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t dm_mode
     * }
     */
    public static final long dm_mode$offset() {
        return dm_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t dm_mode
     * }
     */
    public static byte dm_mode(MemorySegment struct) {
        return struct.get(dm_mode$LAYOUT, dm_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t dm_mode
     * }
     */
    public static void dm_mode(MemorySegment struct, byte fieldValue) {
        struct.set(dm_mode$LAYOUT, dm_mode$OFFSET, fieldValue);
    }

    private static final OfByte dm_version_index$LAYOUT = (OfByte)$LAYOUT.select(groupElement("dm_version_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t dm_version_index
     * }
     */
    public static final OfByte dm_version_index$layout() {
        return dm_version_index$LAYOUT;
    }

    private static final long dm_version_index$OFFSET = $LAYOUT.byteOffset(groupElement("dm_version_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t dm_version_index
     * }
     */
    public static final long dm_version_index$offset() {
        return dm_version_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t dm_version_index
     * }
     */
    public static byte dm_version_index(MemorySegment struct) {
        return struct.get(dm_version_index$LAYOUT, dm_version_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t dm_version_index
     * }
     */
    public static void dm_version_index(MemorySegment struct, byte fieldValue) {
        struct.set(dm_version_index$LAYOUT, dm_version_index$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

