// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDOVIDmLevel5 {
 *     uint16_t left_offset;
 *     uint16_t right_offset;
 *     uint16_t top_offset;
 *     uint16_t bottom_offset;
 * }
 * }
 */
public class AVDOVIDmLevel5 {

    AVDOVIDmLevel5() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_SHORT.withName("left_offset"),
        FFMPEG.C_SHORT.withName("right_offset"),
        FFMPEG.C_SHORT.withName("top_offset"),
        FFMPEG.C_SHORT.withName("bottom_offset")
    ).withName("AVDOVIDmLevel5");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort left_offset$LAYOUT = (OfShort)$LAYOUT.select(groupElement("left_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t left_offset
     * }
     */
    public static final OfShort left_offset$layout() {
        return left_offset$LAYOUT;
    }

    private static final long left_offset$OFFSET = $LAYOUT.byteOffset(groupElement("left_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t left_offset
     * }
     */
    public static final long left_offset$offset() {
        return left_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t left_offset
     * }
     */
    public static short left_offset(MemorySegment struct) {
        return struct.get(left_offset$LAYOUT, left_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t left_offset
     * }
     */
    public static void left_offset(MemorySegment struct, short fieldValue) {
        struct.set(left_offset$LAYOUT, left_offset$OFFSET, fieldValue);
    }

    private static final OfShort right_offset$LAYOUT = (OfShort)$LAYOUT.select(groupElement("right_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t right_offset
     * }
     */
    public static final OfShort right_offset$layout() {
        return right_offset$LAYOUT;
    }

    private static final long right_offset$OFFSET = $LAYOUT.byteOffset(groupElement("right_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t right_offset
     * }
     */
    public static final long right_offset$offset() {
        return right_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t right_offset
     * }
     */
    public static short right_offset(MemorySegment struct) {
        return struct.get(right_offset$LAYOUT, right_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t right_offset
     * }
     */
    public static void right_offset(MemorySegment struct, short fieldValue) {
        struct.set(right_offset$LAYOUT, right_offset$OFFSET, fieldValue);
    }

    private static final OfShort top_offset$LAYOUT = (OfShort)$LAYOUT.select(groupElement("top_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t top_offset
     * }
     */
    public static final OfShort top_offset$layout() {
        return top_offset$LAYOUT;
    }

    private static final long top_offset$OFFSET = $LAYOUT.byteOffset(groupElement("top_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t top_offset
     * }
     */
    public static final long top_offset$offset() {
        return top_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t top_offset
     * }
     */
    public static short top_offset(MemorySegment struct) {
        return struct.get(top_offset$LAYOUT, top_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t top_offset
     * }
     */
    public static void top_offset(MemorySegment struct, short fieldValue) {
        struct.set(top_offset$LAYOUT, top_offset$OFFSET, fieldValue);
    }

    private static final OfShort bottom_offset$LAYOUT = (OfShort)$LAYOUT.select(groupElement("bottom_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t bottom_offset
     * }
     */
    public static final OfShort bottom_offset$layout() {
        return bottom_offset$LAYOUT;
    }

    private static final long bottom_offset$OFFSET = $LAYOUT.byteOffset(groupElement("bottom_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t bottom_offset
     * }
     */
    public static final long bottom_offset$offset() {
        return bottom_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t bottom_offset
     * }
     */
    public static short bottom_offset(MemorySegment struct) {
        return struct.get(bottom_offset$LAYOUT, bottom_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t bottom_offset
     * }
     */
    public static void bottom_offset(MemorySegment struct, short fieldValue) {
        struct.set(bottom_offset$LAYOUT, bottom_offset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

