// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDVProfile {
 *     int dsf;
 *     int video_stype;
 *     int frame_size;
 *     int difseg_size;
 *     int n_difchan;
 *     AVRational time_base;
 *     int ltc_divisor;
 *     int height;
 *     int width;
 *     AVRational sar[2];
 *     enum AVPixelFormat pix_fmt;
 *     int bpm;
 *     const uint8_t *block_sizes;
 *     int audio_stride;
 *     int audio_min_samples[3];
 *     int audio_samples_dist[5];
 *     const uint8_t (*audio_shuffle)[9];
 * }
 * }
 */
public class AVDVProfile {

    AVDVProfile() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_INT.withName("dsf"),
        FFMPEG.C_INT.withName("video_stype"),
        FFMPEG.C_INT.withName("frame_size"),
        FFMPEG.C_INT.withName("difseg_size"),
        FFMPEG.C_INT.withName("n_difchan"),
        AVRational.layout().withName("time_base"),
        FFMPEG.C_INT.withName("ltc_divisor"),
        FFMPEG.C_INT.withName("height"),
        FFMPEG.C_INT.withName("width"),
        MemoryLayout.sequenceLayout(2, AVRational.layout()).withName("sar"),
        FFMPEG.C_INT.withName("pix_fmt"),
        FFMPEG.C_INT.withName("bpm"),
        FFMPEG.C_POINTER.withName("block_sizes"),
        FFMPEG.C_INT.withName("audio_stride"),
        MemoryLayout.sequenceLayout(3, FFMPEG.C_INT).withName("audio_min_samples"),
        MemoryLayout.sequenceLayout(5, FFMPEG.C_INT).withName("audio_samples_dist"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("audio_shuffle")
    ).withName("AVDVProfile");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt dsf$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dsf"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int dsf
     * }
     */
    public static final OfInt dsf$layout() {
        return dsf$LAYOUT;
    }

    private static final long dsf$OFFSET = $LAYOUT.byteOffset(groupElement("dsf"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int dsf
     * }
     */
    public static final long dsf$offset() {
        return dsf$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int dsf
     * }
     */
    public static int dsf(MemorySegment struct) {
        return struct.get(dsf$LAYOUT, dsf$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int dsf
     * }
     */
    public static void dsf(MemorySegment struct, int fieldValue) {
        struct.set(dsf$LAYOUT, dsf$OFFSET, fieldValue);
    }

    private static final OfInt video_stype$LAYOUT = (OfInt)$LAYOUT.select(groupElement("video_stype"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int video_stype
     * }
     */
    public static final OfInt video_stype$layout() {
        return video_stype$LAYOUT;
    }

    private static final long video_stype$OFFSET = $LAYOUT.byteOffset(groupElement("video_stype"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int video_stype
     * }
     */
    public static final long video_stype$offset() {
        return video_stype$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int video_stype
     * }
     */
    public static int video_stype(MemorySegment struct) {
        return struct.get(video_stype$LAYOUT, video_stype$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int video_stype
     * }
     */
    public static void video_stype(MemorySegment struct, int fieldValue) {
        struct.set(video_stype$LAYOUT, video_stype$OFFSET, fieldValue);
    }

    private static final OfInt frame_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("frame_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int frame_size
     * }
     */
    public static final OfInt frame_size$layout() {
        return frame_size$LAYOUT;
    }

    private static final long frame_size$OFFSET = $LAYOUT.byteOffset(groupElement("frame_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int frame_size
     * }
     */
    public static final long frame_size$offset() {
        return frame_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int frame_size
     * }
     */
    public static int frame_size(MemorySegment struct) {
        return struct.get(frame_size$LAYOUT, frame_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int frame_size
     * }
     */
    public static void frame_size(MemorySegment struct, int fieldValue) {
        struct.set(frame_size$LAYOUT, frame_size$OFFSET, fieldValue);
    }

    private static final OfInt difseg_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("difseg_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int difseg_size
     * }
     */
    public static final OfInt difseg_size$layout() {
        return difseg_size$LAYOUT;
    }

    private static final long difseg_size$OFFSET = $LAYOUT.byteOffset(groupElement("difseg_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int difseg_size
     * }
     */
    public static final long difseg_size$offset() {
        return difseg_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int difseg_size
     * }
     */
    public static int difseg_size(MemorySegment struct) {
        return struct.get(difseg_size$LAYOUT, difseg_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int difseg_size
     * }
     */
    public static void difseg_size(MemorySegment struct, int fieldValue) {
        struct.set(difseg_size$LAYOUT, difseg_size$OFFSET, fieldValue);
    }

    private static final OfInt n_difchan$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_difchan"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int n_difchan
     * }
     */
    public static final OfInt n_difchan$layout() {
        return n_difchan$LAYOUT;
    }

    private static final long n_difchan$OFFSET = $LAYOUT.byteOffset(groupElement("n_difchan"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int n_difchan
     * }
     */
    public static final long n_difchan$offset() {
        return n_difchan$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int n_difchan
     * }
     */
    public static int n_difchan(MemorySegment struct) {
        return struct.get(n_difchan$LAYOUT, n_difchan$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int n_difchan
     * }
     */
    public static void n_difchan(MemorySegment struct, int fieldValue) {
        struct.set(n_difchan$LAYOUT, n_difchan$OFFSET, fieldValue);
    }

    private static final GroupLayout time_base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("time_base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational time_base
     * }
     */
    public static final GroupLayout time_base$layout() {
        return time_base$LAYOUT;
    }

    private static final long time_base$OFFSET = $LAYOUT.byteOffset(groupElement("time_base"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational time_base
     * }
     */
    public static final long time_base$offset() {
        return time_base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational time_base
     * }
     */
    public static MemorySegment time_base(MemorySegment struct) {
        return struct.asSlice(time_base$OFFSET, time_base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational time_base
     * }
     */
    public static void time_base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, time_base$OFFSET, time_base$LAYOUT.byteSize());
    }

    private static final OfInt ltc_divisor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ltc_divisor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int ltc_divisor
     * }
     */
    public static final OfInt ltc_divisor$layout() {
        return ltc_divisor$LAYOUT;
    }

    private static final long ltc_divisor$OFFSET = $LAYOUT.byteOffset(groupElement("ltc_divisor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int ltc_divisor
     * }
     */
    public static final long ltc_divisor$offset() {
        return ltc_divisor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int ltc_divisor
     * }
     */
    public static int ltc_divisor(MemorySegment struct) {
        return struct.get(ltc_divisor$LAYOUT, ltc_divisor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int ltc_divisor
     * }
     */
    public static void ltc_divisor(MemorySegment struct, int fieldValue) {
        struct.set(ltc_divisor$LAYOUT, ltc_divisor$OFFSET, fieldValue);
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final SequenceLayout sar$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("sar"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational sar[2]
     * }
     */
    public static final SequenceLayout sar$layout() {
        return sar$LAYOUT;
    }

    private static final long sar$OFFSET = $LAYOUT.byteOffset(groupElement("sar"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational sar[2]
     * }
     */
    public static final long sar$offset() {
        return sar$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational sar[2]
     * }
     */
    public static MemorySegment sar(MemorySegment struct) {
        return struct.asSlice(sar$OFFSET, sar$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational sar[2]
     * }
     */
    public static void sar(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sar$OFFSET, sar$LAYOUT.byteSize());
    }

    private static long[] sar$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVRational sar[2]
     * }
     */
    public static long[] sar$dimensions() {
        return sar$DIMS;
    }
    private static final MethodHandle sar$ELEM_HANDLE = sar$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVRational sar[2]
     * }
     */
    public static MemorySegment sar(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)sar$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVRational sar[2]
     * }
     */
    public static void sar(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, sar(struct, index0), 0L, AVRational.layout().byteSize());
    }

    private static final OfInt pix_fmt$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pix_fmt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVPixelFormat pix_fmt
     * }
     */
    public static final OfInt pix_fmt$layout() {
        return pix_fmt$LAYOUT;
    }

    private static final long pix_fmt$OFFSET = $LAYOUT.byteOffset(groupElement("pix_fmt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVPixelFormat pix_fmt
     * }
     */
    public static final long pix_fmt$offset() {
        return pix_fmt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVPixelFormat pix_fmt
     * }
     */
    public static int pix_fmt(MemorySegment struct) {
        return struct.get(pix_fmt$LAYOUT, pix_fmt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVPixelFormat pix_fmt
     * }
     */
    public static void pix_fmt(MemorySegment struct, int fieldValue) {
        struct.set(pix_fmt$LAYOUT, pix_fmt$OFFSET, fieldValue);
    }

    private static final OfInt bpm$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bpm"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int bpm
     * }
     */
    public static final OfInt bpm$layout() {
        return bpm$LAYOUT;
    }

    private static final long bpm$OFFSET = $LAYOUT.byteOffset(groupElement("bpm"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int bpm
     * }
     */
    public static final long bpm$offset() {
        return bpm$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int bpm
     * }
     */
    public static int bpm(MemorySegment struct) {
        return struct.get(bpm$LAYOUT, bpm$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int bpm
     * }
     */
    public static void bpm(MemorySegment struct, int fieldValue) {
        struct.set(bpm$LAYOUT, bpm$OFFSET, fieldValue);
    }

    private static final AddressLayout block_sizes$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("block_sizes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t *block_sizes
     * }
     */
    public static final AddressLayout block_sizes$layout() {
        return block_sizes$LAYOUT;
    }

    private static final long block_sizes$OFFSET = $LAYOUT.byteOffset(groupElement("block_sizes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t *block_sizes
     * }
     */
    public static final long block_sizes$offset() {
        return block_sizes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t *block_sizes
     * }
     */
    public static MemorySegment block_sizes(MemorySegment struct) {
        return struct.get(block_sizes$LAYOUT, block_sizes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t *block_sizes
     * }
     */
    public static void block_sizes(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(block_sizes$LAYOUT, block_sizes$OFFSET, fieldValue);
    }

    private static final OfInt audio_stride$LAYOUT = (OfInt)$LAYOUT.select(groupElement("audio_stride"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int audio_stride
     * }
     */
    public static final OfInt audio_stride$layout() {
        return audio_stride$LAYOUT;
    }

    private static final long audio_stride$OFFSET = $LAYOUT.byteOffset(groupElement("audio_stride"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int audio_stride
     * }
     */
    public static final long audio_stride$offset() {
        return audio_stride$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int audio_stride
     * }
     */
    public static int audio_stride(MemorySegment struct) {
        return struct.get(audio_stride$LAYOUT, audio_stride$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int audio_stride
     * }
     */
    public static void audio_stride(MemorySegment struct, int fieldValue) {
        struct.set(audio_stride$LAYOUT, audio_stride$OFFSET, fieldValue);
    }

    private static final SequenceLayout audio_min_samples$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("audio_min_samples"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int audio_min_samples[3]
     * }
     */
    public static final SequenceLayout audio_min_samples$layout() {
        return audio_min_samples$LAYOUT;
    }

    private static final long audio_min_samples$OFFSET = $LAYOUT.byteOffset(groupElement("audio_min_samples"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int audio_min_samples[3]
     * }
     */
    public static final long audio_min_samples$offset() {
        return audio_min_samples$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int audio_min_samples[3]
     * }
     */
    public static MemorySegment audio_min_samples(MemorySegment struct) {
        return struct.asSlice(audio_min_samples$OFFSET, audio_min_samples$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int audio_min_samples[3]
     * }
     */
    public static void audio_min_samples(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, audio_min_samples$OFFSET, audio_min_samples$LAYOUT.byteSize());
    }

    private static long[] audio_min_samples$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int audio_min_samples[3]
     * }
     */
    public static long[] audio_min_samples$dimensions() {
        return audio_min_samples$DIMS;
    }
    private static final VarHandle audio_min_samples$ELEM_HANDLE = audio_min_samples$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int audio_min_samples[3]
     * }
     */
    public static int audio_min_samples(MemorySegment struct, long index0) {
        return (int)audio_min_samples$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int audio_min_samples[3]
     * }
     */
    public static void audio_min_samples(MemorySegment struct, long index0, int fieldValue) {
        audio_min_samples$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout audio_samples_dist$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("audio_samples_dist"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int audio_samples_dist[5]
     * }
     */
    public static final SequenceLayout audio_samples_dist$layout() {
        return audio_samples_dist$LAYOUT;
    }

    private static final long audio_samples_dist$OFFSET = $LAYOUT.byteOffset(groupElement("audio_samples_dist"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int audio_samples_dist[5]
     * }
     */
    public static final long audio_samples_dist$offset() {
        return audio_samples_dist$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int audio_samples_dist[5]
     * }
     */
    public static MemorySegment audio_samples_dist(MemorySegment struct) {
        return struct.asSlice(audio_samples_dist$OFFSET, audio_samples_dist$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int audio_samples_dist[5]
     * }
     */
    public static void audio_samples_dist(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, audio_samples_dist$OFFSET, audio_samples_dist$LAYOUT.byteSize());
    }

    private static long[] audio_samples_dist$DIMS = { 5 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int audio_samples_dist[5]
     * }
     */
    public static long[] audio_samples_dist$dimensions() {
        return audio_samples_dist$DIMS;
    }
    private static final VarHandle audio_samples_dist$ELEM_HANDLE = audio_samples_dist$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int audio_samples_dist[5]
     * }
     */
    public static int audio_samples_dist(MemorySegment struct, long index0) {
        return (int)audio_samples_dist$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int audio_samples_dist[5]
     * }
     */
    public static void audio_samples_dist(MemorySegment struct, long index0, int fieldValue) {
        audio_samples_dist$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final AddressLayout audio_shuffle$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("audio_shuffle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint8_t (*audio_shuffle)[9]
     * }
     */
    public static final AddressLayout audio_shuffle$layout() {
        return audio_shuffle$LAYOUT;
    }

    private static final long audio_shuffle$OFFSET = $LAYOUT.byteOffset(groupElement("audio_shuffle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint8_t (*audio_shuffle)[9]
     * }
     */
    public static final long audio_shuffle$offset() {
        return audio_shuffle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint8_t (*audio_shuffle)[9]
     * }
     */
    public static MemorySegment audio_shuffle(MemorySegment struct) {
        return struct.get(audio_shuffle$LAYOUT, audio_shuffle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint8_t (*audio_shuffle)[9]
     * }
     */
    public static void audio_shuffle(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(audio_shuffle$LAYOUT, audio_shuffle$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

