// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDynamicHDRVivid {
 *     uint8_t system_start_code;
 *     uint8_t num_windows;
 *     AVHDRVividColorTransformParams params[3];
 * }
 * }
 */
public class AVDynamicHDRVivid {

    AVDynamicHDRVivid() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_CHAR.withName("system_start_code"),
        FFMPEG.C_CHAR.withName("num_windows"),
        MemoryLayout.paddingLayout(2),
        MemoryLayout.sequenceLayout(3, AVHDRVividColorTransformParams.layout()).withName("params")
    ).withName("AVDynamicHDRVivid");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte system_start_code$LAYOUT = (OfByte)$LAYOUT.select(groupElement("system_start_code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t system_start_code
     * }
     */
    public static final OfByte system_start_code$layout() {
        return system_start_code$LAYOUT;
    }

    private static final long system_start_code$OFFSET = $LAYOUT.byteOffset(groupElement("system_start_code"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t system_start_code
     * }
     */
    public static final long system_start_code$offset() {
        return system_start_code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t system_start_code
     * }
     */
    public static byte system_start_code(MemorySegment struct) {
        return struct.get(system_start_code$LAYOUT, system_start_code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t system_start_code
     * }
     */
    public static void system_start_code(MemorySegment struct, byte fieldValue) {
        struct.set(system_start_code$LAYOUT, system_start_code$OFFSET, fieldValue);
    }

    private static final OfByte num_windows$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_windows"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t num_windows
     * }
     */
    public static final OfByte num_windows$layout() {
        return num_windows$LAYOUT;
    }

    private static final long num_windows$OFFSET = $LAYOUT.byteOffset(groupElement("num_windows"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t num_windows
     * }
     */
    public static final long num_windows$offset() {
        return num_windows$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t num_windows
     * }
     */
    public static byte num_windows(MemorySegment struct) {
        return struct.get(num_windows$LAYOUT, num_windows$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t num_windows
     * }
     */
    public static void num_windows(MemorySegment struct, byte fieldValue) {
        struct.set(num_windows$LAYOUT, num_windows$OFFSET, fieldValue);
    }

    private static final SequenceLayout params$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("params"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVHDRVividColorTransformParams params[3]
     * }
     */
    public static final SequenceLayout params$layout() {
        return params$LAYOUT;
    }

    private static final long params$OFFSET = $LAYOUT.byteOffset(groupElement("params"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVHDRVividColorTransformParams params[3]
     * }
     */
    public static final long params$offset() {
        return params$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVHDRVividColorTransformParams params[3]
     * }
     */
    public static MemorySegment params(MemorySegment struct) {
        return struct.asSlice(params$OFFSET, params$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVHDRVividColorTransformParams params[3]
     * }
     */
    public static void params(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, params$OFFSET, params$LAYOUT.byteSize());
    }

    private static long[] params$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVHDRVividColorTransformParams params[3]
     * }
     */
    public static long[] params$dimensions() {
        return params$DIMS;
    }
    private static final MethodHandle params$ELEM_HANDLE = params$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVHDRVividColorTransformParams params[3]
     * }
     */
    public static MemorySegment params(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)params$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVHDRVividColorTransformParams params[3]
     * }
     */
    public static void params(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, params(struct, index0), 0L, AVHDRVividColorTransformParams.layout().byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

