// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVDynamicHDRPlus {
 *     uint8_t itu_t_t35_country_code;
 *     uint8_t application_version;
 *     uint8_t num_windows;
 *     AVHDRPlusColorTransformParams params[3];
 *     AVRational targeted_system_display_maximum_luminance;
 *     uint8_t targeted_system_display_actual_peak_luminance_flag;
 *     uint8_t num_rows_targeted_system_display_actual_peak_luminance;
 *     uint8_t num_cols_targeted_system_display_actual_peak_luminance;
 *     AVRational targeted_system_display_actual_peak_luminance[25][25];
 *     uint8_t mastering_display_actual_peak_luminance_flag;
 *     uint8_t num_rows_mastering_display_actual_peak_luminance;
 *     uint8_t num_cols_mastering_display_actual_peak_luminance;
 *     AVRational mastering_display_actual_peak_luminance[25][25];
 * }
 * }
 */
public class AVDynamicHDRPlus {

    AVDynamicHDRPlus() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_CHAR.withName("itu_t_t35_country_code"),
        FFMPEG.C_CHAR.withName("application_version"),
        FFMPEG.C_CHAR.withName("num_windows"),
        MemoryLayout.paddingLayout(1),
        MemoryLayout.sequenceLayout(3, AVHDRPlusColorTransformParams.layout()).withName("params"),
        AVRational.layout().withName("targeted_system_display_maximum_luminance"),
        FFMPEG.C_CHAR.withName("targeted_system_display_actual_peak_luminance_flag"),
        FFMPEG.C_CHAR.withName("num_rows_targeted_system_display_actual_peak_luminance"),
        FFMPEG.C_CHAR.withName("num_cols_targeted_system_display_actual_peak_luminance"),
        MemoryLayout.paddingLayout(1),
        MemoryLayout.sequenceLayout(25, MemoryLayout.sequenceLayout(25, AVRational.layout())).withName("targeted_system_display_actual_peak_luminance"),
        FFMPEG.C_CHAR.withName("mastering_display_actual_peak_luminance_flag"),
        FFMPEG.C_CHAR.withName("num_rows_mastering_display_actual_peak_luminance"),
        FFMPEG.C_CHAR.withName("num_cols_mastering_display_actual_peak_luminance"),
        MemoryLayout.paddingLayout(1),
        MemoryLayout.sequenceLayout(25, MemoryLayout.sequenceLayout(25, AVRational.layout())).withName("mastering_display_actual_peak_luminance")
    ).withName("AVDynamicHDRPlus");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte itu_t_t35_country_code$LAYOUT = (OfByte)$LAYOUT.select(groupElement("itu_t_t35_country_code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t itu_t_t35_country_code
     * }
     */
    public static final OfByte itu_t_t35_country_code$layout() {
        return itu_t_t35_country_code$LAYOUT;
    }

    private static final long itu_t_t35_country_code$OFFSET = $LAYOUT.byteOffset(groupElement("itu_t_t35_country_code"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t itu_t_t35_country_code
     * }
     */
    public static final long itu_t_t35_country_code$offset() {
        return itu_t_t35_country_code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t itu_t_t35_country_code
     * }
     */
    public static byte itu_t_t35_country_code(MemorySegment struct) {
        return struct.get(itu_t_t35_country_code$LAYOUT, itu_t_t35_country_code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t itu_t_t35_country_code
     * }
     */
    public static void itu_t_t35_country_code(MemorySegment struct, byte fieldValue) {
        struct.set(itu_t_t35_country_code$LAYOUT, itu_t_t35_country_code$OFFSET, fieldValue);
    }

    private static final OfByte application_version$LAYOUT = (OfByte)$LAYOUT.select(groupElement("application_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t application_version
     * }
     */
    public static final OfByte application_version$layout() {
        return application_version$LAYOUT;
    }

    private static final long application_version$OFFSET = $LAYOUT.byteOffset(groupElement("application_version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t application_version
     * }
     */
    public static final long application_version$offset() {
        return application_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t application_version
     * }
     */
    public static byte application_version(MemorySegment struct) {
        return struct.get(application_version$LAYOUT, application_version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t application_version
     * }
     */
    public static void application_version(MemorySegment struct, byte fieldValue) {
        struct.set(application_version$LAYOUT, application_version$OFFSET, fieldValue);
    }

    private static final OfByte num_windows$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_windows"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t num_windows
     * }
     */
    public static final OfByte num_windows$layout() {
        return num_windows$LAYOUT;
    }

    private static final long num_windows$OFFSET = $LAYOUT.byteOffset(groupElement("num_windows"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t num_windows
     * }
     */
    public static final long num_windows$offset() {
        return num_windows$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t num_windows
     * }
     */
    public static byte num_windows(MemorySegment struct) {
        return struct.get(num_windows$LAYOUT, num_windows$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t num_windows
     * }
     */
    public static void num_windows(MemorySegment struct, byte fieldValue) {
        struct.set(num_windows$LAYOUT, num_windows$OFFSET, fieldValue);
    }

    private static final SequenceLayout params$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("params"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVHDRPlusColorTransformParams params[3]
     * }
     */
    public static final SequenceLayout params$layout() {
        return params$LAYOUT;
    }

    private static final long params$OFFSET = $LAYOUT.byteOffset(groupElement("params"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVHDRPlusColorTransformParams params[3]
     * }
     */
    public static final long params$offset() {
        return params$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVHDRPlusColorTransformParams params[3]
     * }
     */
    public static MemorySegment params(MemorySegment struct) {
        return struct.asSlice(params$OFFSET, params$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVHDRPlusColorTransformParams params[3]
     * }
     */
    public static void params(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, params$OFFSET, params$LAYOUT.byteSize());
    }

    private static long[] params$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVHDRPlusColorTransformParams params[3]
     * }
     */
    public static long[] params$dimensions() {
        return params$DIMS;
    }
    private static final MethodHandle params$ELEM_HANDLE = params$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVHDRPlusColorTransformParams params[3]
     * }
     */
    public static MemorySegment params(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)params$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVHDRPlusColorTransformParams params[3]
     * }
     */
    public static void params(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, params(struct, index0), 0L, AVHDRPlusColorTransformParams.layout().byteSize());
    }

    private static final GroupLayout targeted_system_display_maximum_luminance$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("targeted_system_display_maximum_luminance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_maximum_luminance
     * }
     */
    public static final GroupLayout targeted_system_display_maximum_luminance$layout() {
        return targeted_system_display_maximum_luminance$LAYOUT;
    }

    private static final long targeted_system_display_maximum_luminance$OFFSET = $LAYOUT.byteOffset(groupElement("targeted_system_display_maximum_luminance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_maximum_luminance
     * }
     */
    public static final long targeted_system_display_maximum_luminance$offset() {
        return targeted_system_display_maximum_luminance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_maximum_luminance
     * }
     */
    public static MemorySegment targeted_system_display_maximum_luminance(MemorySegment struct) {
        return struct.asSlice(targeted_system_display_maximum_luminance$OFFSET, targeted_system_display_maximum_luminance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_maximum_luminance
     * }
     */
    public static void targeted_system_display_maximum_luminance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, targeted_system_display_maximum_luminance$OFFSET, targeted_system_display_maximum_luminance$LAYOUT.byteSize());
    }

    private static final OfByte targeted_system_display_actual_peak_luminance_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("targeted_system_display_actual_peak_luminance_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t targeted_system_display_actual_peak_luminance_flag
     * }
     */
    public static final OfByte targeted_system_display_actual_peak_luminance_flag$layout() {
        return targeted_system_display_actual_peak_luminance_flag$LAYOUT;
    }

    private static final long targeted_system_display_actual_peak_luminance_flag$OFFSET = $LAYOUT.byteOffset(groupElement("targeted_system_display_actual_peak_luminance_flag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t targeted_system_display_actual_peak_luminance_flag
     * }
     */
    public static final long targeted_system_display_actual_peak_luminance_flag$offset() {
        return targeted_system_display_actual_peak_luminance_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t targeted_system_display_actual_peak_luminance_flag
     * }
     */
    public static byte targeted_system_display_actual_peak_luminance_flag(MemorySegment struct) {
        return struct.get(targeted_system_display_actual_peak_luminance_flag$LAYOUT, targeted_system_display_actual_peak_luminance_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t targeted_system_display_actual_peak_luminance_flag
     * }
     */
    public static void targeted_system_display_actual_peak_luminance_flag(MemorySegment struct, byte fieldValue) {
        struct.set(targeted_system_display_actual_peak_luminance_flag$LAYOUT, targeted_system_display_actual_peak_luminance_flag$OFFSET, fieldValue);
    }

    private static final OfByte num_rows_targeted_system_display_actual_peak_luminance$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_rows_targeted_system_display_actual_peak_luminance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t num_rows_targeted_system_display_actual_peak_luminance
     * }
     */
    public static final OfByte num_rows_targeted_system_display_actual_peak_luminance$layout() {
        return num_rows_targeted_system_display_actual_peak_luminance$LAYOUT;
    }

    private static final long num_rows_targeted_system_display_actual_peak_luminance$OFFSET = $LAYOUT.byteOffset(groupElement("num_rows_targeted_system_display_actual_peak_luminance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t num_rows_targeted_system_display_actual_peak_luminance
     * }
     */
    public static final long num_rows_targeted_system_display_actual_peak_luminance$offset() {
        return num_rows_targeted_system_display_actual_peak_luminance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t num_rows_targeted_system_display_actual_peak_luminance
     * }
     */
    public static byte num_rows_targeted_system_display_actual_peak_luminance(MemorySegment struct) {
        return struct.get(num_rows_targeted_system_display_actual_peak_luminance$LAYOUT, num_rows_targeted_system_display_actual_peak_luminance$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t num_rows_targeted_system_display_actual_peak_luminance
     * }
     */
    public static void num_rows_targeted_system_display_actual_peak_luminance(MemorySegment struct, byte fieldValue) {
        struct.set(num_rows_targeted_system_display_actual_peak_luminance$LAYOUT, num_rows_targeted_system_display_actual_peak_luminance$OFFSET, fieldValue);
    }

    private static final OfByte num_cols_targeted_system_display_actual_peak_luminance$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_cols_targeted_system_display_actual_peak_luminance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t num_cols_targeted_system_display_actual_peak_luminance
     * }
     */
    public static final OfByte num_cols_targeted_system_display_actual_peak_luminance$layout() {
        return num_cols_targeted_system_display_actual_peak_luminance$LAYOUT;
    }

    private static final long num_cols_targeted_system_display_actual_peak_luminance$OFFSET = $LAYOUT.byteOffset(groupElement("num_cols_targeted_system_display_actual_peak_luminance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t num_cols_targeted_system_display_actual_peak_luminance
     * }
     */
    public static final long num_cols_targeted_system_display_actual_peak_luminance$offset() {
        return num_cols_targeted_system_display_actual_peak_luminance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t num_cols_targeted_system_display_actual_peak_luminance
     * }
     */
    public static byte num_cols_targeted_system_display_actual_peak_luminance(MemorySegment struct) {
        return struct.get(num_cols_targeted_system_display_actual_peak_luminance$LAYOUT, num_cols_targeted_system_display_actual_peak_luminance$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t num_cols_targeted_system_display_actual_peak_luminance
     * }
     */
    public static void num_cols_targeted_system_display_actual_peak_luminance(MemorySegment struct, byte fieldValue) {
        struct.set(num_cols_targeted_system_display_actual_peak_luminance$LAYOUT, num_cols_targeted_system_display_actual_peak_luminance$OFFSET, fieldValue);
    }

    private static final SequenceLayout targeted_system_display_actual_peak_luminance$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("targeted_system_display_actual_peak_luminance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_actual_peak_luminance[25][25]
     * }
     */
    public static final SequenceLayout targeted_system_display_actual_peak_luminance$layout() {
        return targeted_system_display_actual_peak_luminance$LAYOUT;
    }

    private static final long targeted_system_display_actual_peak_luminance$OFFSET = $LAYOUT.byteOffset(groupElement("targeted_system_display_actual_peak_luminance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_actual_peak_luminance[25][25]
     * }
     */
    public static final long targeted_system_display_actual_peak_luminance$offset() {
        return targeted_system_display_actual_peak_luminance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_actual_peak_luminance[25][25]
     * }
     */
    public static MemorySegment targeted_system_display_actual_peak_luminance(MemorySegment struct) {
        return struct.asSlice(targeted_system_display_actual_peak_luminance$OFFSET, targeted_system_display_actual_peak_luminance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_actual_peak_luminance[25][25]
     * }
     */
    public static void targeted_system_display_actual_peak_luminance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, targeted_system_display_actual_peak_luminance$OFFSET, targeted_system_display_actual_peak_luminance$LAYOUT.byteSize());
    }

    private static long[] targeted_system_display_actual_peak_luminance$DIMS = { 25, 25 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_actual_peak_luminance[25][25]
     * }
     */
    public static long[] targeted_system_display_actual_peak_luminance$dimensions() {
        return targeted_system_display_actual_peak_luminance$DIMS;
    }
    private static final MethodHandle targeted_system_display_actual_peak_luminance$ELEM_HANDLE = targeted_system_display_actual_peak_luminance$LAYOUT.sliceHandle(sequenceElement(), sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_actual_peak_luminance[25][25]
     * }
     */
    public static MemorySegment targeted_system_display_actual_peak_luminance(MemorySegment struct, long index0, long index1) {
        try {
            return (MemorySegment)targeted_system_display_actual_peak_luminance$ELEM_HANDLE.invokeExact(struct, 0L, index0, index1);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVRational targeted_system_display_actual_peak_luminance[25][25]
     * }
     */
    public static void targeted_system_display_actual_peak_luminance(MemorySegment struct, long index0, long index1, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, targeted_system_display_actual_peak_luminance(struct, index0, index1), 0L, AVRational.layout().byteSize());
    }

    private static final OfByte mastering_display_actual_peak_luminance_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("mastering_display_actual_peak_luminance_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t mastering_display_actual_peak_luminance_flag
     * }
     */
    public static final OfByte mastering_display_actual_peak_luminance_flag$layout() {
        return mastering_display_actual_peak_luminance_flag$LAYOUT;
    }

    private static final long mastering_display_actual_peak_luminance_flag$OFFSET = $LAYOUT.byteOffset(groupElement("mastering_display_actual_peak_luminance_flag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t mastering_display_actual_peak_luminance_flag
     * }
     */
    public static final long mastering_display_actual_peak_luminance_flag$offset() {
        return mastering_display_actual_peak_luminance_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t mastering_display_actual_peak_luminance_flag
     * }
     */
    public static byte mastering_display_actual_peak_luminance_flag(MemorySegment struct) {
        return struct.get(mastering_display_actual_peak_luminance_flag$LAYOUT, mastering_display_actual_peak_luminance_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t mastering_display_actual_peak_luminance_flag
     * }
     */
    public static void mastering_display_actual_peak_luminance_flag(MemorySegment struct, byte fieldValue) {
        struct.set(mastering_display_actual_peak_luminance_flag$LAYOUT, mastering_display_actual_peak_luminance_flag$OFFSET, fieldValue);
    }

    private static final OfByte num_rows_mastering_display_actual_peak_luminance$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_rows_mastering_display_actual_peak_luminance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t num_rows_mastering_display_actual_peak_luminance
     * }
     */
    public static final OfByte num_rows_mastering_display_actual_peak_luminance$layout() {
        return num_rows_mastering_display_actual_peak_luminance$LAYOUT;
    }

    private static final long num_rows_mastering_display_actual_peak_luminance$OFFSET = $LAYOUT.byteOffset(groupElement("num_rows_mastering_display_actual_peak_luminance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t num_rows_mastering_display_actual_peak_luminance
     * }
     */
    public static final long num_rows_mastering_display_actual_peak_luminance$offset() {
        return num_rows_mastering_display_actual_peak_luminance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t num_rows_mastering_display_actual_peak_luminance
     * }
     */
    public static byte num_rows_mastering_display_actual_peak_luminance(MemorySegment struct) {
        return struct.get(num_rows_mastering_display_actual_peak_luminance$LAYOUT, num_rows_mastering_display_actual_peak_luminance$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t num_rows_mastering_display_actual_peak_luminance
     * }
     */
    public static void num_rows_mastering_display_actual_peak_luminance(MemorySegment struct, byte fieldValue) {
        struct.set(num_rows_mastering_display_actual_peak_luminance$LAYOUT, num_rows_mastering_display_actual_peak_luminance$OFFSET, fieldValue);
    }

    private static final OfByte num_cols_mastering_display_actual_peak_luminance$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_cols_mastering_display_actual_peak_luminance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t num_cols_mastering_display_actual_peak_luminance
     * }
     */
    public static final OfByte num_cols_mastering_display_actual_peak_luminance$layout() {
        return num_cols_mastering_display_actual_peak_luminance$LAYOUT;
    }

    private static final long num_cols_mastering_display_actual_peak_luminance$OFFSET = $LAYOUT.byteOffset(groupElement("num_cols_mastering_display_actual_peak_luminance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t num_cols_mastering_display_actual_peak_luminance
     * }
     */
    public static final long num_cols_mastering_display_actual_peak_luminance$offset() {
        return num_cols_mastering_display_actual_peak_luminance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t num_cols_mastering_display_actual_peak_luminance
     * }
     */
    public static byte num_cols_mastering_display_actual_peak_luminance(MemorySegment struct) {
        return struct.get(num_cols_mastering_display_actual_peak_luminance$LAYOUT, num_cols_mastering_display_actual_peak_luminance$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t num_cols_mastering_display_actual_peak_luminance
     * }
     */
    public static void num_cols_mastering_display_actual_peak_luminance(MemorySegment struct, byte fieldValue) {
        struct.set(num_cols_mastering_display_actual_peak_luminance$LAYOUT, num_cols_mastering_display_actual_peak_luminance$OFFSET, fieldValue);
    }

    private static final SequenceLayout mastering_display_actual_peak_luminance$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("mastering_display_actual_peak_luminance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational mastering_display_actual_peak_luminance[25][25]
     * }
     */
    public static final SequenceLayout mastering_display_actual_peak_luminance$layout() {
        return mastering_display_actual_peak_luminance$LAYOUT;
    }

    private static final long mastering_display_actual_peak_luminance$OFFSET = $LAYOUT.byteOffset(groupElement("mastering_display_actual_peak_luminance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational mastering_display_actual_peak_luminance[25][25]
     * }
     */
    public static final long mastering_display_actual_peak_luminance$offset() {
        return mastering_display_actual_peak_luminance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational mastering_display_actual_peak_luminance[25][25]
     * }
     */
    public static MemorySegment mastering_display_actual_peak_luminance(MemorySegment struct) {
        return struct.asSlice(mastering_display_actual_peak_luminance$OFFSET, mastering_display_actual_peak_luminance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational mastering_display_actual_peak_luminance[25][25]
     * }
     */
    public static void mastering_display_actual_peak_luminance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, mastering_display_actual_peak_luminance$OFFSET, mastering_display_actual_peak_luminance$LAYOUT.byteSize());
    }

    private static long[] mastering_display_actual_peak_luminance$DIMS = { 25, 25 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVRational mastering_display_actual_peak_luminance[25][25]
     * }
     */
    public static long[] mastering_display_actual_peak_luminance$dimensions() {
        return mastering_display_actual_peak_luminance$DIMS;
    }
    private static final MethodHandle mastering_display_actual_peak_luminance$ELEM_HANDLE = mastering_display_actual_peak_luminance$LAYOUT.sliceHandle(sequenceElement(), sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVRational mastering_display_actual_peak_luminance[25][25]
     * }
     */
    public static MemorySegment mastering_display_actual_peak_luminance(MemorySegment struct, long index0, long index1) {
        try {
            return (MemorySegment)mastering_display_actual_peak_luminance$ELEM_HANDLE.invokeExact(struct, 0L, index0, index1);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVRational mastering_display_actual_peak_luminance[25][25]
     * }
     */
    public static void mastering_display_actual_peak_luminance(MemorySegment struct, long index0, long index1, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, mastering_display_actual_peak_luminance(struct, index0, index1), 0L, AVRational.layout().byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

