// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVExifEntry {
 *     uint16_t id;
 *     enum AVTiffDataType type;
 *     uint32_t count;
 *     uint32_t ifd_offset;
 *     uint8_t *ifd_lead;
 *     union {
 *         void *ptr;
 *         int64_t *sint;
 *         uint64_t *uint;
 *         double *dbl;
 *         char *str;
 *         uint8_t *ubytes;
 *         int8_t *sbytes;
 *         AVRational *rat;
 *         AVExifMetadata ifd;
 *     } value;
 * }
 * }
 */
public class AVExifEntry {

    AVExifEntry() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_SHORT.withName("id"),
        MemoryLayout.paddingLayout(2),
        FFMPEG.C_INT.withName("type"),
        FFMPEG.C_INT.withName("count"),
        FFMPEG.C_INT.withName("ifd_offset"),
        FFMPEG.C_POINTER.withName("ifd_lead"),
        AVExifEntry.union.layout().withName("value")
    ).withName("AVExifEntry");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort id$LAYOUT = (OfShort)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t id
     * }
     */
    public static final OfShort id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t id
     * }
     */
    public static short id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t id
     * }
     */
    public static void id(MemorySegment struct, short fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVTiffDataType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVTiffDataType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVTiffDataType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVTiffDataType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfInt count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t count
     * }
     */
    public static final OfInt count$layout() {
        return count$LAYOUT;
    }

    private static final long count$OFFSET = $LAYOUT.byteOffset(groupElement("count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t count
     * }
     */
    public static final long count$offset() {
        return count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t count
     * }
     */
    public static int count(MemorySegment struct) {
        return struct.get(count$LAYOUT, count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t count
     * }
     */
    public static void count(MemorySegment struct, int fieldValue) {
        struct.set(count$LAYOUT, count$OFFSET, fieldValue);
    }

    private static final OfInt ifd_offset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ifd_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ifd_offset
     * }
     */
    public static final OfInt ifd_offset$layout() {
        return ifd_offset$LAYOUT;
    }

    private static final long ifd_offset$OFFSET = $LAYOUT.byteOffset(groupElement("ifd_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ifd_offset
     * }
     */
    public static final long ifd_offset$offset() {
        return ifd_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ifd_offset
     * }
     */
    public static int ifd_offset(MemorySegment struct) {
        return struct.get(ifd_offset$LAYOUT, ifd_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ifd_offset
     * }
     */
    public static void ifd_offset(MemorySegment struct, int fieldValue) {
        struct.set(ifd_offset$LAYOUT, ifd_offset$OFFSET, fieldValue);
    }

    private static final AddressLayout ifd_lead$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ifd_lead"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t *ifd_lead
     * }
     */
    public static final AddressLayout ifd_lead$layout() {
        return ifd_lead$LAYOUT;
    }

    private static final long ifd_lead$OFFSET = $LAYOUT.byteOffset(groupElement("ifd_lead"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t *ifd_lead
     * }
     */
    public static final long ifd_lead$offset() {
        return ifd_lead$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t *ifd_lead
     * }
     */
    public static MemorySegment ifd_lead(MemorySegment struct) {
        return struct.get(ifd_lead$LAYOUT, ifd_lead$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t *ifd_lead
     * }
     */
    public static void ifd_lead(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ifd_lead$LAYOUT, ifd_lead$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     void *ptr;
     *     int64_t *sint;
     *     uint64_t *uint;
     *     double *dbl;
     *     char *str;
     *     uint8_t *ubytes;
     *     int8_t *sbytes;
     *     AVRational *rat;
     *     AVExifMetadata ifd;
     * }
     * }
     */
    public static class union {

        union() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            FFMPEG.C_POINTER.withName("ptr"),
            FFMPEG.C_POINTER.withName("sint"),
            FFMPEG.C_POINTER.withName("uint"),
            FFMPEG.C_POINTER.withName("dbl"),
            FFMPEG.C_POINTER.withName("str"),
            FFMPEG.C_POINTER.withName("ubytes"),
            FFMPEG.C_POINTER.withName("sbytes"),
            FFMPEG.C_POINTER.withName("rat"),
            AVExifMetadata.layout().withName("ifd")
        ).withName("union");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final AddressLayout ptr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ptr"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * void *ptr
         * }
         */
        public static final AddressLayout ptr$layout() {
            return ptr$LAYOUT;
        }

        private static final long ptr$OFFSET = $LAYOUT.byteOffset(groupElement("ptr"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * void *ptr
         * }
         */
        public static final long ptr$offset() {
            return ptr$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * void *ptr
         * }
         */
        public static MemorySegment ptr(MemorySegment union) {
            return union.get(ptr$LAYOUT, ptr$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * void *ptr
         * }
         */
        public static void ptr(MemorySegment union, MemorySegment fieldValue) {
            union.set(ptr$LAYOUT, ptr$OFFSET, fieldValue);
        }

        private static final AddressLayout sint$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sint"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * int64_t *sint
         * }
         */
        public static final AddressLayout sint$layout() {
            return sint$LAYOUT;
        }

        private static final long sint$OFFSET = $LAYOUT.byteOffset(groupElement("sint"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * int64_t *sint
         * }
         */
        public static final long sint$offset() {
            return sint$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * int64_t *sint
         * }
         */
        public static MemorySegment sint(MemorySegment union) {
            return union.get(sint$LAYOUT, sint$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * int64_t *sint
         * }
         */
        public static void sint(MemorySegment union, MemorySegment fieldValue) {
            union.set(sint$LAYOUT, sint$OFFSET, fieldValue);
        }

        private static final AddressLayout uint$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("uint"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * uint64_t *uint
         * }
         */
        public static final AddressLayout uint$layout() {
            return uint$LAYOUT;
        }

        private static final long uint$OFFSET = $LAYOUT.byteOffset(groupElement("uint"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * uint64_t *uint
         * }
         */
        public static final long uint$offset() {
            return uint$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * uint64_t *uint
         * }
         */
        public static MemorySegment uint(MemorySegment union) {
            return union.get(uint$LAYOUT, uint$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * uint64_t *uint
         * }
         */
        public static void uint(MemorySegment union, MemorySegment fieldValue) {
            union.set(uint$LAYOUT, uint$OFFSET, fieldValue);
        }

        private static final AddressLayout dbl$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("dbl"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * double *dbl
         * }
         */
        public static final AddressLayout dbl$layout() {
            return dbl$LAYOUT;
        }

        private static final long dbl$OFFSET = $LAYOUT.byteOffset(groupElement("dbl"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * double *dbl
         * }
         */
        public static final long dbl$offset() {
            return dbl$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * double *dbl
         * }
         */
        public static MemorySegment dbl(MemorySegment union) {
            return union.get(dbl$LAYOUT, dbl$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * double *dbl
         * }
         */
        public static void dbl(MemorySegment union, MemorySegment fieldValue) {
            union.set(dbl$LAYOUT, dbl$OFFSET, fieldValue);
        }

        private static final AddressLayout str$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("str"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * char *str
         * }
         */
        public static final AddressLayout str$layout() {
            return str$LAYOUT;
        }

        private static final long str$OFFSET = $LAYOUT.byteOffset(groupElement("str"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * char *str
         * }
         */
        public static final long str$offset() {
            return str$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * char *str
         * }
         */
        public static MemorySegment str(MemorySegment union) {
            return union.get(str$LAYOUT, str$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * char *str
         * }
         */
        public static void str(MemorySegment union, MemorySegment fieldValue) {
            union.set(str$LAYOUT, str$OFFSET, fieldValue);
        }

        private static final AddressLayout ubytes$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ubytes"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * uint8_t *ubytes
         * }
         */
        public static final AddressLayout ubytes$layout() {
            return ubytes$LAYOUT;
        }

        private static final long ubytes$OFFSET = $LAYOUT.byteOffset(groupElement("ubytes"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * uint8_t *ubytes
         * }
         */
        public static final long ubytes$offset() {
            return ubytes$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * uint8_t *ubytes
         * }
         */
        public static MemorySegment ubytes(MemorySegment union) {
            return union.get(ubytes$LAYOUT, ubytes$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * uint8_t *ubytes
         * }
         */
        public static void ubytes(MemorySegment union, MemorySegment fieldValue) {
            union.set(ubytes$LAYOUT, ubytes$OFFSET, fieldValue);
        }

        private static final AddressLayout sbytes$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("sbytes"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * int8_t *sbytes
         * }
         */
        public static final AddressLayout sbytes$layout() {
            return sbytes$LAYOUT;
        }

        private static final long sbytes$OFFSET = $LAYOUT.byteOffset(groupElement("sbytes"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * int8_t *sbytes
         * }
         */
        public static final long sbytes$offset() {
            return sbytes$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * int8_t *sbytes
         * }
         */
        public static MemorySegment sbytes(MemorySegment union) {
            return union.get(sbytes$LAYOUT, sbytes$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * int8_t *sbytes
         * }
         */
        public static void sbytes(MemorySegment union, MemorySegment fieldValue) {
            union.set(sbytes$LAYOUT, sbytes$OFFSET, fieldValue);
        }

        private static final AddressLayout rat$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("rat"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * AVRational *rat
         * }
         */
        public static final AddressLayout rat$layout() {
            return rat$LAYOUT;
        }

        private static final long rat$OFFSET = $LAYOUT.byteOffset(groupElement("rat"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * AVRational *rat
         * }
         */
        public static final long rat$offset() {
            return rat$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * AVRational *rat
         * }
         */
        public static MemorySegment rat(MemorySegment union) {
            return union.get(rat$LAYOUT, rat$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * AVRational *rat
         * }
         */
        public static void rat(MemorySegment union, MemorySegment fieldValue) {
            union.set(rat$LAYOUT, rat$OFFSET, fieldValue);
        }

        private static final GroupLayout ifd$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ifd"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * AVExifMetadata ifd
         * }
         */
        public static final GroupLayout ifd$layout() {
            return ifd$LAYOUT;
        }

        private static final long ifd$OFFSET = $LAYOUT.byteOffset(groupElement("ifd"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * AVExifMetadata ifd
         * }
         */
        public static final long ifd$offset() {
            return ifd$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * AVExifMetadata ifd
         * }
         */
        public static MemorySegment ifd(MemorySegment union) {
            return union.asSlice(ifd$OFFSET, ifd$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * AVExifMetadata ifd
         * }
         */
        public static void ifd(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, ifd$OFFSET, ifd$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     void *ptr;
     *     int64_t *sint;
     *     uint64_t *uint;
     *     double *dbl;
     *     char *str;
     *     uint8_t *ubytes;
     *     int8_t *sbytes;
     *     AVRational *rat;
     *     AVExifMetadata ifd;
     * } value
     * }
     */
    public static final GroupLayout value$layout() {
        return value$LAYOUT;
    }

    private static final long value$OFFSET = $LAYOUT.byteOffset(groupElement("value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     void *ptr;
     *     int64_t *sint;
     *     uint64_t *uint;
     *     double *dbl;
     *     char *str;
     *     uint8_t *ubytes;
     *     int8_t *sbytes;
     *     AVRational *rat;
     *     AVExifMetadata ifd;
     * } value
     * }
     */
    public static final long value$offset() {
        return value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     void *ptr;
     *     int64_t *sint;
     *     uint64_t *uint;
     *     double *dbl;
     *     char *str;
     *     uint8_t *ubytes;
     *     int8_t *sbytes;
     *     AVRational *rat;
     *     AVExifMetadata ifd;
     * } value
     * }
     */
    public static MemorySegment value(MemorySegment struct) {
        return struct.asSlice(value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     void *ptr;
     *     int64_t *sint;
     *     uint64_t *uint;
     *     double *dbl;
     *     char *str;
     *     uint8_t *ubytes;
     *     int8_t *sbytes;
     *     AVRational *rat;
     *     AVExifMetadata ifd;
     * } value
     * }
     */
    public static void value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, value$OFFSET, value$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

