// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVFilmGrainParams {
 *     enum AVFilmGrainParamsType type;
 *     uint64_t seed;
 *     int width;
 *     int height;
 *     int subsampling_x;
 *     int subsampling_y;
 *     enum AVColorRange color_range;
 *     enum AVColorPrimaries color_primaries;
 *     enum AVColorTransferCharacteristic color_trc;
 *     enum AVColorSpace color_space;
 *     int bit_depth_luma;
 *     int bit_depth_chroma;
 *     union {
 *         AVFilmGrainAOMParams aom;
 *         AVFilmGrainH274Params h274;
 *     } codec;
 * }
 * }
 */
public class AVFilmGrainParams {

    AVFilmGrainParams() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_LONG.withName("seed"),
        FFMPEG.C_INT.withName("width"),
        FFMPEG.C_INT.withName("height"),
        FFMPEG.C_INT.withName("subsampling_x"),
        FFMPEG.C_INT.withName("subsampling_y"),
        FFMPEG.C_INT.withName("color_range"),
        FFMPEG.C_INT.withName("color_primaries"),
        FFMPEG.C_INT.withName("color_trc"),
        FFMPEG.C_INT.withName("color_space"),
        FFMPEG.C_INT.withName("bit_depth_luma"),
        FFMPEG.C_INT.withName("bit_depth_chroma"),
        AVFilmGrainParams.union.layout().withName("codec"),
        MemoryLayout.paddingLayout(4)
    ).withName("AVFilmGrainParams");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVFilmGrainParamsType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVFilmGrainParamsType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVFilmGrainParamsType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVFilmGrainParamsType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfLong seed$LAYOUT = (OfLong)$LAYOUT.select(groupElement("seed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t seed
     * }
     */
    public static final OfLong seed$layout() {
        return seed$LAYOUT;
    }

    private static final long seed$OFFSET = $LAYOUT.byteOffset(groupElement("seed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t seed
     * }
     */
    public static final long seed$offset() {
        return seed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t seed
     * }
     */
    public static long seed(MemorySegment struct) {
        return struct.get(seed$LAYOUT, seed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t seed
     * }
     */
    public static void seed(MemorySegment struct, long fieldValue) {
        struct.set(seed$LAYOUT, seed$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfInt subsampling_x$LAYOUT = (OfInt)$LAYOUT.select(groupElement("subsampling_x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int subsampling_x
     * }
     */
    public static final OfInt subsampling_x$layout() {
        return subsampling_x$LAYOUT;
    }

    private static final long subsampling_x$OFFSET = $LAYOUT.byteOffset(groupElement("subsampling_x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int subsampling_x
     * }
     */
    public static final long subsampling_x$offset() {
        return subsampling_x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int subsampling_x
     * }
     */
    public static int subsampling_x(MemorySegment struct) {
        return struct.get(subsampling_x$LAYOUT, subsampling_x$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int subsampling_x
     * }
     */
    public static void subsampling_x(MemorySegment struct, int fieldValue) {
        struct.set(subsampling_x$LAYOUT, subsampling_x$OFFSET, fieldValue);
    }

    private static final OfInt subsampling_y$LAYOUT = (OfInt)$LAYOUT.select(groupElement("subsampling_y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int subsampling_y
     * }
     */
    public static final OfInt subsampling_y$layout() {
        return subsampling_y$LAYOUT;
    }

    private static final long subsampling_y$OFFSET = $LAYOUT.byteOffset(groupElement("subsampling_y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int subsampling_y
     * }
     */
    public static final long subsampling_y$offset() {
        return subsampling_y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int subsampling_y
     * }
     */
    public static int subsampling_y(MemorySegment struct) {
        return struct.get(subsampling_y$LAYOUT, subsampling_y$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int subsampling_y
     * }
     */
    public static void subsampling_y(MemorySegment struct, int fieldValue) {
        struct.set(subsampling_y$LAYOUT, subsampling_y$OFFSET, fieldValue);
    }

    private static final OfInt color_range$LAYOUT = (OfInt)$LAYOUT.select(groupElement("color_range"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVColorRange color_range
     * }
     */
    public static final OfInt color_range$layout() {
        return color_range$LAYOUT;
    }

    private static final long color_range$OFFSET = $LAYOUT.byteOffset(groupElement("color_range"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVColorRange color_range
     * }
     */
    public static final long color_range$offset() {
        return color_range$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVColorRange color_range
     * }
     */
    public static int color_range(MemorySegment struct) {
        return struct.get(color_range$LAYOUT, color_range$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVColorRange color_range
     * }
     */
    public static void color_range(MemorySegment struct, int fieldValue) {
        struct.set(color_range$LAYOUT, color_range$OFFSET, fieldValue);
    }

    private static final OfInt color_primaries$LAYOUT = (OfInt)$LAYOUT.select(groupElement("color_primaries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVColorPrimaries color_primaries
     * }
     */
    public static final OfInt color_primaries$layout() {
        return color_primaries$LAYOUT;
    }

    private static final long color_primaries$OFFSET = $LAYOUT.byteOffset(groupElement("color_primaries"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVColorPrimaries color_primaries
     * }
     */
    public static final long color_primaries$offset() {
        return color_primaries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVColorPrimaries color_primaries
     * }
     */
    public static int color_primaries(MemorySegment struct) {
        return struct.get(color_primaries$LAYOUT, color_primaries$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVColorPrimaries color_primaries
     * }
     */
    public static void color_primaries(MemorySegment struct, int fieldValue) {
        struct.set(color_primaries$LAYOUT, color_primaries$OFFSET, fieldValue);
    }

    private static final OfInt color_trc$LAYOUT = (OfInt)$LAYOUT.select(groupElement("color_trc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVColorTransferCharacteristic color_trc
     * }
     */
    public static final OfInt color_trc$layout() {
        return color_trc$LAYOUT;
    }

    private static final long color_trc$OFFSET = $LAYOUT.byteOffset(groupElement("color_trc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVColorTransferCharacteristic color_trc
     * }
     */
    public static final long color_trc$offset() {
        return color_trc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVColorTransferCharacteristic color_trc
     * }
     */
    public static int color_trc(MemorySegment struct) {
        return struct.get(color_trc$LAYOUT, color_trc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVColorTransferCharacteristic color_trc
     * }
     */
    public static void color_trc(MemorySegment struct, int fieldValue) {
        struct.set(color_trc$LAYOUT, color_trc$OFFSET, fieldValue);
    }

    private static final OfInt color_space$LAYOUT = (OfInt)$LAYOUT.select(groupElement("color_space"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVColorSpace color_space
     * }
     */
    public static final OfInt color_space$layout() {
        return color_space$LAYOUT;
    }

    private static final long color_space$OFFSET = $LAYOUT.byteOffset(groupElement("color_space"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVColorSpace color_space
     * }
     */
    public static final long color_space$offset() {
        return color_space$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVColorSpace color_space
     * }
     */
    public static int color_space(MemorySegment struct) {
        return struct.get(color_space$LAYOUT, color_space$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVColorSpace color_space
     * }
     */
    public static void color_space(MemorySegment struct, int fieldValue) {
        struct.set(color_space$LAYOUT, color_space$OFFSET, fieldValue);
    }

    private static final OfInt bit_depth_luma$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bit_depth_luma"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int bit_depth_luma
     * }
     */
    public static final OfInt bit_depth_luma$layout() {
        return bit_depth_luma$LAYOUT;
    }

    private static final long bit_depth_luma$OFFSET = $LAYOUT.byteOffset(groupElement("bit_depth_luma"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int bit_depth_luma
     * }
     */
    public static final long bit_depth_luma$offset() {
        return bit_depth_luma$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int bit_depth_luma
     * }
     */
    public static int bit_depth_luma(MemorySegment struct) {
        return struct.get(bit_depth_luma$LAYOUT, bit_depth_luma$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int bit_depth_luma
     * }
     */
    public static void bit_depth_luma(MemorySegment struct, int fieldValue) {
        struct.set(bit_depth_luma$LAYOUT, bit_depth_luma$OFFSET, fieldValue);
    }

    private static final OfInt bit_depth_chroma$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bit_depth_chroma"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int bit_depth_chroma
     * }
     */
    public static final OfInt bit_depth_chroma$layout() {
        return bit_depth_chroma$LAYOUT;
    }

    private static final long bit_depth_chroma$OFFSET = $LAYOUT.byteOffset(groupElement("bit_depth_chroma"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int bit_depth_chroma
     * }
     */
    public static final long bit_depth_chroma$offset() {
        return bit_depth_chroma$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int bit_depth_chroma
     * }
     */
    public static int bit_depth_chroma(MemorySegment struct) {
        return struct.get(bit_depth_chroma$LAYOUT, bit_depth_chroma$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int bit_depth_chroma
     * }
     */
    public static void bit_depth_chroma(MemorySegment struct, int fieldValue) {
        struct.set(bit_depth_chroma$LAYOUT, bit_depth_chroma$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     AVFilmGrainAOMParams aom;
     *     AVFilmGrainH274Params h274;
     * }
     * }
     */
    public static class union {

        union() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            AVFilmGrainAOMParams.layout().withName("aom"),
            AVFilmGrainH274Params.layout().withName("h274")
        ).withName("union");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final GroupLayout aom$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("aom"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * AVFilmGrainAOMParams aom
         * }
         */
        public static final GroupLayout aom$layout() {
            return aom$LAYOUT;
        }

        private static final long aom$OFFSET = $LAYOUT.byteOffset(groupElement("aom"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * AVFilmGrainAOMParams aom
         * }
         */
        public static final long aom$offset() {
            return aom$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * AVFilmGrainAOMParams aom
         * }
         */
        public static MemorySegment aom(MemorySegment union) {
            return union.asSlice(aom$OFFSET, aom$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * AVFilmGrainAOMParams aom
         * }
         */
        public static void aom(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, aom$OFFSET, aom$LAYOUT.byteSize());
        }

        private static final GroupLayout h274$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("h274"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * AVFilmGrainH274Params h274
         * }
         */
        public static final GroupLayout h274$layout() {
            return h274$LAYOUT;
        }

        private static final long h274$OFFSET = $LAYOUT.byteOffset(groupElement("h274"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * AVFilmGrainH274Params h274
         * }
         */
        public static final long h274$offset() {
            return h274$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * AVFilmGrainH274Params h274
         * }
         */
        public static MemorySegment h274(MemorySegment union) {
            return union.asSlice(h274$OFFSET, h274$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * AVFilmGrainH274Params h274
         * }
         */
        public static void h274(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, h274$OFFSET, h274$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout codec$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("codec"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     AVFilmGrainAOMParams aom;
     *     AVFilmGrainH274Params h274;
     * } codec
     * }
     */
    public static final GroupLayout codec$layout() {
        return codec$LAYOUT;
    }

    private static final long codec$OFFSET = $LAYOUT.byteOffset(groupElement("codec"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     AVFilmGrainAOMParams aom;
     *     AVFilmGrainH274Params h274;
     * } codec
     * }
     */
    public static final long codec$offset() {
        return codec$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     AVFilmGrainAOMParams aom;
     *     AVFilmGrainH274Params h274;
     * } codec
     * }
     */
    public static MemorySegment codec(MemorySegment struct) {
        return struct.asSlice(codec$OFFSET, codec$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     AVFilmGrainAOMParams aom;
     *     AVFilmGrainH274Params h274;
     * } codec
     * }
     */
    public static void codec(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, codec$OFFSET, codec$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

