// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVHDRPlusPercentile {
 *     uint8_t percentage;
 *     AVRational percentile;
 * }
 * }
 */
public class AVHDRPlusPercentile {

    AVHDRPlusPercentile() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_CHAR.withName("percentage"),
        MemoryLayout.paddingLayout(3),
        AVRational.layout().withName("percentile")
    ).withName("AVHDRPlusPercentile");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte percentage$LAYOUT = (OfByte)$LAYOUT.select(groupElement("percentage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t percentage
     * }
     */
    public static final OfByte percentage$layout() {
        return percentage$LAYOUT;
    }

    private static final long percentage$OFFSET = $LAYOUT.byteOffset(groupElement("percentage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t percentage
     * }
     */
    public static final long percentage$offset() {
        return percentage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t percentage
     * }
     */
    public static byte percentage(MemorySegment struct) {
        return struct.get(percentage$LAYOUT, percentage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t percentage
     * }
     */
    public static void percentage(MemorySegment struct, byte fieldValue) {
        struct.set(percentage$LAYOUT, percentage$OFFSET, fieldValue);
    }

    private static final GroupLayout percentile$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("percentile"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational percentile
     * }
     */
    public static final GroupLayout percentile$layout() {
        return percentile$LAYOUT;
    }

    private static final long percentile$OFFSET = $LAYOUT.byteOffset(groupElement("percentile"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational percentile
     * }
     */
    public static final long percentile$offset() {
        return percentile$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational percentile
     * }
     */
    public static MemorySegment percentile(MemorySegment struct) {
        return struct.asSlice(percentile$OFFSET, percentile$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational percentile
     * }
     */
    public static void percentile(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, percentile$OFFSET, percentile$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

