// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVHDRPlusColorTransformParams {
 *     AVRational window_upper_left_corner_x;
 *     AVRational window_upper_left_corner_y;
 *     AVRational window_lower_right_corner_x;
 *     AVRational window_lower_right_corner_y;
 *     uint16_t center_of_ellipse_x;
 *     uint16_t center_of_ellipse_y;
 *     uint8_t rotation_angle;
 *     uint16_t semimajor_axis_internal_ellipse;
 *     uint16_t semimajor_axis_external_ellipse;
 *     uint16_t semiminor_axis_external_ellipse;
 *     enum AVHDRPlusOverlapProcessOption overlap_process_option;
 *     AVRational maxscl[3];
 *     AVRational average_maxrgb;
 *     uint8_t num_distribution_maxrgb_percentiles;
 *     AVHDRPlusPercentile distribution_maxrgb[15];
 *     AVRational fraction_bright_pixels;
 *     uint8_t tone_mapping_flag;
 *     AVRational knee_point_x;
 *     AVRational knee_point_y;
 *     uint8_t num_bezier_curve_anchors;
 *     AVRational bezier_curve_anchors[15];
 *     uint8_t color_saturation_mapping_flag;
 *     AVRational color_saturation_weight;
 * }
 * }
 */
public class AVHDRPlusColorTransformParams {

    AVHDRPlusColorTransformParams() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        AVRational.layout().withName("window_upper_left_corner_x"),
        AVRational.layout().withName("window_upper_left_corner_y"),
        AVRational.layout().withName("window_lower_right_corner_x"),
        AVRational.layout().withName("window_lower_right_corner_y"),
        FFMPEG.C_SHORT.withName("center_of_ellipse_x"),
        FFMPEG.C_SHORT.withName("center_of_ellipse_y"),
        FFMPEG.C_CHAR.withName("rotation_angle"),
        MemoryLayout.paddingLayout(1),
        FFMPEG.C_SHORT.withName("semimajor_axis_internal_ellipse"),
        FFMPEG.C_SHORT.withName("semimajor_axis_external_ellipse"),
        FFMPEG.C_SHORT.withName("semiminor_axis_external_ellipse"),
        FFMPEG.C_INT.withName("overlap_process_option"),
        MemoryLayout.sequenceLayout(3, AVRational.layout()).withName("maxscl"),
        AVRational.layout().withName("average_maxrgb"),
        FFMPEG.C_CHAR.withName("num_distribution_maxrgb_percentiles"),
        MemoryLayout.paddingLayout(3),
        MemoryLayout.sequenceLayout(15, AVHDRPlusPercentile.layout()).withName("distribution_maxrgb"),
        AVRational.layout().withName("fraction_bright_pixels"),
        FFMPEG.C_CHAR.withName("tone_mapping_flag"),
        MemoryLayout.paddingLayout(3),
        AVRational.layout().withName("knee_point_x"),
        AVRational.layout().withName("knee_point_y"),
        FFMPEG.C_CHAR.withName("num_bezier_curve_anchors"),
        MemoryLayout.paddingLayout(3),
        MemoryLayout.sequenceLayout(15, AVRational.layout()).withName("bezier_curve_anchors"),
        FFMPEG.C_CHAR.withName("color_saturation_mapping_flag"),
        MemoryLayout.paddingLayout(3),
        AVRational.layout().withName("color_saturation_weight")
    ).withName("AVHDRPlusColorTransformParams");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout window_upper_left_corner_x$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("window_upper_left_corner_x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational window_upper_left_corner_x
     * }
     */
    public static final GroupLayout window_upper_left_corner_x$layout() {
        return window_upper_left_corner_x$LAYOUT;
    }

    private static final long window_upper_left_corner_x$OFFSET = $LAYOUT.byteOffset(groupElement("window_upper_left_corner_x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational window_upper_left_corner_x
     * }
     */
    public static final long window_upper_left_corner_x$offset() {
        return window_upper_left_corner_x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational window_upper_left_corner_x
     * }
     */
    public static MemorySegment window_upper_left_corner_x(MemorySegment struct) {
        return struct.asSlice(window_upper_left_corner_x$OFFSET, window_upper_left_corner_x$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational window_upper_left_corner_x
     * }
     */
    public static void window_upper_left_corner_x(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, window_upper_left_corner_x$OFFSET, window_upper_left_corner_x$LAYOUT.byteSize());
    }

    private static final GroupLayout window_upper_left_corner_y$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("window_upper_left_corner_y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational window_upper_left_corner_y
     * }
     */
    public static final GroupLayout window_upper_left_corner_y$layout() {
        return window_upper_left_corner_y$LAYOUT;
    }

    private static final long window_upper_left_corner_y$OFFSET = $LAYOUT.byteOffset(groupElement("window_upper_left_corner_y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational window_upper_left_corner_y
     * }
     */
    public static final long window_upper_left_corner_y$offset() {
        return window_upper_left_corner_y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational window_upper_left_corner_y
     * }
     */
    public static MemorySegment window_upper_left_corner_y(MemorySegment struct) {
        return struct.asSlice(window_upper_left_corner_y$OFFSET, window_upper_left_corner_y$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational window_upper_left_corner_y
     * }
     */
    public static void window_upper_left_corner_y(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, window_upper_left_corner_y$OFFSET, window_upper_left_corner_y$LAYOUT.byteSize());
    }

    private static final GroupLayout window_lower_right_corner_x$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("window_lower_right_corner_x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational window_lower_right_corner_x
     * }
     */
    public static final GroupLayout window_lower_right_corner_x$layout() {
        return window_lower_right_corner_x$LAYOUT;
    }

    private static final long window_lower_right_corner_x$OFFSET = $LAYOUT.byteOffset(groupElement("window_lower_right_corner_x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational window_lower_right_corner_x
     * }
     */
    public static final long window_lower_right_corner_x$offset() {
        return window_lower_right_corner_x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational window_lower_right_corner_x
     * }
     */
    public static MemorySegment window_lower_right_corner_x(MemorySegment struct) {
        return struct.asSlice(window_lower_right_corner_x$OFFSET, window_lower_right_corner_x$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational window_lower_right_corner_x
     * }
     */
    public static void window_lower_right_corner_x(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, window_lower_right_corner_x$OFFSET, window_lower_right_corner_x$LAYOUT.byteSize());
    }

    private static final GroupLayout window_lower_right_corner_y$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("window_lower_right_corner_y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational window_lower_right_corner_y
     * }
     */
    public static final GroupLayout window_lower_right_corner_y$layout() {
        return window_lower_right_corner_y$LAYOUT;
    }

    private static final long window_lower_right_corner_y$OFFSET = $LAYOUT.byteOffset(groupElement("window_lower_right_corner_y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational window_lower_right_corner_y
     * }
     */
    public static final long window_lower_right_corner_y$offset() {
        return window_lower_right_corner_y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational window_lower_right_corner_y
     * }
     */
    public static MemorySegment window_lower_right_corner_y(MemorySegment struct) {
        return struct.asSlice(window_lower_right_corner_y$OFFSET, window_lower_right_corner_y$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational window_lower_right_corner_y
     * }
     */
    public static void window_lower_right_corner_y(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, window_lower_right_corner_y$OFFSET, window_lower_right_corner_y$LAYOUT.byteSize());
    }

    private static final OfShort center_of_ellipse_x$LAYOUT = (OfShort)$LAYOUT.select(groupElement("center_of_ellipse_x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t center_of_ellipse_x
     * }
     */
    public static final OfShort center_of_ellipse_x$layout() {
        return center_of_ellipse_x$LAYOUT;
    }

    private static final long center_of_ellipse_x$OFFSET = $LAYOUT.byteOffset(groupElement("center_of_ellipse_x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t center_of_ellipse_x
     * }
     */
    public static final long center_of_ellipse_x$offset() {
        return center_of_ellipse_x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t center_of_ellipse_x
     * }
     */
    public static short center_of_ellipse_x(MemorySegment struct) {
        return struct.get(center_of_ellipse_x$LAYOUT, center_of_ellipse_x$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t center_of_ellipse_x
     * }
     */
    public static void center_of_ellipse_x(MemorySegment struct, short fieldValue) {
        struct.set(center_of_ellipse_x$LAYOUT, center_of_ellipse_x$OFFSET, fieldValue);
    }

    private static final OfShort center_of_ellipse_y$LAYOUT = (OfShort)$LAYOUT.select(groupElement("center_of_ellipse_y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t center_of_ellipse_y
     * }
     */
    public static final OfShort center_of_ellipse_y$layout() {
        return center_of_ellipse_y$LAYOUT;
    }

    private static final long center_of_ellipse_y$OFFSET = $LAYOUT.byteOffset(groupElement("center_of_ellipse_y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t center_of_ellipse_y
     * }
     */
    public static final long center_of_ellipse_y$offset() {
        return center_of_ellipse_y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t center_of_ellipse_y
     * }
     */
    public static short center_of_ellipse_y(MemorySegment struct) {
        return struct.get(center_of_ellipse_y$LAYOUT, center_of_ellipse_y$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t center_of_ellipse_y
     * }
     */
    public static void center_of_ellipse_y(MemorySegment struct, short fieldValue) {
        struct.set(center_of_ellipse_y$LAYOUT, center_of_ellipse_y$OFFSET, fieldValue);
    }

    private static final OfByte rotation_angle$LAYOUT = (OfByte)$LAYOUT.select(groupElement("rotation_angle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t rotation_angle
     * }
     */
    public static final OfByte rotation_angle$layout() {
        return rotation_angle$LAYOUT;
    }

    private static final long rotation_angle$OFFSET = $LAYOUT.byteOffset(groupElement("rotation_angle"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t rotation_angle
     * }
     */
    public static final long rotation_angle$offset() {
        return rotation_angle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t rotation_angle
     * }
     */
    public static byte rotation_angle(MemorySegment struct) {
        return struct.get(rotation_angle$LAYOUT, rotation_angle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t rotation_angle
     * }
     */
    public static void rotation_angle(MemorySegment struct, byte fieldValue) {
        struct.set(rotation_angle$LAYOUT, rotation_angle$OFFSET, fieldValue);
    }

    private static final OfShort semimajor_axis_internal_ellipse$LAYOUT = (OfShort)$LAYOUT.select(groupElement("semimajor_axis_internal_ellipse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t semimajor_axis_internal_ellipse
     * }
     */
    public static final OfShort semimajor_axis_internal_ellipse$layout() {
        return semimajor_axis_internal_ellipse$LAYOUT;
    }

    private static final long semimajor_axis_internal_ellipse$OFFSET = $LAYOUT.byteOffset(groupElement("semimajor_axis_internal_ellipse"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t semimajor_axis_internal_ellipse
     * }
     */
    public static final long semimajor_axis_internal_ellipse$offset() {
        return semimajor_axis_internal_ellipse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t semimajor_axis_internal_ellipse
     * }
     */
    public static short semimajor_axis_internal_ellipse(MemorySegment struct) {
        return struct.get(semimajor_axis_internal_ellipse$LAYOUT, semimajor_axis_internal_ellipse$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t semimajor_axis_internal_ellipse
     * }
     */
    public static void semimajor_axis_internal_ellipse(MemorySegment struct, short fieldValue) {
        struct.set(semimajor_axis_internal_ellipse$LAYOUT, semimajor_axis_internal_ellipse$OFFSET, fieldValue);
    }

    private static final OfShort semimajor_axis_external_ellipse$LAYOUT = (OfShort)$LAYOUT.select(groupElement("semimajor_axis_external_ellipse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t semimajor_axis_external_ellipse
     * }
     */
    public static final OfShort semimajor_axis_external_ellipse$layout() {
        return semimajor_axis_external_ellipse$LAYOUT;
    }

    private static final long semimajor_axis_external_ellipse$OFFSET = $LAYOUT.byteOffset(groupElement("semimajor_axis_external_ellipse"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t semimajor_axis_external_ellipse
     * }
     */
    public static final long semimajor_axis_external_ellipse$offset() {
        return semimajor_axis_external_ellipse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t semimajor_axis_external_ellipse
     * }
     */
    public static short semimajor_axis_external_ellipse(MemorySegment struct) {
        return struct.get(semimajor_axis_external_ellipse$LAYOUT, semimajor_axis_external_ellipse$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t semimajor_axis_external_ellipse
     * }
     */
    public static void semimajor_axis_external_ellipse(MemorySegment struct, short fieldValue) {
        struct.set(semimajor_axis_external_ellipse$LAYOUT, semimajor_axis_external_ellipse$OFFSET, fieldValue);
    }

    private static final OfShort semiminor_axis_external_ellipse$LAYOUT = (OfShort)$LAYOUT.select(groupElement("semiminor_axis_external_ellipse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t semiminor_axis_external_ellipse
     * }
     */
    public static final OfShort semiminor_axis_external_ellipse$layout() {
        return semiminor_axis_external_ellipse$LAYOUT;
    }

    private static final long semiminor_axis_external_ellipse$OFFSET = $LAYOUT.byteOffset(groupElement("semiminor_axis_external_ellipse"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t semiminor_axis_external_ellipse
     * }
     */
    public static final long semiminor_axis_external_ellipse$offset() {
        return semiminor_axis_external_ellipse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t semiminor_axis_external_ellipse
     * }
     */
    public static short semiminor_axis_external_ellipse(MemorySegment struct) {
        return struct.get(semiminor_axis_external_ellipse$LAYOUT, semiminor_axis_external_ellipse$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t semiminor_axis_external_ellipse
     * }
     */
    public static void semiminor_axis_external_ellipse(MemorySegment struct, short fieldValue) {
        struct.set(semiminor_axis_external_ellipse$LAYOUT, semiminor_axis_external_ellipse$OFFSET, fieldValue);
    }

    private static final OfInt overlap_process_option$LAYOUT = (OfInt)$LAYOUT.select(groupElement("overlap_process_option"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVHDRPlusOverlapProcessOption overlap_process_option
     * }
     */
    public static final OfInt overlap_process_option$layout() {
        return overlap_process_option$LAYOUT;
    }

    private static final long overlap_process_option$OFFSET = $LAYOUT.byteOffset(groupElement("overlap_process_option"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVHDRPlusOverlapProcessOption overlap_process_option
     * }
     */
    public static final long overlap_process_option$offset() {
        return overlap_process_option$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVHDRPlusOverlapProcessOption overlap_process_option
     * }
     */
    public static int overlap_process_option(MemorySegment struct) {
        return struct.get(overlap_process_option$LAYOUT, overlap_process_option$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVHDRPlusOverlapProcessOption overlap_process_option
     * }
     */
    public static void overlap_process_option(MemorySegment struct, int fieldValue) {
        struct.set(overlap_process_option$LAYOUT, overlap_process_option$OFFSET, fieldValue);
    }

    private static final SequenceLayout maxscl$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("maxscl"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational maxscl[3]
     * }
     */
    public static final SequenceLayout maxscl$layout() {
        return maxscl$LAYOUT;
    }

    private static final long maxscl$OFFSET = $LAYOUT.byteOffset(groupElement("maxscl"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational maxscl[3]
     * }
     */
    public static final long maxscl$offset() {
        return maxscl$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational maxscl[3]
     * }
     */
    public static MemorySegment maxscl(MemorySegment struct) {
        return struct.asSlice(maxscl$OFFSET, maxscl$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational maxscl[3]
     * }
     */
    public static void maxscl(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, maxscl$OFFSET, maxscl$LAYOUT.byteSize());
    }

    private static long[] maxscl$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVRational maxscl[3]
     * }
     */
    public static long[] maxscl$dimensions() {
        return maxscl$DIMS;
    }
    private static final MethodHandle maxscl$ELEM_HANDLE = maxscl$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVRational maxscl[3]
     * }
     */
    public static MemorySegment maxscl(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)maxscl$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVRational maxscl[3]
     * }
     */
    public static void maxscl(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, maxscl(struct, index0), 0L, AVRational.layout().byteSize());
    }

    private static final GroupLayout average_maxrgb$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("average_maxrgb"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational average_maxrgb
     * }
     */
    public static final GroupLayout average_maxrgb$layout() {
        return average_maxrgb$LAYOUT;
    }

    private static final long average_maxrgb$OFFSET = $LAYOUT.byteOffset(groupElement("average_maxrgb"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational average_maxrgb
     * }
     */
    public static final long average_maxrgb$offset() {
        return average_maxrgb$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational average_maxrgb
     * }
     */
    public static MemorySegment average_maxrgb(MemorySegment struct) {
        return struct.asSlice(average_maxrgb$OFFSET, average_maxrgb$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational average_maxrgb
     * }
     */
    public static void average_maxrgb(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, average_maxrgb$OFFSET, average_maxrgb$LAYOUT.byteSize());
    }

    private static final OfByte num_distribution_maxrgb_percentiles$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_distribution_maxrgb_percentiles"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t num_distribution_maxrgb_percentiles
     * }
     */
    public static final OfByte num_distribution_maxrgb_percentiles$layout() {
        return num_distribution_maxrgb_percentiles$LAYOUT;
    }

    private static final long num_distribution_maxrgb_percentiles$OFFSET = $LAYOUT.byteOffset(groupElement("num_distribution_maxrgb_percentiles"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t num_distribution_maxrgb_percentiles
     * }
     */
    public static final long num_distribution_maxrgb_percentiles$offset() {
        return num_distribution_maxrgb_percentiles$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t num_distribution_maxrgb_percentiles
     * }
     */
    public static byte num_distribution_maxrgb_percentiles(MemorySegment struct) {
        return struct.get(num_distribution_maxrgb_percentiles$LAYOUT, num_distribution_maxrgb_percentiles$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t num_distribution_maxrgb_percentiles
     * }
     */
    public static void num_distribution_maxrgb_percentiles(MemorySegment struct, byte fieldValue) {
        struct.set(num_distribution_maxrgb_percentiles$LAYOUT, num_distribution_maxrgb_percentiles$OFFSET, fieldValue);
    }

    private static final SequenceLayout distribution_maxrgb$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("distribution_maxrgb"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVHDRPlusPercentile distribution_maxrgb[15]
     * }
     */
    public static final SequenceLayout distribution_maxrgb$layout() {
        return distribution_maxrgb$LAYOUT;
    }

    private static final long distribution_maxrgb$OFFSET = $LAYOUT.byteOffset(groupElement("distribution_maxrgb"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVHDRPlusPercentile distribution_maxrgb[15]
     * }
     */
    public static final long distribution_maxrgb$offset() {
        return distribution_maxrgb$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVHDRPlusPercentile distribution_maxrgb[15]
     * }
     */
    public static MemorySegment distribution_maxrgb(MemorySegment struct) {
        return struct.asSlice(distribution_maxrgb$OFFSET, distribution_maxrgb$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVHDRPlusPercentile distribution_maxrgb[15]
     * }
     */
    public static void distribution_maxrgb(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, distribution_maxrgb$OFFSET, distribution_maxrgb$LAYOUT.byteSize());
    }

    private static long[] distribution_maxrgb$DIMS = { 15 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVHDRPlusPercentile distribution_maxrgb[15]
     * }
     */
    public static long[] distribution_maxrgb$dimensions() {
        return distribution_maxrgb$DIMS;
    }
    private static final MethodHandle distribution_maxrgb$ELEM_HANDLE = distribution_maxrgb$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVHDRPlusPercentile distribution_maxrgb[15]
     * }
     */
    public static MemorySegment distribution_maxrgb(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)distribution_maxrgb$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVHDRPlusPercentile distribution_maxrgb[15]
     * }
     */
    public static void distribution_maxrgb(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, distribution_maxrgb(struct, index0), 0L, AVHDRPlusPercentile.layout().byteSize());
    }

    private static final GroupLayout fraction_bright_pixels$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("fraction_bright_pixels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational fraction_bright_pixels
     * }
     */
    public static final GroupLayout fraction_bright_pixels$layout() {
        return fraction_bright_pixels$LAYOUT;
    }

    private static final long fraction_bright_pixels$OFFSET = $LAYOUT.byteOffset(groupElement("fraction_bright_pixels"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational fraction_bright_pixels
     * }
     */
    public static final long fraction_bright_pixels$offset() {
        return fraction_bright_pixels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational fraction_bright_pixels
     * }
     */
    public static MemorySegment fraction_bright_pixels(MemorySegment struct) {
        return struct.asSlice(fraction_bright_pixels$OFFSET, fraction_bright_pixels$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational fraction_bright_pixels
     * }
     */
    public static void fraction_bright_pixels(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, fraction_bright_pixels$OFFSET, fraction_bright_pixels$LAYOUT.byteSize());
    }

    private static final OfByte tone_mapping_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("tone_mapping_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t tone_mapping_flag
     * }
     */
    public static final OfByte tone_mapping_flag$layout() {
        return tone_mapping_flag$LAYOUT;
    }

    private static final long tone_mapping_flag$OFFSET = $LAYOUT.byteOffset(groupElement("tone_mapping_flag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t tone_mapping_flag
     * }
     */
    public static final long tone_mapping_flag$offset() {
        return tone_mapping_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t tone_mapping_flag
     * }
     */
    public static byte tone_mapping_flag(MemorySegment struct) {
        return struct.get(tone_mapping_flag$LAYOUT, tone_mapping_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t tone_mapping_flag
     * }
     */
    public static void tone_mapping_flag(MemorySegment struct, byte fieldValue) {
        struct.set(tone_mapping_flag$LAYOUT, tone_mapping_flag$OFFSET, fieldValue);
    }

    private static final GroupLayout knee_point_x$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("knee_point_x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational knee_point_x
     * }
     */
    public static final GroupLayout knee_point_x$layout() {
        return knee_point_x$LAYOUT;
    }

    private static final long knee_point_x$OFFSET = $LAYOUT.byteOffset(groupElement("knee_point_x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational knee_point_x
     * }
     */
    public static final long knee_point_x$offset() {
        return knee_point_x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational knee_point_x
     * }
     */
    public static MemorySegment knee_point_x(MemorySegment struct) {
        return struct.asSlice(knee_point_x$OFFSET, knee_point_x$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational knee_point_x
     * }
     */
    public static void knee_point_x(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, knee_point_x$OFFSET, knee_point_x$LAYOUT.byteSize());
    }

    private static final GroupLayout knee_point_y$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("knee_point_y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational knee_point_y
     * }
     */
    public static final GroupLayout knee_point_y$layout() {
        return knee_point_y$LAYOUT;
    }

    private static final long knee_point_y$OFFSET = $LAYOUT.byteOffset(groupElement("knee_point_y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational knee_point_y
     * }
     */
    public static final long knee_point_y$offset() {
        return knee_point_y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational knee_point_y
     * }
     */
    public static MemorySegment knee_point_y(MemorySegment struct) {
        return struct.asSlice(knee_point_y$OFFSET, knee_point_y$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational knee_point_y
     * }
     */
    public static void knee_point_y(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, knee_point_y$OFFSET, knee_point_y$LAYOUT.byteSize());
    }

    private static final OfByte num_bezier_curve_anchors$LAYOUT = (OfByte)$LAYOUT.select(groupElement("num_bezier_curve_anchors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t num_bezier_curve_anchors
     * }
     */
    public static final OfByte num_bezier_curve_anchors$layout() {
        return num_bezier_curve_anchors$LAYOUT;
    }

    private static final long num_bezier_curve_anchors$OFFSET = $LAYOUT.byteOffset(groupElement("num_bezier_curve_anchors"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t num_bezier_curve_anchors
     * }
     */
    public static final long num_bezier_curve_anchors$offset() {
        return num_bezier_curve_anchors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t num_bezier_curve_anchors
     * }
     */
    public static byte num_bezier_curve_anchors(MemorySegment struct) {
        return struct.get(num_bezier_curve_anchors$LAYOUT, num_bezier_curve_anchors$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t num_bezier_curve_anchors
     * }
     */
    public static void num_bezier_curve_anchors(MemorySegment struct, byte fieldValue) {
        struct.set(num_bezier_curve_anchors$LAYOUT, num_bezier_curve_anchors$OFFSET, fieldValue);
    }

    private static final SequenceLayout bezier_curve_anchors$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("bezier_curve_anchors"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational bezier_curve_anchors[15]
     * }
     */
    public static final SequenceLayout bezier_curve_anchors$layout() {
        return bezier_curve_anchors$LAYOUT;
    }

    private static final long bezier_curve_anchors$OFFSET = $LAYOUT.byteOffset(groupElement("bezier_curve_anchors"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational bezier_curve_anchors[15]
     * }
     */
    public static final long bezier_curve_anchors$offset() {
        return bezier_curve_anchors$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational bezier_curve_anchors[15]
     * }
     */
    public static MemorySegment bezier_curve_anchors(MemorySegment struct) {
        return struct.asSlice(bezier_curve_anchors$OFFSET, bezier_curve_anchors$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational bezier_curve_anchors[15]
     * }
     */
    public static void bezier_curve_anchors(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, bezier_curve_anchors$OFFSET, bezier_curve_anchors$LAYOUT.byteSize());
    }

    private static long[] bezier_curve_anchors$DIMS = { 15 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * AVRational bezier_curve_anchors[15]
     * }
     */
    public static long[] bezier_curve_anchors$dimensions() {
        return bezier_curve_anchors$DIMS;
    }
    private static final MethodHandle bezier_curve_anchors$ELEM_HANDLE = bezier_curve_anchors$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * AVRational bezier_curve_anchors[15]
     * }
     */
    public static MemorySegment bezier_curve_anchors(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)bezier_curve_anchors$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * AVRational bezier_curve_anchors[15]
     * }
     */
    public static void bezier_curve_anchors(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, bezier_curve_anchors(struct, index0), 0L, AVRational.layout().byteSize());
    }

    private static final OfByte color_saturation_mapping_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("color_saturation_mapping_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t color_saturation_mapping_flag
     * }
     */
    public static final OfByte color_saturation_mapping_flag$layout() {
        return color_saturation_mapping_flag$LAYOUT;
    }

    private static final long color_saturation_mapping_flag$OFFSET = $LAYOUT.byteOffset(groupElement("color_saturation_mapping_flag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t color_saturation_mapping_flag
     * }
     */
    public static final long color_saturation_mapping_flag$offset() {
        return color_saturation_mapping_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t color_saturation_mapping_flag
     * }
     */
    public static byte color_saturation_mapping_flag(MemorySegment struct) {
        return struct.get(color_saturation_mapping_flag$LAYOUT, color_saturation_mapping_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t color_saturation_mapping_flag
     * }
     */
    public static void color_saturation_mapping_flag(MemorySegment struct, byte fieldValue) {
        struct.set(color_saturation_mapping_flag$LAYOUT, color_saturation_mapping_flag$OFFSET, fieldValue);
    }

    private static final GroupLayout color_saturation_weight$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("color_saturation_weight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational color_saturation_weight
     * }
     */
    public static final GroupLayout color_saturation_weight$layout() {
        return color_saturation_weight$LAYOUT;
    }

    private static final long color_saturation_weight$OFFSET = $LAYOUT.byteOffset(groupElement("color_saturation_weight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational color_saturation_weight
     * }
     */
    public static final long color_saturation_weight$offset() {
        return color_saturation_weight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational color_saturation_weight
     * }
     */
    public static MemorySegment color_saturation_weight(MemorySegment struct) {
        return struct.asSlice(color_saturation_weight$OFFSET, color_saturation_weight$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational color_saturation_weight
     * }
     */
    public static void color_saturation_weight(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, color_saturation_weight$OFFSET, color_saturation_weight$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

