// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVIAMFSubmixLayout {
 *     const AVClass *av_class;
 *     enum AVIAMFSubmixLayoutType layout_type;
 *     AVChannelLayout sound_system;
 *     AVRational integrated_loudness;
 *     AVRational digital_peak;
 *     AVRational true_peak;
 *     AVRational dialogue_anchored_loudness;
 *     AVRational album_anchored_loudness;
 * }
 * }
 */
public class AVIAMFSubmixLayout {

    AVIAMFSubmixLayout() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("av_class"),
        FFMPEG.C_INT.withName("layout_type"),
        MemoryLayout.paddingLayout(4),
        AVChannelLayout.layout().withName("sound_system"),
        AVRational.layout().withName("integrated_loudness"),
        AVRational.layout().withName("digital_peak"),
        AVRational.layout().withName("true_peak"),
        AVRational.layout().withName("dialogue_anchored_loudness"),
        AVRational.layout().withName("album_anchored_loudness")
    ).withName("AVIAMFSubmixLayout");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout av_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("av_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final AddressLayout av_class$layout() {
        return av_class$LAYOUT;
    }

    private static final long av_class$OFFSET = $LAYOUT.byteOffset(groupElement("av_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final long av_class$offset() {
        return av_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static MemorySegment av_class(MemorySegment struct) {
        return struct.get(av_class$LAYOUT, av_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static void av_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(av_class$LAYOUT, av_class$OFFSET, fieldValue);
    }

    private static final OfInt layout_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("layout_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVIAMFSubmixLayoutType layout_type
     * }
     */
    public static final OfInt layout_type$layout() {
        return layout_type$LAYOUT;
    }

    private static final long layout_type$OFFSET = $LAYOUT.byteOffset(groupElement("layout_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVIAMFSubmixLayoutType layout_type
     * }
     */
    public static final long layout_type$offset() {
        return layout_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVIAMFSubmixLayoutType layout_type
     * }
     */
    public static int layout_type(MemorySegment struct) {
        return struct.get(layout_type$LAYOUT, layout_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVIAMFSubmixLayoutType layout_type
     * }
     */
    public static void layout_type(MemorySegment struct, int fieldValue) {
        struct.set(layout_type$LAYOUT, layout_type$OFFSET, fieldValue);
    }

    private static final GroupLayout sound_system$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("sound_system"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVChannelLayout sound_system
     * }
     */
    public static final GroupLayout sound_system$layout() {
        return sound_system$LAYOUT;
    }

    private static final long sound_system$OFFSET = $LAYOUT.byteOffset(groupElement("sound_system"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVChannelLayout sound_system
     * }
     */
    public static final long sound_system$offset() {
        return sound_system$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVChannelLayout sound_system
     * }
     */
    public static MemorySegment sound_system(MemorySegment struct) {
        return struct.asSlice(sound_system$OFFSET, sound_system$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVChannelLayout sound_system
     * }
     */
    public static void sound_system(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sound_system$OFFSET, sound_system$LAYOUT.byteSize());
    }

    private static final GroupLayout integrated_loudness$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("integrated_loudness"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational integrated_loudness
     * }
     */
    public static final GroupLayout integrated_loudness$layout() {
        return integrated_loudness$LAYOUT;
    }

    private static final long integrated_loudness$OFFSET = $LAYOUT.byteOffset(groupElement("integrated_loudness"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational integrated_loudness
     * }
     */
    public static final long integrated_loudness$offset() {
        return integrated_loudness$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational integrated_loudness
     * }
     */
    public static MemorySegment integrated_loudness(MemorySegment struct) {
        return struct.asSlice(integrated_loudness$OFFSET, integrated_loudness$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational integrated_loudness
     * }
     */
    public static void integrated_loudness(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, integrated_loudness$OFFSET, integrated_loudness$LAYOUT.byteSize());
    }

    private static final GroupLayout digital_peak$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("digital_peak"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational digital_peak
     * }
     */
    public static final GroupLayout digital_peak$layout() {
        return digital_peak$LAYOUT;
    }

    private static final long digital_peak$OFFSET = $LAYOUT.byteOffset(groupElement("digital_peak"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational digital_peak
     * }
     */
    public static final long digital_peak$offset() {
        return digital_peak$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational digital_peak
     * }
     */
    public static MemorySegment digital_peak(MemorySegment struct) {
        return struct.asSlice(digital_peak$OFFSET, digital_peak$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational digital_peak
     * }
     */
    public static void digital_peak(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, digital_peak$OFFSET, digital_peak$LAYOUT.byteSize());
    }

    private static final GroupLayout true_peak$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("true_peak"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational true_peak
     * }
     */
    public static final GroupLayout true_peak$layout() {
        return true_peak$LAYOUT;
    }

    private static final long true_peak$OFFSET = $LAYOUT.byteOffset(groupElement("true_peak"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational true_peak
     * }
     */
    public static final long true_peak$offset() {
        return true_peak$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational true_peak
     * }
     */
    public static MemorySegment true_peak(MemorySegment struct) {
        return struct.asSlice(true_peak$OFFSET, true_peak$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational true_peak
     * }
     */
    public static void true_peak(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, true_peak$OFFSET, true_peak$LAYOUT.byteSize());
    }

    private static final GroupLayout dialogue_anchored_loudness$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("dialogue_anchored_loudness"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational dialogue_anchored_loudness
     * }
     */
    public static final GroupLayout dialogue_anchored_loudness$layout() {
        return dialogue_anchored_loudness$LAYOUT;
    }

    private static final long dialogue_anchored_loudness$OFFSET = $LAYOUT.byteOffset(groupElement("dialogue_anchored_loudness"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational dialogue_anchored_loudness
     * }
     */
    public static final long dialogue_anchored_loudness$offset() {
        return dialogue_anchored_loudness$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational dialogue_anchored_loudness
     * }
     */
    public static MemorySegment dialogue_anchored_loudness(MemorySegment struct) {
        return struct.asSlice(dialogue_anchored_loudness$OFFSET, dialogue_anchored_loudness$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational dialogue_anchored_loudness
     * }
     */
    public static void dialogue_anchored_loudness(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, dialogue_anchored_loudness$OFFSET, dialogue_anchored_loudness$LAYOUT.byteSize());
    }

    private static final GroupLayout album_anchored_loudness$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("album_anchored_loudness"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational album_anchored_loudness
     * }
     */
    public static final GroupLayout album_anchored_loudness$layout() {
        return album_anchored_loudness$LAYOUT;
    }

    private static final long album_anchored_loudness$OFFSET = $LAYOUT.byteOffset(groupElement("album_anchored_loudness"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational album_anchored_loudness
     * }
     */
    public static final long album_anchored_loudness$offset() {
        return album_anchored_loudness$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational album_anchored_loudness
     * }
     */
    public static MemorySegment album_anchored_loudness(MemorySegment struct) {
        return struct.asSlice(album_anchored_loudness$OFFSET, album_anchored_loudness$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational album_anchored_loudness
     * }
     */
    public static void album_anchored_loudness(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, album_anchored_loudness$OFFSET, album_anchored_loudness$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

