// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVIAMFSubmixElement {
 *     const AVClass *av_class;
 *     unsigned int audio_element_id;
 *     AVIAMFParamDefinition *element_mix_config;
 *     AVRational default_mix_gain;
 *     enum AVIAMFHeadphonesMode headphones_rendering_mode;
 *     AVDictionary *annotations;
 * }
 * }
 */
public class AVIAMFSubmixElement {

    AVIAMFSubmixElement() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("av_class"),
        FFMPEG.C_INT.withName("audio_element_id"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("element_mix_config"),
        AVRational.layout().withName("default_mix_gain"),
        FFMPEG.C_INT.withName("headphones_rendering_mode"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("annotations")
    ).withName("AVIAMFSubmixElement");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout av_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("av_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final AddressLayout av_class$layout() {
        return av_class$LAYOUT;
    }

    private static final long av_class$OFFSET = $LAYOUT.byteOffset(groupElement("av_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final long av_class$offset() {
        return av_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static MemorySegment av_class(MemorySegment struct) {
        return struct.get(av_class$LAYOUT, av_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static void av_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(av_class$LAYOUT, av_class$OFFSET, fieldValue);
    }

    private static final OfInt audio_element_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("audio_element_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int audio_element_id
     * }
     */
    public static final OfInt audio_element_id$layout() {
        return audio_element_id$LAYOUT;
    }

    private static final long audio_element_id$OFFSET = $LAYOUT.byteOffset(groupElement("audio_element_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int audio_element_id
     * }
     */
    public static final long audio_element_id$offset() {
        return audio_element_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int audio_element_id
     * }
     */
    public static int audio_element_id(MemorySegment struct) {
        return struct.get(audio_element_id$LAYOUT, audio_element_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int audio_element_id
     * }
     */
    public static void audio_element_id(MemorySegment struct, int fieldValue) {
        struct.set(audio_element_id$LAYOUT, audio_element_id$OFFSET, fieldValue);
    }

    private static final AddressLayout element_mix_config$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("element_mix_config"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *element_mix_config
     * }
     */
    public static final AddressLayout element_mix_config$layout() {
        return element_mix_config$LAYOUT;
    }

    private static final long element_mix_config$OFFSET = $LAYOUT.byteOffset(groupElement("element_mix_config"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *element_mix_config
     * }
     */
    public static final long element_mix_config$offset() {
        return element_mix_config$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *element_mix_config
     * }
     */
    public static MemorySegment element_mix_config(MemorySegment struct) {
        return struct.get(element_mix_config$LAYOUT, element_mix_config$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *element_mix_config
     * }
     */
    public static void element_mix_config(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(element_mix_config$LAYOUT, element_mix_config$OFFSET, fieldValue);
    }

    private static final GroupLayout default_mix_gain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("default_mix_gain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational default_mix_gain
     * }
     */
    public static final GroupLayout default_mix_gain$layout() {
        return default_mix_gain$LAYOUT;
    }

    private static final long default_mix_gain$OFFSET = $LAYOUT.byteOffset(groupElement("default_mix_gain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational default_mix_gain
     * }
     */
    public static final long default_mix_gain$offset() {
        return default_mix_gain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational default_mix_gain
     * }
     */
    public static MemorySegment default_mix_gain(MemorySegment struct) {
        return struct.asSlice(default_mix_gain$OFFSET, default_mix_gain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational default_mix_gain
     * }
     */
    public static void default_mix_gain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, default_mix_gain$OFFSET, default_mix_gain$LAYOUT.byteSize());
    }

    private static final OfInt headphones_rendering_mode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("headphones_rendering_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVIAMFHeadphonesMode headphones_rendering_mode
     * }
     */
    public static final OfInt headphones_rendering_mode$layout() {
        return headphones_rendering_mode$LAYOUT;
    }

    private static final long headphones_rendering_mode$OFFSET = $LAYOUT.byteOffset(groupElement("headphones_rendering_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVIAMFHeadphonesMode headphones_rendering_mode
     * }
     */
    public static final long headphones_rendering_mode$offset() {
        return headphones_rendering_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVIAMFHeadphonesMode headphones_rendering_mode
     * }
     */
    public static int headphones_rendering_mode(MemorySegment struct) {
        return struct.get(headphones_rendering_mode$LAYOUT, headphones_rendering_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVIAMFHeadphonesMode headphones_rendering_mode
     * }
     */
    public static void headphones_rendering_mode(MemorySegment struct, int fieldValue) {
        struct.set(headphones_rendering_mode$LAYOUT, headphones_rendering_mode$OFFSET, fieldValue);
    }

    private static final AddressLayout annotations$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("annotations"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVDictionary *annotations
     * }
     */
    public static final AddressLayout annotations$layout() {
        return annotations$LAYOUT;
    }

    private static final long annotations$OFFSET = $LAYOUT.byteOffset(groupElement("annotations"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVDictionary *annotations
     * }
     */
    public static final long annotations$offset() {
        return annotations$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVDictionary *annotations
     * }
     */
    public static MemorySegment annotations(MemorySegment struct) {
        return struct.get(annotations$LAYOUT, annotations$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVDictionary *annotations
     * }
     */
    public static void annotations(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(annotations$LAYOUT, annotations$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

