// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVIAMFSubmix {
 *     const AVClass *av_class;
 *     AVIAMFSubmixElement **elements;
 *     unsigned int nb_elements;
 *     AVIAMFSubmixLayout **layouts;
 *     unsigned int nb_layouts;
 *     AVIAMFParamDefinition *output_mix_config;
 *     AVRational default_mix_gain;
 * }
 * }
 */
public class AVIAMFSubmix {

    AVIAMFSubmix() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("av_class"),
        FFMPEG.C_POINTER.withName("elements"),
        FFMPEG.C_INT.withName("nb_elements"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("layouts"),
        FFMPEG.C_INT.withName("nb_layouts"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("output_mix_config"),
        AVRational.layout().withName("default_mix_gain")
    ).withName("AVIAMFSubmix");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout av_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("av_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final AddressLayout av_class$layout() {
        return av_class$LAYOUT;
    }

    private static final long av_class$OFFSET = $LAYOUT.byteOffset(groupElement("av_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final long av_class$offset() {
        return av_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static MemorySegment av_class(MemorySegment struct) {
        return struct.get(av_class$LAYOUT, av_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static void av_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(av_class$LAYOUT, av_class$OFFSET, fieldValue);
    }

    private static final AddressLayout elements$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("elements"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVIAMFSubmixElement **elements
     * }
     */
    public static final AddressLayout elements$layout() {
        return elements$LAYOUT;
    }

    private static final long elements$OFFSET = $LAYOUT.byteOffset(groupElement("elements"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVIAMFSubmixElement **elements
     * }
     */
    public static final long elements$offset() {
        return elements$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVIAMFSubmixElement **elements
     * }
     */
    public static MemorySegment elements(MemorySegment struct) {
        return struct.get(elements$LAYOUT, elements$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVIAMFSubmixElement **elements
     * }
     */
    public static void elements(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(elements$LAYOUT, elements$OFFSET, fieldValue);
    }

    private static final OfInt nb_elements$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nb_elements"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int nb_elements
     * }
     */
    public static final OfInt nb_elements$layout() {
        return nb_elements$LAYOUT;
    }

    private static final long nb_elements$OFFSET = $LAYOUT.byteOffset(groupElement("nb_elements"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int nb_elements
     * }
     */
    public static final long nb_elements$offset() {
        return nb_elements$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int nb_elements
     * }
     */
    public static int nb_elements(MemorySegment struct) {
        return struct.get(nb_elements$LAYOUT, nb_elements$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int nb_elements
     * }
     */
    public static void nb_elements(MemorySegment struct, int fieldValue) {
        struct.set(nb_elements$LAYOUT, nb_elements$OFFSET, fieldValue);
    }

    private static final AddressLayout layouts$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("layouts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVIAMFSubmixLayout **layouts
     * }
     */
    public static final AddressLayout layouts$layout() {
        return layouts$LAYOUT;
    }

    private static final long layouts$OFFSET = $LAYOUT.byteOffset(groupElement("layouts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVIAMFSubmixLayout **layouts
     * }
     */
    public static final long layouts$offset() {
        return layouts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVIAMFSubmixLayout **layouts
     * }
     */
    public static MemorySegment layouts(MemorySegment struct) {
        return struct.get(layouts$LAYOUT, layouts$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVIAMFSubmixLayout **layouts
     * }
     */
    public static void layouts(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(layouts$LAYOUT, layouts$OFFSET, fieldValue);
    }

    private static final OfInt nb_layouts$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nb_layouts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int nb_layouts
     * }
     */
    public static final OfInt nb_layouts$layout() {
        return nb_layouts$LAYOUT;
    }

    private static final long nb_layouts$OFFSET = $LAYOUT.byteOffset(groupElement("nb_layouts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int nb_layouts
     * }
     */
    public static final long nb_layouts$offset() {
        return nb_layouts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int nb_layouts
     * }
     */
    public static int nb_layouts(MemorySegment struct) {
        return struct.get(nb_layouts$LAYOUT, nb_layouts$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int nb_layouts
     * }
     */
    public static void nb_layouts(MemorySegment struct, int fieldValue) {
        struct.set(nb_layouts$LAYOUT, nb_layouts$OFFSET, fieldValue);
    }

    private static final AddressLayout output_mix_config$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("output_mix_config"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *output_mix_config
     * }
     */
    public static final AddressLayout output_mix_config$layout() {
        return output_mix_config$LAYOUT;
    }

    private static final long output_mix_config$OFFSET = $LAYOUT.byteOffset(groupElement("output_mix_config"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *output_mix_config
     * }
     */
    public static final long output_mix_config$offset() {
        return output_mix_config$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *output_mix_config
     * }
     */
    public static MemorySegment output_mix_config(MemorySegment struct) {
        return struct.get(output_mix_config$LAYOUT, output_mix_config$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *output_mix_config
     * }
     */
    public static void output_mix_config(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(output_mix_config$LAYOUT, output_mix_config$OFFSET, fieldValue);
    }

    private static final GroupLayout default_mix_gain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("default_mix_gain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational default_mix_gain
     * }
     */
    public static final GroupLayout default_mix_gain$layout() {
        return default_mix_gain$LAYOUT;
    }

    private static final long default_mix_gain$OFFSET = $LAYOUT.byteOffset(groupElement("default_mix_gain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational default_mix_gain
     * }
     */
    public static final long default_mix_gain$offset() {
        return default_mix_gain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational default_mix_gain
     * }
     */
    public static MemorySegment default_mix_gain(MemorySegment struct) {
        return struct.asSlice(default_mix_gain$OFFSET, default_mix_gain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational default_mix_gain
     * }
     */
    public static void default_mix_gain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, default_mix_gain$OFFSET, default_mix_gain$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

