// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVIAMFAudioElement {
 *     const AVClass *av_class;
 *     AVIAMFLayer **layers;
 *     unsigned int nb_layers;
 *     AVIAMFParamDefinition *demixing_info;
 *     AVIAMFParamDefinition *recon_gain_info;
 *     enum AVIAMFAudioElementType audio_element_type;
 *     unsigned int default_w;
 * }
 * }
 */
public class AVIAMFAudioElement {

    AVIAMFAudioElement() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("av_class"),
        FFMPEG.C_POINTER.withName("layers"),
        FFMPEG.C_INT.withName("nb_layers"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("demixing_info"),
        FFMPEG.C_POINTER.withName("recon_gain_info"),
        FFMPEG.C_INT.withName("audio_element_type"),
        FFMPEG.C_INT.withName("default_w")
    ).withName("AVIAMFAudioElement");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout av_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("av_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final AddressLayout av_class$layout() {
        return av_class$LAYOUT;
    }

    private static final long av_class$OFFSET = $LAYOUT.byteOffset(groupElement("av_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final long av_class$offset() {
        return av_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static MemorySegment av_class(MemorySegment struct) {
        return struct.get(av_class$LAYOUT, av_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static void av_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(av_class$LAYOUT, av_class$OFFSET, fieldValue);
    }

    private static final AddressLayout layers$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("layers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVIAMFLayer **layers
     * }
     */
    public static final AddressLayout layers$layout() {
        return layers$LAYOUT;
    }

    private static final long layers$OFFSET = $LAYOUT.byteOffset(groupElement("layers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVIAMFLayer **layers
     * }
     */
    public static final long layers$offset() {
        return layers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVIAMFLayer **layers
     * }
     */
    public static MemorySegment layers(MemorySegment struct) {
        return struct.get(layers$LAYOUT, layers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVIAMFLayer **layers
     * }
     */
    public static void layers(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(layers$LAYOUT, layers$OFFSET, fieldValue);
    }

    private static final OfInt nb_layers$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nb_layers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int nb_layers
     * }
     */
    public static final OfInt nb_layers$layout() {
        return nb_layers$LAYOUT;
    }

    private static final long nb_layers$OFFSET = $LAYOUT.byteOffset(groupElement("nb_layers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int nb_layers
     * }
     */
    public static final long nb_layers$offset() {
        return nb_layers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int nb_layers
     * }
     */
    public static int nb_layers(MemorySegment struct) {
        return struct.get(nb_layers$LAYOUT, nb_layers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int nb_layers
     * }
     */
    public static void nb_layers(MemorySegment struct, int fieldValue) {
        struct.set(nb_layers$LAYOUT, nb_layers$OFFSET, fieldValue);
    }

    private static final AddressLayout demixing_info$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("demixing_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *demixing_info
     * }
     */
    public static final AddressLayout demixing_info$layout() {
        return demixing_info$LAYOUT;
    }

    private static final long demixing_info$OFFSET = $LAYOUT.byteOffset(groupElement("demixing_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *demixing_info
     * }
     */
    public static final long demixing_info$offset() {
        return demixing_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *demixing_info
     * }
     */
    public static MemorySegment demixing_info(MemorySegment struct) {
        return struct.get(demixing_info$LAYOUT, demixing_info$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *demixing_info
     * }
     */
    public static void demixing_info(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(demixing_info$LAYOUT, demixing_info$OFFSET, fieldValue);
    }

    private static final AddressLayout recon_gain_info$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("recon_gain_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *recon_gain_info
     * }
     */
    public static final AddressLayout recon_gain_info$layout() {
        return recon_gain_info$LAYOUT;
    }

    private static final long recon_gain_info$OFFSET = $LAYOUT.byteOffset(groupElement("recon_gain_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *recon_gain_info
     * }
     */
    public static final long recon_gain_info$offset() {
        return recon_gain_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *recon_gain_info
     * }
     */
    public static MemorySegment recon_gain_info(MemorySegment struct) {
        return struct.get(recon_gain_info$LAYOUT, recon_gain_info$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVIAMFParamDefinition *recon_gain_info
     * }
     */
    public static void recon_gain_info(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(recon_gain_info$LAYOUT, recon_gain_info$OFFSET, fieldValue);
    }

    private static final OfInt audio_element_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("audio_element_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVIAMFAudioElementType audio_element_type
     * }
     */
    public static final OfInt audio_element_type$layout() {
        return audio_element_type$LAYOUT;
    }

    private static final long audio_element_type$OFFSET = $LAYOUT.byteOffset(groupElement("audio_element_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVIAMFAudioElementType audio_element_type
     * }
     */
    public static final long audio_element_type$offset() {
        return audio_element_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVIAMFAudioElementType audio_element_type
     * }
     */
    public static int audio_element_type(MemorySegment struct) {
        return struct.get(audio_element_type$LAYOUT, audio_element_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVIAMFAudioElementType audio_element_type
     * }
     */
    public static void audio_element_type(MemorySegment struct, int fieldValue) {
        struct.set(audio_element_type$LAYOUT, audio_element_type$OFFSET, fieldValue);
    }

    private static final OfInt default_w$LAYOUT = (OfInt)$LAYOUT.select(groupElement("default_w"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int default_w
     * }
     */
    public static final OfInt default_w$layout() {
        return default_w$LAYOUT;
    }

    private static final long default_w$OFFSET = $LAYOUT.byteOffset(groupElement("default_w"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int default_w
     * }
     */
    public static final long default_w$offset() {
        return default_w$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int default_w
     * }
     */
    public static int default_w(MemorySegment struct) {
        return struct.get(default_w$LAYOUT, default_w$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int default_w
     * }
     */
    public static void default_w(MemorySegment struct, int fieldValue) {
        struct.set(default_w$LAYOUT, default_w$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

