// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVIAMFReconGain {
 *     const AVClass *av_class;
 *     unsigned int subblock_duration;
 *     uint8_t recon_gain[6][12];
 * }
 * }
 */
public class AVIAMFReconGain {

    AVIAMFReconGain() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("av_class"),
        FFMPEG.C_INT.withName("subblock_duration"),
        MemoryLayout.sequenceLayout(6, MemoryLayout.sequenceLayout(12, FFMPEG.C_CHAR)).withName("recon_gain"),
        MemoryLayout.paddingLayout(4)
    ).withName("AVIAMFReconGain");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout av_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("av_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final AddressLayout av_class$layout() {
        return av_class$LAYOUT;
    }

    private static final long av_class$OFFSET = $LAYOUT.byteOffset(groupElement("av_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final long av_class$offset() {
        return av_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static MemorySegment av_class(MemorySegment struct) {
        return struct.get(av_class$LAYOUT, av_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static void av_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(av_class$LAYOUT, av_class$OFFSET, fieldValue);
    }

    private static final OfInt subblock_duration$LAYOUT = (OfInt)$LAYOUT.select(groupElement("subblock_duration"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int subblock_duration
     * }
     */
    public static final OfInt subblock_duration$layout() {
        return subblock_duration$LAYOUT;
    }

    private static final long subblock_duration$OFFSET = $LAYOUT.byteOffset(groupElement("subblock_duration"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int subblock_duration
     * }
     */
    public static final long subblock_duration$offset() {
        return subblock_duration$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int subblock_duration
     * }
     */
    public static int subblock_duration(MemorySegment struct) {
        return struct.get(subblock_duration$LAYOUT, subblock_duration$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int subblock_duration
     * }
     */
    public static void subblock_duration(MemorySegment struct, int fieldValue) {
        struct.set(subblock_duration$LAYOUT, subblock_duration$OFFSET, fieldValue);
    }

    private static final SequenceLayout recon_gain$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("recon_gain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t recon_gain[6][12]
     * }
     */
    public static final SequenceLayout recon_gain$layout() {
        return recon_gain$LAYOUT;
    }

    private static final long recon_gain$OFFSET = $LAYOUT.byteOffset(groupElement("recon_gain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t recon_gain[6][12]
     * }
     */
    public static final long recon_gain$offset() {
        return recon_gain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t recon_gain[6][12]
     * }
     */
    public static MemorySegment recon_gain(MemorySegment struct) {
        return struct.asSlice(recon_gain$OFFSET, recon_gain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t recon_gain[6][12]
     * }
     */
    public static void recon_gain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, recon_gain$OFFSET, recon_gain$LAYOUT.byteSize());
    }

    private static long[] recon_gain$DIMS = { 6, 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t recon_gain[6][12]
     * }
     */
    public static long[] recon_gain$dimensions() {
        return recon_gain$DIMS;
    }
    private static final VarHandle recon_gain$ELEM_HANDLE = recon_gain$LAYOUT.varHandle(sequenceElement(), sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t recon_gain[6][12]
     * }
     */
    public static byte recon_gain(MemorySegment struct, long index0, long index1) {
        return (byte)recon_gain$ELEM_HANDLE.get(struct, 0L, index0, index1);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t recon_gain[6][12]
     * }
     */
    public static void recon_gain(MemorySegment struct, long index0, long index1, byte fieldValue) {
        recon_gain$ELEM_HANDLE.set(struct, 0L, index0, index1, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

