// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVIAMFParamDefinition {
 *     const AVClass *av_class;
 *     size_t subblocks_offset;
 *     size_t subblock_size;
 *     unsigned int nb_subblocks;
 *     enum AVIAMFParamDefinitionType type;
 *     unsigned int parameter_id;
 *     unsigned int parameter_rate;
 *     unsigned int duration;
 *     unsigned int constant_subblock_duration;
 * }
 * }
 */
public class AVIAMFParamDefinition {

    AVIAMFParamDefinition() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("av_class"),
        FFMPEG.C_LONG.withName("subblocks_offset"),
        FFMPEG.C_LONG.withName("subblock_size"),
        FFMPEG.C_INT.withName("nb_subblocks"),
        FFMPEG.C_INT.withName("type"),
        FFMPEG.C_INT.withName("parameter_id"),
        FFMPEG.C_INT.withName("parameter_rate"),
        FFMPEG.C_INT.withName("duration"),
        FFMPEG.C_INT.withName("constant_subblock_duration")
    ).withName("AVIAMFParamDefinition");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout av_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("av_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final AddressLayout av_class$layout() {
        return av_class$LAYOUT;
    }

    private static final long av_class$OFFSET = $LAYOUT.byteOffset(groupElement("av_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final long av_class$offset() {
        return av_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static MemorySegment av_class(MemorySegment struct) {
        return struct.get(av_class$LAYOUT, av_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static void av_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(av_class$LAYOUT, av_class$OFFSET, fieldValue);
    }

    private static final OfLong subblocks_offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("subblocks_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t subblocks_offset
     * }
     */
    public static final OfLong subblocks_offset$layout() {
        return subblocks_offset$LAYOUT;
    }

    private static final long subblocks_offset$OFFSET = $LAYOUT.byteOffset(groupElement("subblocks_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t subblocks_offset
     * }
     */
    public static final long subblocks_offset$offset() {
        return subblocks_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t subblocks_offset
     * }
     */
    public static long subblocks_offset(MemorySegment struct) {
        return struct.get(subblocks_offset$LAYOUT, subblocks_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t subblocks_offset
     * }
     */
    public static void subblocks_offset(MemorySegment struct, long fieldValue) {
        struct.set(subblocks_offset$LAYOUT, subblocks_offset$OFFSET, fieldValue);
    }

    private static final OfLong subblock_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("subblock_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t subblock_size
     * }
     */
    public static final OfLong subblock_size$layout() {
        return subblock_size$LAYOUT;
    }

    private static final long subblock_size$OFFSET = $LAYOUT.byteOffset(groupElement("subblock_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t subblock_size
     * }
     */
    public static final long subblock_size$offset() {
        return subblock_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t subblock_size
     * }
     */
    public static long subblock_size(MemorySegment struct) {
        return struct.get(subblock_size$LAYOUT, subblock_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t subblock_size
     * }
     */
    public static void subblock_size(MemorySegment struct, long fieldValue) {
        struct.set(subblock_size$LAYOUT, subblock_size$OFFSET, fieldValue);
    }

    private static final OfInt nb_subblocks$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nb_subblocks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int nb_subblocks
     * }
     */
    public static final OfInt nb_subblocks$layout() {
        return nb_subblocks$LAYOUT;
    }

    private static final long nb_subblocks$OFFSET = $LAYOUT.byteOffset(groupElement("nb_subblocks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int nb_subblocks
     * }
     */
    public static final long nb_subblocks$offset() {
        return nb_subblocks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int nb_subblocks
     * }
     */
    public static int nb_subblocks(MemorySegment struct) {
        return struct.get(nb_subblocks$LAYOUT, nb_subblocks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int nb_subblocks
     * }
     */
    public static void nb_subblocks(MemorySegment struct, int fieldValue) {
        struct.set(nb_subblocks$LAYOUT, nb_subblocks$OFFSET, fieldValue);
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVIAMFParamDefinitionType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVIAMFParamDefinitionType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVIAMFParamDefinitionType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVIAMFParamDefinitionType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfInt parameter_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("parameter_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int parameter_id
     * }
     */
    public static final OfInt parameter_id$layout() {
        return parameter_id$LAYOUT;
    }

    private static final long parameter_id$OFFSET = $LAYOUT.byteOffset(groupElement("parameter_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int parameter_id
     * }
     */
    public static final long parameter_id$offset() {
        return parameter_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int parameter_id
     * }
     */
    public static int parameter_id(MemorySegment struct) {
        return struct.get(parameter_id$LAYOUT, parameter_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int parameter_id
     * }
     */
    public static void parameter_id(MemorySegment struct, int fieldValue) {
        struct.set(parameter_id$LAYOUT, parameter_id$OFFSET, fieldValue);
    }

    private static final OfInt parameter_rate$LAYOUT = (OfInt)$LAYOUT.select(groupElement("parameter_rate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int parameter_rate
     * }
     */
    public static final OfInt parameter_rate$layout() {
        return parameter_rate$LAYOUT;
    }

    private static final long parameter_rate$OFFSET = $LAYOUT.byteOffset(groupElement("parameter_rate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int parameter_rate
     * }
     */
    public static final long parameter_rate$offset() {
        return parameter_rate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int parameter_rate
     * }
     */
    public static int parameter_rate(MemorySegment struct) {
        return struct.get(parameter_rate$LAYOUT, parameter_rate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int parameter_rate
     * }
     */
    public static void parameter_rate(MemorySegment struct, int fieldValue) {
        struct.set(parameter_rate$LAYOUT, parameter_rate$OFFSET, fieldValue);
    }

    private static final OfInt duration$LAYOUT = (OfInt)$LAYOUT.select(groupElement("duration"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int duration
     * }
     */
    public static final OfInt duration$layout() {
        return duration$LAYOUT;
    }

    private static final long duration$OFFSET = $LAYOUT.byteOffset(groupElement("duration"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int duration
     * }
     */
    public static final long duration$offset() {
        return duration$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int duration
     * }
     */
    public static int duration(MemorySegment struct) {
        return struct.get(duration$LAYOUT, duration$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int duration
     * }
     */
    public static void duration(MemorySegment struct, int fieldValue) {
        struct.set(duration$LAYOUT, duration$OFFSET, fieldValue);
    }

    private static final OfInt constant_subblock_duration$LAYOUT = (OfInt)$LAYOUT.select(groupElement("constant_subblock_duration"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int constant_subblock_duration
     * }
     */
    public static final OfInt constant_subblock_duration$layout() {
        return constant_subblock_duration$LAYOUT;
    }

    private static final long constant_subblock_duration$OFFSET = $LAYOUT.byteOffset(groupElement("constant_subblock_duration"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int constant_subblock_duration
     * }
     */
    public static final long constant_subblock_duration$offset() {
        return constant_subblock_duration$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int constant_subblock_duration
     * }
     */
    public static int constant_subblock_duration(MemorySegment struct) {
        return struct.get(constant_subblock_duration$LAYOUT, constant_subblock_duration$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int constant_subblock_duration
     * }
     */
    public static void constant_subblock_duration(MemorySegment struct, int fieldValue) {
        struct.set(constant_subblock_duration$LAYOUT, constant_subblock_duration$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

