// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVIAMFLayer {
 *     const AVClass *av_class;
 *     AVChannelLayout ch_layout;
 *     unsigned int flags;
 *     unsigned int output_gain_flags;
 *     AVRational output_gain;
 *     enum AVIAMFAmbisonicsMode ambisonics_mode;
 *     AVRational *demixing_matrix;
 *     unsigned int nb_demixing_matrix;
 * }
 * }
 */
public class AVIAMFLayer {

    AVIAMFLayer() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("av_class"),
        AVChannelLayout.layout().withName("ch_layout"),
        FFMPEG.C_INT.withName("flags"),
        FFMPEG.C_INT.withName("output_gain_flags"),
        AVRational.layout().withName("output_gain"),
        FFMPEG.C_INT.withName("ambisonics_mode"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("demixing_matrix"),
        FFMPEG.C_INT.withName("nb_demixing_matrix"),
        MemoryLayout.paddingLayout(4)
    ).withName("AVIAMFLayer");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout av_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("av_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final AddressLayout av_class$layout() {
        return av_class$LAYOUT;
    }

    private static final long av_class$OFFSET = $LAYOUT.byteOffset(groupElement("av_class"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static final long av_class$offset() {
        return av_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static MemorySegment av_class(MemorySegment struct) {
        return struct.get(av_class$LAYOUT, av_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *av_class
     * }
     */
    public static void av_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(av_class$LAYOUT, av_class$OFFSET, fieldValue);
    }

    private static final GroupLayout ch_layout$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ch_layout"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVChannelLayout ch_layout
     * }
     */
    public static final GroupLayout ch_layout$layout() {
        return ch_layout$LAYOUT;
    }

    private static final long ch_layout$OFFSET = $LAYOUT.byteOffset(groupElement("ch_layout"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVChannelLayout ch_layout
     * }
     */
    public static final long ch_layout$offset() {
        return ch_layout$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVChannelLayout ch_layout
     * }
     */
    public static MemorySegment ch_layout(MemorySegment struct) {
        return struct.asSlice(ch_layout$OFFSET, ch_layout$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVChannelLayout ch_layout
     * }
     */
    public static void ch_layout(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ch_layout$OFFSET, ch_layout$LAYOUT.byteSize());
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfInt output_gain_flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("output_gain_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int output_gain_flags
     * }
     */
    public static final OfInt output_gain_flags$layout() {
        return output_gain_flags$LAYOUT;
    }

    private static final long output_gain_flags$OFFSET = $LAYOUT.byteOffset(groupElement("output_gain_flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int output_gain_flags
     * }
     */
    public static final long output_gain_flags$offset() {
        return output_gain_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int output_gain_flags
     * }
     */
    public static int output_gain_flags(MemorySegment struct) {
        return struct.get(output_gain_flags$LAYOUT, output_gain_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int output_gain_flags
     * }
     */
    public static void output_gain_flags(MemorySegment struct, int fieldValue) {
        struct.set(output_gain_flags$LAYOUT, output_gain_flags$OFFSET, fieldValue);
    }

    private static final GroupLayout output_gain$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("output_gain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational output_gain
     * }
     */
    public static final GroupLayout output_gain$layout() {
        return output_gain$LAYOUT;
    }

    private static final long output_gain$OFFSET = $LAYOUT.byteOffset(groupElement("output_gain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational output_gain
     * }
     */
    public static final long output_gain$offset() {
        return output_gain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational output_gain
     * }
     */
    public static MemorySegment output_gain(MemorySegment struct) {
        return struct.asSlice(output_gain$OFFSET, output_gain$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational output_gain
     * }
     */
    public static void output_gain(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, output_gain$OFFSET, output_gain$LAYOUT.byteSize());
    }

    private static final OfInt ambisonics_mode$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ambisonics_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVIAMFAmbisonicsMode ambisonics_mode
     * }
     */
    public static final OfInt ambisonics_mode$layout() {
        return ambisonics_mode$LAYOUT;
    }

    private static final long ambisonics_mode$OFFSET = $LAYOUT.byteOffset(groupElement("ambisonics_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVIAMFAmbisonicsMode ambisonics_mode
     * }
     */
    public static final long ambisonics_mode$offset() {
        return ambisonics_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVIAMFAmbisonicsMode ambisonics_mode
     * }
     */
    public static int ambisonics_mode(MemorySegment struct) {
        return struct.get(ambisonics_mode$LAYOUT, ambisonics_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVIAMFAmbisonicsMode ambisonics_mode
     * }
     */
    public static void ambisonics_mode(MemorySegment struct, int fieldValue) {
        struct.set(ambisonics_mode$LAYOUT, ambisonics_mode$OFFSET, fieldValue);
    }

    private static final AddressLayout demixing_matrix$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("demixing_matrix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational *demixing_matrix
     * }
     */
    public static final AddressLayout demixing_matrix$layout() {
        return demixing_matrix$LAYOUT;
    }

    private static final long demixing_matrix$OFFSET = $LAYOUT.byteOffset(groupElement("demixing_matrix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational *demixing_matrix
     * }
     */
    public static final long demixing_matrix$offset() {
        return demixing_matrix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational *demixing_matrix
     * }
     */
    public static MemorySegment demixing_matrix(MemorySegment struct) {
        return struct.get(demixing_matrix$LAYOUT, demixing_matrix$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational *demixing_matrix
     * }
     */
    public static void demixing_matrix(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(demixing_matrix$LAYOUT, demixing_matrix$OFFSET, fieldValue);
    }

    private static final OfInt nb_demixing_matrix$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nb_demixing_matrix"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int nb_demixing_matrix
     * }
     */
    public static final OfInt nb_demixing_matrix$layout() {
        return nb_demixing_matrix$LAYOUT;
    }

    private static final long nb_demixing_matrix$OFFSET = $LAYOUT.byteOffset(groupElement("nb_demixing_matrix"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int nb_demixing_matrix
     * }
     */
    public static final long nb_demixing_matrix$offset() {
        return nb_demixing_matrix$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int nb_demixing_matrix
     * }
     */
    public static int nb_demixing_matrix(MemorySegment struct) {
        return struct.get(nb_demixing_matrix$LAYOUT, nb_demixing_matrix$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int nb_demixing_matrix
     * }
     */
    public static void nb_demixing_matrix(MemorySegment struct, int fieldValue) {
        struct.set(nb_demixing_matrix$LAYOUT, nb_demixing_matrix$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

