// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVLumaCoefficients {
 *     AVRational cr;
 *     AVRational cg;
 *     AVRational cb;
 * }
 * }
 */
public class AVLumaCoefficients {

    AVLumaCoefficients() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        AVRational.layout().withName("cr"),
        AVRational.layout().withName("cg"),
        AVRational.layout().withName("cb")
    ).withName("AVLumaCoefficients");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout cr$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("cr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational cr
     * }
     */
    public static final GroupLayout cr$layout() {
        return cr$LAYOUT;
    }

    private static final long cr$OFFSET = $LAYOUT.byteOffset(groupElement("cr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational cr
     * }
     */
    public static final long cr$offset() {
        return cr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational cr
     * }
     */
    public static MemorySegment cr(MemorySegment struct) {
        return struct.asSlice(cr$OFFSET, cr$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational cr
     * }
     */
    public static void cr(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, cr$OFFSET, cr$LAYOUT.byteSize());
    }

    private static final GroupLayout cg$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("cg"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational cg
     * }
     */
    public static final GroupLayout cg$layout() {
        return cg$LAYOUT;
    }

    private static final long cg$OFFSET = $LAYOUT.byteOffset(groupElement("cg"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational cg
     * }
     */
    public static final long cg$offset() {
        return cg$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational cg
     * }
     */
    public static MemorySegment cg(MemorySegment struct) {
        return struct.asSlice(cg$OFFSET, cg$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational cg
     * }
     */
    public static void cg(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, cg$OFFSET, cg$LAYOUT.byteSize());
    }

    private static final GroupLayout cb$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("cb"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVRational cb
     * }
     */
    public static final GroupLayout cb$layout() {
        return cb$LAYOUT;
    }

    private static final long cb$OFFSET = $LAYOUT.byteOffset(groupElement("cb"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVRational cb
     * }
     */
    public static final long cb$offset() {
        return cb$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVRational cb
     * }
     */
    public static MemorySegment cb(MemorySegment struct) {
        return struct.asSlice(cb$OFFSET, cb$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVRational cb
     * }
     */
    public static void cb(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, cb$OFFSET, cb$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

