// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVReplayGain {
 *     int32_t track_gain;
 *     uint32_t track_peak;
 *     int32_t album_gain;
 *     uint32_t album_peak;
 * }
 * }
 */
public class AVReplayGain {

    AVReplayGain() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_INT.withName("track_gain"),
        FFMPEG.C_INT.withName("track_peak"),
        FFMPEG.C_INT.withName("album_gain"),
        FFMPEG.C_INT.withName("album_peak")
    ).withName("AVReplayGain");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt track_gain$LAYOUT = (OfInt)$LAYOUT.select(groupElement("track_gain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t track_gain
     * }
     */
    public static final OfInt track_gain$layout() {
        return track_gain$LAYOUT;
    }

    private static final long track_gain$OFFSET = $LAYOUT.byteOffset(groupElement("track_gain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t track_gain
     * }
     */
    public static final long track_gain$offset() {
        return track_gain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t track_gain
     * }
     */
    public static int track_gain(MemorySegment struct) {
        return struct.get(track_gain$LAYOUT, track_gain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t track_gain
     * }
     */
    public static void track_gain(MemorySegment struct, int fieldValue) {
        struct.set(track_gain$LAYOUT, track_gain$OFFSET, fieldValue);
    }

    private static final OfInt track_peak$LAYOUT = (OfInt)$LAYOUT.select(groupElement("track_peak"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t track_peak
     * }
     */
    public static final OfInt track_peak$layout() {
        return track_peak$LAYOUT;
    }

    private static final long track_peak$OFFSET = $LAYOUT.byteOffset(groupElement("track_peak"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t track_peak
     * }
     */
    public static final long track_peak$offset() {
        return track_peak$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t track_peak
     * }
     */
    public static int track_peak(MemorySegment struct) {
        return struct.get(track_peak$LAYOUT, track_peak$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t track_peak
     * }
     */
    public static void track_peak(MemorySegment struct, int fieldValue) {
        struct.set(track_peak$LAYOUT, track_peak$OFFSET, fieldValue);
    }

    private static final OfInt album_gain$LAYOUT = (OfInt)$LAYOUT.select(groupElement("album_gain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t album_gain
     * }
     */
    public static final OfInt album_gain$layout() {
        return album_gain$LAYOUT;
    }

    private static final long album_gain$OFFSET = $LAYOUT.byteOffset(groupElement("album_gain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t album_gain
     * }
     */
    public static final long album_gain$offset() {
        return album_gain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t album_gain
     * }
     */
    public static int album_gain(MemorySegment struct) {
        return struct.get(album_gain$LAYOUT, album_gain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t album_gain
     * }
     */
    public static void album_gain(MemorySegment struct, int fieldValue) {
        struct.set(album_gain$LAYOUT, album_gain$OFFSET, fieldValue);
    }

    private static final OfInt album_peak$LAYOUT = (OfInt)$LAYOUT.select(groupElement("album_peak"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t album_peak
     * }
     */
    public static final OfInt album_peak$layout() {
        return album_peak$LAYOUT;
    }

    private static final long album_peak$OFFSET = $LAYOUT.byteOffset(groupElement("album_peak"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t album_peak
     * }
     */
    public static final long album_peak$offset() {
        return album_peak$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t album_peak
     * }
     */
    public static int album_peak(MemorySegment struct) {
        return struct.get(album_peak$LAYOUT, album_peak$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t album_peak
     * }
     */
    public static void album_peak(MemorySegment struct, int fieldValue) {
        struct.set(album_peak$LAYOUT, album_peak$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

