// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVRTSPResponse {
 *     int status_code;
 *     char *reason;
 *     size_t body_len;
 *     unsigned char *body;
 * }
 * }
 */
public class AVRTSPResponse {

    AVRTSPResponse() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_INT.withName("status_code"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("reason"),
        FFMPEG.C_LONG.withName("body_len"),
        FFMPEG.C_POINTER.withName("body")
    ).withName("AVRTSPResponse");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt status_code$LAYOUT = (OfInt)$LAYOUT.select(groupElement("status_code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int status_code
     * }
     */
    public static final OfInt status_code$layout() {
        return status_code$LAYOUT;
    }

    private static final long status_code$OFFSET = $LAYOUT.byteOffset(groupElement("status_code"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int status_code
     * }
     */
    public static final long status_code$offset() {
        return status_code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int status_code
     * }
     */
    public static int status_code(MemorySegment struct) {
        return struct.get(status_code$LAYOUT, status_code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int status_code
     * }
     */
    public static void status_code(MemorySegment struct, int fieldValue) {
        struct.set(status_code$LAYOUT, status_code$OFFSET, fieldValue);
    }

    private static final AddressLayout reason$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("reason"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *reason
     * }
     */
    public static final AddressLayout reason$layout() {
        return reason$LAYOUT;
    }

    private static final long reason$OFFSET = $LAYOUT.byteOffset(groupElement("reason"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *reason
     * }
     */
    public static final long reason$offset() {
        return reason$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *reason
     * }
     */
    public static MemorySegment reason(MemorySegment struct) {
        return struct.get(reason$LAYOUT, reason$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *reason
     * }
     */
    public static void reason(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(reason$LAYOUT, reason$OFFSET, fieldValue);
    }

    private static final OfLong body_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("body_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t body_len
     * }
     */
    public static final OfLong body_len$layout() {
        return body_len$LAYOUT;
    }

    private static final long body_len$OFFSET = $LAYOUT.byteOffset(groupElement("body_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t body_len
     * }
     */
    public static final long body_len$offset() {
        return body_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t body_len
     * }
     */
    public static long body_len(MemorySegment struct) {
        return struct.get(body_len$LAYOUT, body_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t body_len
     * }
     */
    public static void body_len(MemorySegment struct, long fieldValue) {
        struct.set(body_len$LAYOUT, body_len$OFFSET, fieldValue);
    }

    private static final AddressLayout body$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("body"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *body
     * }
     */
    public static final AddressLayout body$layout() {
        return body$LAYOUT;
    }

    private static final long body$OFFSET = $LAYOUT.byteOffset(groupElement("body"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *body
     * }
     */
    public static final long body$offset() {
        return body$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *body
     * }
     */
    public static MemorySegment body(MemorySegment struct) {
        return struct.get(body$LAYOUT, body$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *body
     * }
     */
    public static void body(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(body$LAYOUT, body$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

