// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVSubsampleEncryptionInfo {
 *     unsigned int bytes_of_clear_data;
 *     unsigned int bytes_of_protected_data;
 * }
 * }
 */
public class AVSubsampleEncryptionInfo {

    AVSubsampleEncryptionInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_INT.withName("bytes_of_clear_data"),
        FFMPEG.C_INT.withName("bytes_of_protected_data")
    ).withName("AVSubsampleEncryptionInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt bytes_of_clear_data$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bytes_of_clear_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int bytes_of_clear_data
     * }
     */
    public static final OfInt bytes_of_clear_data$layout() {
        return bytes_of_clear_data$LAYOUT;
    }

    private static final long bytes_of_clear_data$OFFSET = $LAYOUT.byteOffset(groupElement("bytes_of_clear_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int bytes_of_clear_data
     * }
     */
    public static final long bytes_of_clear_data$offset() {
        return bytes_of_clear_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int bytes_of_clear_data
     * }
     */
    public static int bytes_of_clear_data(MemorySegment struct) {
        return struct.get(bytes_of_clear_data$LAYOUT, bytes_of_clear_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int bytes_of_clear_data
     * }
     */
    public static void bytes_of_clear_data(MemorySegment struct, int fieldValue) {
        struct.set(bytes_of_clear_data$LAYOUT, bytes_of_clear_data$OFFSET, fieldValue);
    }

    private static final OfInt bytes_of_protected_data$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bytes_of_protected_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int bytes_of_protected_data
     * }
     */
    public static final OfInt bytes_of_protected_data$layout() {
        return bytes_of_protected_data$LAYOUT;
    }

    private static final long bytes_of_protected_data$OFFSET = $LAYOUT.byteOffset(groupElement("bytes_of_protected_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int bytes_of_protected_data
     * }
     */
    public static final long bytes_of_protected_data$offset() {
        return bytes_of_protected_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int bytes_of_protected_data
     * }
     */
    public static int bytes_of_protected_data(MemorySegment struct) {
        return struct.get(bytes_of_protected_data$LAYOUT, bytes_of_protected_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int bytes_of_protected_data
     * }
     */
    public static void bytes_of_protected_data(MemorySegment struct, int fieldValue) {
        struct.set(bytes_of_protected_data$LAYOUT, bytes_of_protected_data$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

