// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVTaskCallbacks {
 *     void *user_data;
 *     int local_context_size;
 *     int (*priority_higher)(const AVTask *, const AVTask *);
 *     int (*ready)(const AVTask *, void *);
 *     int (*run)(AVTask *, void *, void *);
 * }
 * }
 */
public class AVTaskCallbacks {

    AVTaskCallbacks() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_POINTER.withName("user_data"),
        FFMPEG.C_INT.withName("local_context_size"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_POINTER.withName("priority_higher"),
        FFMPEG.C_POINTER.withName("ready"),
        FFMPEG.C_POINTER.withName("run")
    ).withName("AVTaskCallbacks");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout user_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final AddressLayout user_data$layout() {
        return user_data$LAYOUT;
    }

    private static final long user_data$OFFSET = $LAYOUT.byteOffset(groupElement("user_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static final long user_data$offset() {
        return user_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static MemorySegment user_data(MemorySegment struct) {
        return struct.get(user_data$LAYOUT, user_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *user_data
     * }
     */
    public static void user_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_data$LAYOUT, user_data$OFFSET, fieldValue);
    }

    private static final OfInt local_context_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("local_context_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int local_context_size
     * }
     */
    public static final OfInt local_context_size$layout() {
        return local_context_size$LAYOUT;
    }

    private static final long local_context_size$OFFSET = $LAYOUT.byteOffset(groupElement("local_context_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int local_context_size
     * }
     */
    public static final long local_context_size$offset() {
        return local_context_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int local_context_size
     * }
     */
    public static int local_context_size(MemorySegment struct) {
        return struct.get(local_context_size$LAYOUT, local_context_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int local_context_size
     * }
     */
    public static void local_context_size(MemorySegment struct, int fieldValue) {
        struct.set(local_context_size$LAYOUT, local_context_size$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*priority_higher)(const AVTask *, const AVTask *)
     * }
     */
    public final static class priority_higher {

        private priority_higher() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            FFMPEG.C_INT,
            FFMPEG.C_POINTER,
            FFMPEG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = FFMPEG.upcallHandle(priority_higher.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(priority_higher.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout priority_higher$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("priority_higher"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*priority_higher)(const AVTask *, const AVTask *)
     * }
     */
    public static final AddressLayout priority_higher$layout() {
        return priority_higher$LAYOUT;
    }

    private static final long priority_higher$OFFSET = $LAYOUT.byteOffset(groupElement("priority_higher"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*priority_higher)(const AVTask *, const AVTask *)
     * }
     */
    public static final long priority_higher$offset() {
        return priority_higher$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*priority_higher)(const AVTask *, const AVTask *)
     * }
     */
    public static MemorySegment priority_higher(MemorySegment struct) {
        return struct.get(priority_higher$LAYOUT, priority_higher$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*priority_higher)(const AVTask *, const AVTask *)
     * }
     */
    public static void priority_higher(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(priority_higher$LAYOUT, priority_higher$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*ready)(const AVTask *, void *)
     * }
     */
    public final static class ready {

        private ready() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            FFMPEG.C_INT,
            FFMPEG.C_POINTER,
            FFMPEG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = FFMPEG.upcallHandle(ready.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(ready.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout ready$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ready"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*ready)(const AVTask *, void *)
     * }
     */
    public static final AddressLayout ready$layout() {
        return ready$LAYOUT;
    }

    private static final long ready$OFFSET = $LAYOUT.byteOffset(groupElement("ready"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*ready)(const AVTask *, void *)
     * }
     */
    public static final long ready$offset() {
        return ready$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*ready)(const AVTask *, void *)
     * }
     */
    public static MemorySegment ready(MemorySegment struct) {
        return struct.get(ready$LAYOUT, ready$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*ready)(const AVTask *, void *)
     * }
     */
    public static void ready(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ready$LAYOUT, ready$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*run)(AVTask *, void *, void *)
     * }
     */
    public final static class run {

        private run() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            FFMPEG.C_INT,
            FFMPEG.C_POINTER,
            FFMPEG.C_POINTER,
            FFMPEG.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = FFMPEG.upcallHandle(run.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(run.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr, MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Error | RuntimeException ex) {
                throw ex;
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout run$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("run"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*run)(AVTask *, void *, void *)
     * }
     */
    public static final AddressLayout run$layout() {
        return run$LAYOUT;
    }

    private static final long run$OFFSET = $LAYOUT.byteOffset(groupElement("run"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*run)(AVTask *, void *, void *)
     * }
     */
    public static final long run$offset() {
        return run$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*run)(AVTask *, void *, void *)
     * }
     */
    public static MemorySegment run(MemorySegment struct) {
        return struct.get(run$LAYOUT, run$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*run)(AVTask *, void *, void *)
     * }
     */
    public static void run(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(run$LAYOUT, run$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

