// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVVideoEncParams {
 *     unsigned int nb_blocks;
 *     size_t blocks_offset;
 *     size_t block_size;
 *     enum AVVideoEncParamsType type;
 *     int32_t qp;
 *     int32_t delta_qp[4][2];
 * }
 * }
 */
public class AVVideoEncParams {

    AVVideoEncParams() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_INT.withName("nb_blocks"),
        MemoryLayout.paddingLayout(4),
        FFMPEG.C_LONG.withName("blocks_offset"),
        FFMPEG.C_LONG.withName("block_size"),
        FFMPEG.C_INT.withName("type"),
        FFMPEG.C_INT.withName("qp"),
        MemoryLayout.sequenceLayout(4, MemoryLayout.sequenceLayout(2, FFMPEG.C_INT)).withName("delta_qp")
    ).withName("AVVideoEncParams");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt nb_blocks$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nb_blocks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int nb_blocks
     * }
     */
    public static final OfInt nb_blocks$layout() {
        return nb_blocks$LAYOUT;
    }

    private static final long nb_blocks$OFFSET = $LAYOUT.byteOffset(groupElement("nb_blocks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int nb_blocks
     * }
     */
    public static final long nb_blocks$offset() {
        return nb_blocks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int nb_blocks
     * }
     */
    public static int nb_blocks(MemorySegment struct) {
        return struct.get(nb_blocks$LAYOUT, nb_blocks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int nb_blocks
     * }
     */
    public static void nb_blocks(MemorySegment struct, int fieldValue) {
        struct.set(nb_blocks$LAYOUT, nb_blocks$OFFSET, fieldValue);
    }

    private static final OfLong blocks_offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("blocks_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t blocks_offset
     * }
     */
    public static final OfLong blocks_offset$layout() {
        return blocks_offset$LAYOUT;
    }

    private static final long blocks_offset$OFFSET = $LAYOUT.byteOffset(groupElement("blocks_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t blocks_offset
     * }
     */
    public static final long blocks_offset$offset() {
        return blocks_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t blocks_offset
     * }
     */
    public static long blocks_offset(MemorySegment struct) {
        return struct.get(blocks_offset$LAYOUT, blocks_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t blocks_offset
     * }
     */
    public static void blocks_offset(MemorySegment struct, long fieldValue) {
        struct.set(blocks_offset$LAYOUT, blocks_offset$OFFSET, fieldValue);
    }

    private static final OfLong block_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("block_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t block_size
     * }
     */
    public static final OfLong block_size$layout() {
        return block_size$LAYOUT;
    }

    private static final long block_size$OFFSET = $LAYOUT.byteOffset(groupElement("block_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t block_size
     * }
     */
    public static final long block_size$offset() {
        return block_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t block_size
     * }
     */
    public static long block_size(MemorySegment struct) {
        return struct.get(block_size$LAYOUT, block_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t block_size
     * }
     */
    public static void block_size(MemorySegment struct, long fieldValue) {
        struct.set(block_size$LAYOUT, block_size$OFFSET, fieldValue);
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum AVVideoEncParamsType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum AVVideoEncParamsType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum AVVideoEncParamsType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum AVVideoEncParamsType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfInt qp$LAYOUT = (OfInt)$LAYOUT.select(groupElement("qp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t qp
     * }
     */
    public static final OfInt qp$layout() {
        return qp$LAYOUT;
    }

    private static final long qp$OFFSET = $LAYOUT.byteOffset(groupElement("qp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t qp
     * }
     */
    public static final long qp$offset() {
        return qp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t qp
     * }
     */
    public static int qp(MemorySegment struct) {
        return struct.get(qp$LAYOUT, qp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t qp
     * }
     */
    public static void qp(MemorySegment struct, int fieldValue) {
        struct.set(qp$LAYOUT, qp$OFFSET, fieldValue);
    }

    private static final SequenceLayout delta_qp$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("delta_qp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t delta_qp[4][2]
     * }
     */
    public static final SequenceLayout delta_qp$layout() {
        return delta_qp$LAYOUT;
    }

    private static final long delta_qp$OFFSET = $LAYOUT.byteOffset(groupElement("delta_qp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t delta_qp[4][2]
     * }
     */
    public static final long delta_qp$offset() {
        return delta_qp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t delta_qp[4][2]
     * }
     */
    public static MemorySegment delta_qp(MemorySegment struct) {
        return struct.asSlice(delta_qp$OFFSET, delta_qp$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t delta_qp[4][2]
     * }
     */
    public static void delta_qp(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, delta_qp$OFFSET, delta_qp$LAYOUT.byteSize());
    }

    private static long[] delta_qp$DIMS = { 4, 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int32_t delta_qp[4][2]
     * }
     */
    public static long[] delta_qp$dimensions() {
        return delta_qp$DIMS;
    }
    private static final VarHandle delta_qp$ELEM_HANDLE = delta_qp$LAYOUT.varHandle(sequenceElement(), sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int32_t delta_qp[4][2]
     * }
     */
    public static int delta_qp(MemorySegment struct, long index0, long index1) {
        return (int)delta_qp$ELEM_HANDLE.get(struct, 0L, index0, index1);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int32_t delta_qp[4][2]
     * }
     */
    public static void delta_qp(MemorySegment struct, long index0, long index1, int fieldValue) {
        delta_qp$ELEM_HANDLE.set(struct, 0L, index0, index1, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

