// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVVideoHint {
 *     size_t nb_rects;
 *     size_t rect_offset;
 *     size_t rect_size;
 *     AVVideoHintType type;
 * }
 * }
 */
public class AVVideoHint {

    AVVideoHint() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_LONG.withName("nb_rects"),
        FFMPEG.C_LONG.withName("rect_offset"),
        FFMPEG.C_LONG.withName("rect_size"),
        FFMPEG.C_INT.withName("type"),
        MemoryLayout.paddingLayout(4)
    ).withName("AVVideoHint");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong nb_rects$LAYOUT = (OfLong)$LAYOUT.select(groupElement("nb_rects"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t nb_rects
     * }
     */
    public static final OfLong nb_rects$layout() {
        return nb_rects$LAYOUT;
    }

    private static final long nb_rects$OFFSET = $LAYOUT.byteOffset(groupElement("nb_rects"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t nb_rects
     * }
     */
    public static final long nb_rects$offset() {
        return nb_rects$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t nb_rects
     * }
     */
    public static long nb_rects(MemorySegment struct) {
        return struct.get(nb_rects$LAYOUT, nb_rects$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t nb_rects
     * }
     */
    public static void nb_rects(MemorySegment struct, long fieldValue) {
        struct.set(nb_rects$LAYOUT, nb_rects$OFFSET, fieldValue);
    }

    private static final OfLong rect_offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("rect_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t rect_offset
     * }
     */
    public static final OfLong rect_offset$layout() {
        return rect_offset$LAYOUT;
    }

    private static final long rect_offset$OFFSET = $LAYOUT.byteOffset(groupElement("rect_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t rect_offset
     * }
     */
    public static final long rect_offset$offset() {
        return rect_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t rect_offset
     * }
     */
    public static long rect_offset(MemorySegment struct) {
        return struct.get(rect_offset$LAYOUT, rect_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t rect_offset
     * }
     */
    public static void rect_offset(MemorySegment struct, long fieldValue) {
        struct.set(rect_offset$LAYOUT, rect_offset$OFFSET, fieldValue);
    }

    private static final OfLong rect_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("rect_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t rect_size
     * }
     */
    public static final OfLong rect_size$layout() {
        return rect_size$LAYOUT;
    }

    private static final long rect_size$OFFSET = $LAYOUT.byteOffset(groupElement("rect_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t rect_size
     * }
     */
    public static final long rect_size$offset() {
        return rect_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t rect_size
     * }
     */
    public static long rect_size(MemorySegment struct) {
        return struct.get(rect_size$LAYOUT, rect_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t rect_size
     * }
     */
    public static void rect_size(MemorySegment struct, long fieldValue) {
        struct.set(rect_size$LAYOUT, rect_size$OFFSET, fieldValue);
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVVideoHintType type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVVideoHintType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVVideoHintType type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVVideoHintType type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

