// Generated by jextract

package org.ffmpeg.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVVideoBlockParams {
 *     int src_x;
 *     int src_y;
 *     int w;
 *     int h;
 *     int32_t delta_qp;
 * }
 * }
 */
public class AVVideoBlockParams {

    AVVideoBlockParams() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FFMPEG.C_INT.withName("src_x"),
        FFMPEG.C_INT.withName("src_y"),
        FFMPEG.C_INT.withName("w"),
        FFMPEG.C_INT.withName("h"),
        FFMPEG.C_INT.withName("delta_qp")
    ).withName("AVVideoBlockParams");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt src_x$LAYOUT = (OfInt)$LAYOUT.select(groupElement("src_x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int src_x
     * }
     */
    public static final OfInt src_x$layout() {
        return src_x$LAYOUT;
    }

    private static final long src_x$OFFSET = $LAYOUT.byteOffset(groupElement("src_x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int src_x
     * }
     */
    public static final long src_x$offset() {
        return src_x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int src_x
     * }
     */
    public static int src_x(MemorySegment struct) {
        return struct.get(src_x$LAYOUT, src_x$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int src_x
     * }
     */
    public static void src_x(MemorySegment struct, int fieldValue) {
        struct.set(src_x$LAYOUT, src_x$OFFSET, fieldValue);
    }

    private static final OfInt src_y$LAYOUT = (OfInt)$LAYOUT.select(groupElement("src_y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int src_y
     * }
     */
    public static final OfInt src_y$layout() {
        return src_y$LAYOUT;
    }

    private static final long src_y$OFFSET = $LAYOUT.byteOffset(groupElement("src_y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int src_y
     * }
     */
    public static final long src_y$offset() {
        return src_y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int src_y
     * }
     */
    public static int src_y(MemorySegment struct) {
        return struct.get(src_y$LAYOUT, src_y$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int src_y
     * }
     */
    public static void src_y(MemorySegment struct, int fieldValue) {
        struct.set(src_y$LAYOUT, src_y$OFFSET, fieldValue);
    }

    private static final OfInt w$LAYOUT = (OfInt)$LAYOUT.select(groupElement("w"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static final OfInt w$layout() {
        return w$LAYOUT;
    }

    private static final long w$OFFSET = $LAYOUT.byteOffset(groupElement("w"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static final long w$offset() {
        return w$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static int w(MemorySegment struct) {
        return struct.get(w$LAYOUT, w$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int w
     * }
     */
    public static void w(MemorySegment struct, int fieldValue) {
        struct.set(w$LAYOUT, w$OFFSET, fieldValue);
    }

    private static final OfInt h$LAYOUT = (OfInt)$LAYOUT.select(groupElement("h"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static final OfInt h$layout() {
        return h$LAYOUT;
    }

    private static final long h$OFFSET = $LAYOUT.byteOffset(groupElement("h"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static final long h$offset() {
        return h$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static int h(MemorySegment struct) {
        return struct.get(h$LAYOUT, h$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int h
     * }
     */
    public static void h(MemorySegment struct, int fieldValue) {
        struct.set(h$LAYOUT, h$OFFSET, fieldValue);
    }

    private static final OfInt delta_qp$LAYOUT = (OfInt)$LAYOUT.select(groupElement("delta_qp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t delta_qp
     * }
     */
    public static final OfInt delta_qp$layout() {
        return delta_qp$LAYOUT;
    }

    private static final long delta_qp$OFFSET = $LAYOUT.byteOffset(groupElement("delta_qp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t delta_qp
     * }
     */
    public static final long delta_qp$offset() {
        return delta_qp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t delta_qp
     * }
     */
    public static int delta_qp(MemorySegment struct) {
        return struct.get(delta_qp$LAYOUT, delta_qp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t delta_qp
     * }
     */
    public static void delta_qp(MemorySegment struct, int fieldValue) {
        struct.set(delta_qp$LAYOUT, delta_qp$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

